package ch.globaz.perseus.businessimpl.services.statsOFS.jaxb;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.10.04 at 12:29:02 PM CEST
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="12" minOccurs="0">
 *         &lt;element name="row">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="monat_id">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                       &lt;minInclusive value="1"/>
 *                       &lt;maxInclusive value="12"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="betrag" type="{}shsBetrag" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "row" })
@XmlRootElement(name = "auszahlung")
public class Auszahlung {

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="monat_id">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *             &lt;minInclusive value="1"/>
     *             &lt;maxInclusive value="12"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="betrag" type="{}shsBetrag" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Row {

        @XmlAttribute
        protected String betrag;
        @XmlAttribute(name = "monat_id")
        protected Integer monatId;

        /**
         * Gets the value of the betrag property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetrag() {
            return betrag;
        }

        /**
         * Gets the value of the monatId property.
         * 
         * @return possible object is {@link Integer }
         * 
         */
        public Integer getMonatId() {
            return monatId;
        }

        /**
         * Sets the value of the betrag property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetrag(String value) {
            betrag = value;
        }

        /**
         * Sets the value of the monatId property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setMonatId(Integer value) {
            monatId = value;
        }

    }

    protected List<Auszahlung.Row> row;

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Auszahlung.Row }
     * 
     * 
     */
    public List<Auszahlung.Row> getRow() {
        if (row == null) {
            row = new ArrayList<Auszahlung.Row>();
        }
        return row;
    }

}
