//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.10.04 at 12:29:02 PM CEST
//

package ch.globaz.perseus.businessimpl.services.statsOFS.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="row" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{}dossierAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}antragsteller"/>
 *         &lt;element ref="{}auszahlung" minOccurs="0"/>
 *         &lt;element ref="{}ausgabe" minOccurs="0"/>
 *         &lt;element ref="{}bedarf" minOccurs="0"/>
 *         &lt;element ref="{}zusatz" minOccurs="0"/>
 *         &lt;element ref="{}massnahme" minOccurs="0"/>
 *         &lt;element ref="{}merkmal" minOccurs="0"/>
 *         &lt;element ref="{}wbsl_einkommensart" minOccurs="0"/>
 *         &lt;element ref="{}ue" minOccurs="0"/>
 *         &lt;element ref="{}hh" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="sh_fremd_id" use="required" type="{}non_empty_string" />
 *       &lt;attribute name="b_neubezuegerrecord" use="required" type="{}shsNullEins" />
 *       &lt;anyAttribute/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "dossier")
public class Dossier {

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{}dossierAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Row {

        @XmlAttribute(name = "antragsart_id")
        protected List<String> antragsartId;
        @XmlAttribute(name = "anz_personen_hh")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger anzPersonenHh;
        @XmlAttribute(name = "anz_personen_ue")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger anzPersonenUe;
        @XmlAttribute(name = "anz_pflegefaelle_hh")
        protected List<String> anzPflegefaelleHh;
        @XmlAttribute(name = "b_beihilfe_kanton")
        protected String bBeihilfeKanton;
        @XmlAttribute(name = "b_ber_skos_2005")
        protected String bBerSkos2005;
        @XmlAttribute(name = "b_bezug_stichtag")
        protected String bBezugStichtag;
        @XmlAttribute(name = "beendigungsgrund_id")
        protected List<String> beendigungsgrundId;
        @XmlAttribute(name = "b_ergaenzung_bund")
        protected String bErgaenzungBund;
        @XmlAttribute(name = "betrag_ausbezahlt_beihilfe_kanton")
        protected String betragAusbezahltBeihilfeKanton;
        @XmlAttribute(name = "betrag_ausbezahlt_el_bund")
        protected String betragAusbezahltElBund;
        @XmlAttribute(name = "betrag_ausbezahlt_zuschuss_gemeinde")
        protected String betragAusbezahltZuschussGemeinde;
        @XmlAttribute(name = "betrag_bruttobedarf")
        protected String betragBruttobedarf;
        @XmlAttribute(name = "betrag_nettobedarf_skos")
        protected String betragNettobedarfSkos;
        @XmlAttribute(name = "betrag_tot_auszahlungen")
        protected String betragTotAuszahlungen;
        @XmlAttribute(name = "betrag_tot_ausz_krankheit")
        protected String betragTotAuszKrankheit;
        @XmlAttribute(name = "betrag_zugesprochen")
        protected String betragZugesprochen;
        @XmlAttribute(name = "betrag_zugesprochen_beihilfe_kanton")
        protected String betragZugesprochenBeihilfeKanton;
        @XmlAttribute(name = "betrag_zugesprochen_el_bund")
        protected String betragZugesprochenElBund;
        @XmlAttribute(name = "betrag_zugesprochen_zuschuss_gemeinde")
        protected String betragZugesprochenZuschussGemeinde;
        @XmlAttribute(name = "b_frueher_unterstuetzt")
        protected String bFrueherUnterstuetzt;
        @XmlAttribute(name = "b_guthaben_pensionskasse")
        protected String bGuthabenPensionskasse;
        @XmlAttribute(name = "b_ueberbrueckung")
        protected String bUeberbrueckung;
        @XmlAttribute(name = "b_vermoegensfreibetrag")
        protected String bVermoegensfreibetrag;
        @XmlAttribute(name = "b_weitere_ue_einkommen")
        protected String bWeitereUeEinkommen;
        @XmlAttribute(name = "b_wohneigentum")
        protected String bWohneigentum;
        @XmlAttribute(name = "b_zuschuss_gemeinde")
        protected String bZuschussGemeinde;
        @XmlAttribute(name = "dat_abgeschlossen")
        protected List<String> datAbgeschlossen;
        @XmlAttribute(name = "dat_aufnahme")
        protected String datAufnahme;
        @XmlAttribute(name = "dat_beginn_anspruch")
        protected String datBeginnAnspruch;
        @XmlAttribute(name = "dat_erste_auszahlung")
        protected List<String> datErsteAuszahlung;
        @XmlAttribute(name = "dat_letzte_zahlung")
        protected List<String> datLetzteZahlung;
        @XmlAttribute(name = "dauer_unterstuetzung_mt")
        protected List<String> dauerUnterstuetzungMt;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger dossiernummer;
        @XmlAttribute(name = "einkommen_detail_id")
        protected List<String> einkommenDetailId;
        @XmlAttribute(name = "gemeinde_id", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger gemeindeId;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger jahr;
        @XmlAttribute(name = "pfleger_id")
        protected List<String> pflegerId;
        @XmlAttribute(name = "sh_leistungsart_id", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger shLeistungsartId;
        @XmlAttribute(name = "sh_leistungstyp_id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger shLeistungstypId;
        @XmlAttribute(name = "sh_wohnsituation_id")
        protected List<String> shWohnsituationId;
        @XmlAttribute(name = "sozialleistungstraeger_id", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger sozialleistungstraegerId;
        @XmlAttribute(name = "ue_monatseinkommen")
        protected String ueMonatseinkommen;
        @XmlAttribute(name = "ue_monatserwerbseinkommen")
        protected String ueMonatserwerbseinkommen;
        @XmlAttribute(name = "ue_monatsleistungen_bedarf")
        protected String ueMonatsleistungenBedarf;
        @XmlAttribute(name = "ue_monatssozialversleistungen")
        protected String ueMonatssozialversleistungen;
        @XmlAttribute(name = "ue_monats_zusatzeinkommen")
        protected String ueMonatsZusatzeinkommen;
        @XmlAttribute(name = "wohnkosten_inkl_nk")
        protected String wohnkostenInklNk;
        @XmlAttribute(name = "wohnungsgroesse_id")
        protected List<String> wohnungsgroesseId;

        /**
         * Gets the value of the antragsartId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the antragsartId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getAntragsartId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getAntragsartId() {
            if (antragsartId == null) {
                antragsartId = new ArrayList<String>();
            }
            return antragsartId;
        }

        /**
         * Gets the value of the anzPersonenHh property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getAnzPersonenHh() {
            return anzPersonenHh;
        }

        /**
         * Gets the value of the anzPersonenUe property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getAnzPersonenUe() {
            return anzPersonenUe;
        }

        /**
         * Gets the value of the anzPflegefaelleHh property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the anzPflegefaelleHh property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getAnzPflegefaelleHh().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getAnzPflegefaelleHh() {
            if (anzPflegefaelleHh == null) {
                anzPflegefaelleHh = new ArrayList<String>();
            }
            return anzPflegefaelleHh;
        }

        /**
         * Gets the value of the bBeihilfeKanton property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBBeihilfeKanton() {
            return bBeihilfeKanton;
        }

        /**
         * Gets the value of the bBerSkos2005 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBBerSkos2005() {
            return bBerSkos2005;
        }

        /**
         * Gets the value of the bBezugStichtag property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBBezugStichtag() {
            return bBezugStichtag;
        }

        /**
         * Gets the value of the beendigungsgrundId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the beendigungsgrundId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getBeendigungsgrundId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getBeendigungsgrundId() {
            if (beendigungsgrundId == null) {
                beendigungsgrundId = new ArrayList<String>();
            }
            return beendigungsgrundId;
        }

        /**
         * Gets the value of the bErgaenzungBund property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBErgaenzungBund() {
            return bErgaenzungBund;
        }

        /**
         * Gets the value of the betragAusbezahltBeihilfeKanton property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragAusbezahltBeihilfeKanton() {
            return betragAusbezahltBeihilfeKanton;
        }

        /**
         * Gets the value of the betragAusbezahltElBund property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragAusbezahltElBund() {
            return betragAusbezahltElBund;
        }

        /**
         * Gets the value of the betragAusbezahltZuschussGemeinde property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragAusbezahltZuschussGemeinde() {
            return betragAusbezahltZuschussGemeinde;
        }

        /**
         * Gets the value of the betragBruttobedarf property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragBruttobedarf() {
            return betragBruttobedarf;
        }

        /**
         * Gets the value of the betragNettobedarfSkos property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragNettobedarfSkos() {
            return betragNettobedarfSkos;
        }

        /**
         * Gets the value of the betragTotAuszahlungen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragTotAuszahlungen() {
            return betragTotAuszahlungen;
        }

        /**
         * Gets the value of the betragTotAuszKrankheit property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragTotAuszKrankheit() {
            return betragTotAuszKrankheit;
        }

        /**
         * Gets the value of the betragZugesprochen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragZugesprochen() {
            return betragZugesprochen;
        }

        /**
         * Gets the value of the betragZugesprochenBeihilfeKanton property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragZugesprochenBeihilfeKanton() {
            return betragZugesprochenBeihilfeKanton;
        }

        /**
         * Gets the value of the betragZugesprochenElBund property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragZugesprochenElBund() {
            return betragZugesprochenElBund;
        }

        /**
         * Gets the value of the betragZugesprochenZuschussGemeinde property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBetragZugesprochenZuschussGemeinde() {
            return betragZugesprochenZuschussGemeinde;
        }

        /**
         * Gets the value of the bFrueherUnterstuetzt property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBFrueherUnterstuetzt() {
            return bFrueherUnterstuetzt;
        }

        /**
         * Gets the value of the bGuthabenPensionskasse property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBGuthabenPensionskasse() {
            return bGuthabenPensionskasse;
        }

        /**
         * Gets the value of the bUeberbrueckung property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBUeberbrueckung() {
            return bUeberbrueckung;
        }

        /**
         * Gets the value of the bVermoegensfreibetrag property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBVermoegensfreibetrag() {
            return bVermoegensfreibetrag;
        }

        /**
         * Gets the value of the bWeitereUeEinkommen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBWeitereUeEinkommen() {
            return bWeitereUeEinkommen;
        }

        /**
         * Gets the value of the bWohneigentum property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBWohneigentum() {
            return bWohneigentum;
        }

        /**
         * Gets the value of the bZuschussGemeinde property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBZuschussGemeinde() {
            return bZuschussGemeinde;
        }

        /**
         * Gets the value of the datAbgeschlossen property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the datAbgeschlossen property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getDatAbgeschlossen().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getDatAbgeschlossen() {
            if (datAbgeschlossen == null) {
                datAbgeschlossen = new ArrayList<String>();
            }
            return datAbgeschlossen;
        }

        /**
         * Gets the value of the datAufnahme property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDatAufnahme() {
            return datAufnahme;
        }

        /**
         * Gets the value of the datBeginnAnspruch property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDatBeginnAnspruch() {
            return datBeginnAnspruch;
        }

        /**
         * Gets the value of the datErsteAuszahlung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the datErsteAuszahlung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getDatErsteAuszahlung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getDatErsteAuszahlung() {
            if (datErsteAuszahlung == null) {
                datErsteAuszahlung = new ArrayList<String>();
            }
            return datErsteAuszahlung;
        }

        /**
         * Gets the value of the datLetzteZahlung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the datLetzteZahlung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getDatLetzteZahlung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getDatLetzteZahlung() {
            if (datLetzteZahlung == null) {
                datLetzteZahlung = new ArrayList<String>();
            }
            return datLetzteZahlung;
        }

        /**
         * Gets the value of the dauerUnterstuetzungMt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the dauerUnterstuetzungMt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getDauerUnterstuetzungMt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getDauerUnterstuetzungMt() {
            if (dauerUnterstuetzungMt == null) {
                dauerUnterstuetzungMt = new ArrayList<String>();
            }
            return dauerUnterstuetzungMt;
        }

        /**
         * Gets the value of the dossiernummer property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getDossiernummer() {
            return dossiernummer;
        }

        /**
         * Gets the value of the einkommenDetailId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the einkommenDetailId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getEinkommenDetailId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getEinkommenDetailId() {
            if (einkommenDetailId == null) {
                einkommenDetailId = new ArrayList<String>();
            }
            return einkommenDetailId;
        }

        /**
         * Gets the value of the gemeindeId property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getGemeindeId() {
            return gemeindeId;
        }

        /**
         * Gets the value of the jahr property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getJahr() {
            return jahr;
        }

        /**
         * Gets the value of the pflegerId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the pflegerId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getPflegerId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getPflegerId() {
            if (pflegerId == null) {
                pflegerId = new ArrayList<String>();
            }
            return pflegerId;
        }

        /**
         * Gets the value of the shLeistungsartId property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getShLeistungsartId() {
            return shLeistungsartId;
        }

        /**
         * Gets the value of the shLeistungstypId property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getShLeistungstypId() {
            return shLeistungstypId;
        }

        /**
         * Gets the value of the shWohnsituationId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the shWohnsituationId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getShWohnsituationId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getShWohnsituationId() {
            if (shWohnsituationId == null) {
                shWohnsituationId = new ArrayList<String>();
            }
            return shWohnsituationId;
        }

        /**
         * Gets the value of the sozialleistungstraegerId property.
         * 
         * @return possible object is {@link BigInteger }
         * 
         */
        public BigInteger getSozialleistungstraegerId() {
            return sozialleistungstraegerId;
        }

        /**
         * Gets the value of the ueMonatseinkommen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getUeMonatseinkommen() {
            return ueMonatseinkommen;
        }

        /**
         * Gets the value of the ueMonatserwerbseinkommen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getUeMonatserwerbseinkommen() {
            return ueMonatserwerbseinkommen;
        }

        /**
         * Gets the value of the ueMonatsleistungenBedarf property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getUeMonatsleistungenBedarf() {
            return ueMonatsleistungenBedarf;
        }

        /**
         * Gets the value of the ueMonatssozialversleistungen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getUeMonatssozialversleistungen() {
            return ueMonatssozialversleistungen;
        }

        /**
         * Gets the value of the ueMonatsZusatzeinkommen property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getUeMonatsZusatzeinkommen() {
            return ueMonatsZusatzeinkommen;
        }

        /**
         * Gets the value of the wohnkostenInklNk property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getWohnkostenInklNk() {
            return wohnkostenInklNk;
        }

        /**
         * Gets the value of the wohnungsgroesseId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the wohnungsgroesseId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getWohnungsgroesseId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         * 
         * 
         */
        public List<String> getWohnungsgroesseId() {
            if (wohnungsgroesseId == null) {
                wohnungsgroesseId = new ArrayList<String>();
            }
            return wohnungsgroesseId;
        }

        /**
         * Sets the value of the anzPersonenHh property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setAnzPersonenHh(BigInteger value) {
            anzPersonenHh = value;
        }

        /**
         * Sets the value of the anzPersonenUe property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setAnzPersonenUe(BigInteger value) {
            anzPersonenUe = value;
        }

        /**
         * Sets the value of the bBeihilfeKanton property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBBeihilfeKanton(String value) {
            bBeihilfeKanton = value;
        }

        /**
         * Sets the value of the bBerSkos2005 property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBBerSkos2005(String value) {
            bBerSkos2005 = value;
        }

        /**
         * Sets the value of the bBezugStichtag property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBBezugStichtag(String value) {
            bBezugStichtag = value;
        }

        /**
         * Sets the value of the bErgaenzungBund property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBErgaenzungBund(String value) {
            bErgaenzungBund = value;
        }

        /**
         * Sets the value of the betragAusbezahltBeihilfeKanton property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragAusbezahltBeihilfeKanton(String value) {
            betragAusbezahltBeihilfeKanton = value;
        }

        /**
         * Sets the value of the betragAusbezahltElBund property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragAusbezahltElBund(String value) {
            betragAusbezahltElBund = value;
        }

        /**
         * Sets the value of the betragAusbezahltZuschussGemeinde property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragAusbezahltZuschussGemeinde(String value) {
            betragAusbezahltZuschussGemeinde = value;
        }

        /**
         * Sets the value of the betragBruttobedarf property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragBruttobedarf(String value) {
            betragBruttobedarf = value;
        }

        /**
         * Sets the value of the betragNettobedarfSkos property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragNettobedarfSkos(String value) {
            betragNettobedarfSkos = value;
        }

        /**
         * Sets the value of the betragTotAuszahlungen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragTotAuszahlungen(String value) {
            betragTotAuszahlungen = value;
        }

        /**
         * Sets the value of the betragTotAuszKrankheit property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragTotAuszKrankheit(String value) {
            betragTotAuszKrankheit = value;
        }

        /**
         * Sets the value of the betragZugesprochen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragZugesprochen(String value) {
            betragZugesprochen = value;
        }

        /**
         * Sets the value of the betragZugesprochenBeihilfeKanton property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragZugesprochenBeihilfeKanton(String value) {
            betragZugesprochenBeihilfeKanton = value;
        }

        /**
         * Sets the value of the betragZugesprochenElBund property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragZugesprochenElBund(String value) {
            betragZugesprochenElBund = value;
        }

        /**
         * Sets the value of the betragZugesprochenZuschussGemeinde property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBetragZugesprochenZuschussGemeinde(String value) {
            betragZugesprochenZuschussGemeinde = value;
        }

        /**
         * Sets the value of the bFrueherUnterstuetzt property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBFrueherUnterstuetzt(String value) {
            bFrueherUnterstuetzt = value;
        }

        /**
         * Sets the value of the bGuthabenPensionskasse property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBGuthabenPensionskasse(String value) {
            bGuthabenPensionskasse = value;
        }

        /**
         * Sets the value of the bUeberbrueckung property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBUeberbrueckung(String value) {
            bUeberbrueckung = value;
        }

        /**
         * Sets the value of the bVermoegensfreibetrag property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBVermoegensfreibetrag(String value) {
            bVermoegensfreibetrag = value;
        }

        /**
         * Sets the value of the bWeitereUeEinkommen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBWeitereUeEinkommen(String value) {
            bWeitereUeEinkommen = value;
        }

        /**
         * Sets the value of the bWohneigentum property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBWohneigentum(String value) {
            bWohneigentum = value;
        }

        /**
         * Sets the value of the bZuschussGemeinde property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBZuschussGemeinde(String value) {
            bZuschussGemeinde = value;
        }

        /**
         * Sets the value of the datAufnahme property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setDatAufnahme(String value) {
            datAufnahme = value;
        }

        /**
         * Sets the value of the datBeginnAnspruch property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setDatBeginnAnspruch(String value) {
            datBeginnAnspruch = value;
        }

        /**
         * Sets the value of the dossiernummer property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setDossiernummer(BigInteger value) {
            dossiernummer = value;
        }

        /**
         * Sets the value of the gemeindeId property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setGemeindeId(BigInteger value) {
            gemeindeId = value;
        }

        /**
         * Sets the value of the jahr property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setJahr(BigInteger value) {
            jahr = value;
        }

        /**
         * Sets the value of the shLeistungsartId property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setShLeistungsartId(BigInteger value) {
            shLeistungsartId = value;
        }

        /**
         * Sets the value of the shLeistungstypId property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setShLeistungstypId(BigInteger value) {
            shLeistungstypId = value;
        }

        /**
         * Sets the value of the sozialleistungstraegerId property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setSozialleistungstraegerId(BigInteger value) {
            sozialleistungstraegerId = value;
        }

        /**
         * Sets the value of the ueMonatseinkommen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setUeMonatseinkommen(String value) {
            ueMonatseinkommen = value;
        }

        /**
         * Sets the value of the ueMonatserwerbseinkommen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setUeMonatserwerbseinkommen(String value) {
            ueMonatserwerbseinkommen = value;
        }

        /**
         * Sets the value of the ueMonatsleistungenBedarf property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setUeMonatsleistungenBedarf(String value) {
            ueMonatsleistungenBedarf = value;
        }

        /**
         * Sets the value of the ueMonatssozialversleistungen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setUeMonatssozialversleistungen(String value) {
            ueMonatssozialversleistungen = value;
        }

        /**
         * Sets the value of the ueMonatsZusatzeinkommen property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setUeMonatsZusatzeinkommen(String value) {
            ueMonatsZusatzeinkommen = value;
        }

        /**
         * Sets the value of the wohnkostenInklNk property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setWohnkostenInklNk(String value) {
            wohnkostenInklNk = value;
        }

    }

    @XmlElement(required = true)
    protected Antragsteller antragsteller;
    protected Ausgabe ausgabe;
    protected Auszahlung auszahlung;
    protected Bedarf bedarf;
    @XmlAttribute(name = "b_neubezuegerrecord", required = true)
    protected String bNeubezuegerrecord;
    protected Hh hh;
    protected Massnahme massnahme;
    protected Merkmal merkmal;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();
    protected Dossier.Row row;
    @XmlAttribute(name = "sh_fremd_id", required = true)
    protected String shFremdId;
    protected Ue ue;
    @XmlElement(name = "wbsl_einkommensart")
    protected WbslEinkommensart wbslEinkommensart;

    protected Zusatz zusatz;

    /**
     * Gets the value of the antragsteller property.
     * 
     * @return possible object is {@link Antragsteller }
     * 
     */
    public Antragsteller getAntragsteller() {
        return antragsteller;
    }

    /**
     * Gets the value of the ausgabe property.
     * 
     * @return possible object is {@link Ausgabe }
     * 
     */
    public Ausgabe getAusgabe() {
        return ausgabe;
    }

    /**
     * Gets the value of the auszahlung property.
     * 
     * @return possible object is {@link Auszahlung }
     * 
     */
    public Auszahlung getAuszahlung() {
        return auszahlung;
    }

    /**
     * Gets the value of the bedarf property.
     * 
     * @return possible object is {@link Bedarf }
     * 
     */
    public Bedarf getBedarf() {
        return bedarf;
    }

    /**
     * Gets the value of the bNeubezuegerrecord property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBNeubezuegerrecord() {
        return bNeubezuegerrecord;
    }

    /**
     * Gets the value of the hh property.
     * 
     * @return possible object is {@link Hh }
     * 
     */
    public Hh getHh() {
        return hh;
    }

    /**
     * Gets the value of the massnahme property.
     * 
     * @return possible object is {@link Massnahme }
     * 
     */
    public Massnahme getMassnahme() {
        return massnahme;
    }

    /**
     * Gets the value of the merkmal property.
     * 
     * @return possible object is {@link Merkmal }
     * 
     */
    public Merkmal getMerkmal() {
        return merkmal;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute by updating the map directly. Because of
     * this design, there's no setter.
     * 
     * 
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

    /**
     * Gets the value of the row property.
     * 
     * @return possible object is {@link Dossier.Row }
     * 
     */
    public Dossier.Row getRow() {
        return row;
    }

    /**
     * Gets the value of the shFremdId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShFremdId() {
        return shFremdId;
    }

    /**
     * Gets the value of the ue property.
     * 
     * @return possible object is {@link Ue }
     * 
     */
    public Ue getUe() {
        return ue;
    }

    /**
     * Gets the value of the wbslEinkommensart property.
     * 
     * @return possible object is {@link WbslEinkommensart }
     * 
     */
    public WbslEinkommensart getWbslEinkommensart() {
        return wbslEinkommensart;
    }

    /**
     * Gets the value of the zusatz property.
     * 
     * @return possible object is {@link Zusatz }
     * 
     */
    public Zusatz getZusatz() {
        return zusatz;
    }

    /**
     * Sets the value of the antragsteller property.
     * 
     * @param value
     *            allowed object is {@link Antragsteller }
     * 
     */
    public void setAntragsteller(Antragsteller value) {
        antragsteller = value;
    }

    /**
     * Sets the value of the ausgabe property.
     * 
     * @param value
     *            allowed object is {@link Ausgabe }
     * 
     */
    public void setAusgabe(Ausgabe value) {
        ausgabe = value;
    }

    /**
     * Sets the value of the auszahlung property.
     * 
     * @param value
     *            allowed object is {@link Auszahlung }
     * 
     */
    public void setAuszahlung(Auszahlung value) {
        auszahlung = value;
    }

    /**
     * Sets the value of the bedarf property.
     * 
     * @param value
     *            allowed object is {@link Bedarf }
     * 
     */
    public void setBedarf(Bedarf value) {
        bedarf = value;
    }

    /**
     * Sets the value of the bNeubezuegerrecord property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBNeubezuegerrecord(String value) {
        bNeubezuegerrecord = value;
    }

    /**
     * Sets the value of the hh property.
     * 
     * @param value
     *            allowed object is {@link Hh }
     * 
     */
    public void setHh(Hh value) {
        hh = value;
    }

    /**
     * Sets the value of the massnahme property.
     * 
     * @param value
     *            allowed object is {@link Massnahme }
     * 
     */
    public void setMassnahme(Massnahme value) {
        massnahme = value;
    }

    /**
     * Sets the value of the merkmal property.
     * 
     * @param value
     *            allowed object is {@link Merkmal }
     * 
     */
    public void setMerkmal(Merkmal value) {
        merkmal = value;
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *            allowed object is {@link Dossier.Row }
     * 
     */
    public void setRow(Dossier.Row value) {
        row = value;
    }

    /**
     * Sets the value of the shFremdId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShFremdId(String value) {
        shFremdId = value;
    }

    /**
     * Sets the value of the ue property.
     * 
     * @param value
     *            allowed object is {@link Ue }
     * 
     */
    public void setUe(Ue value) {
        ue = value;
    }

    /**
     * Sets the value of the wbslEinkommensart property.
     * 
     * @param value
     *            allowed object is {@link WbslEinkommensart }
     * 
     */
    public void setWbslEinkommensart(WbslEinkommensart value) {
        wbslEinkommensart = value;
    }

    /**
     * Sets the value of the zusatz property.
     * 
     * @param value
     *            allowed object is {@link Zusatz }
     * 
     */
    public void setZusatz(Zusatz value) {
        zusatz = value;
    }

}
