/*
 * Generated by JasperReports - 05.11.15 13:41
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class DRACO_PREIMP_DECSAL_MASTER_2 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_P_3 = null;
    private JRFillParameter parameter_P_CAISSE = null;
    private JRFillParameter parameter_P_AF = null;
    private JRFillParameter parameter_L_19 = null;
    private JRFillParameter parameter_L_COL_1 = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_P_CATEGORIE_PERSONNE = null;
    private JRFillParameter parameter_L_18 = null;
    private JRFillParameter parameter_P_PAGE_DEBUT = null;
    private JRFillParameter parameter_P_CANTON = null;
    private JRFillParameter parameter_L_17 = null;
    private JRFillParameter parameter_P_2 = null;
    private JRFillParameter parameter_P_NOMPRENOMAFFILIE = null;
    private JRFillParameter parameter_P_PAGE_FIN = null;
    private JRFillParameter parameter_L_8 = null;
    private JRFillParameter parameter_P_NUMEROAFFILIE = null;
    private JRFillParameter parameter_P_HEAD_3 = null;
    private JRFillParameter parameter_L_15 = null;
    private JRFillParameter parameter_L_1 = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_P_PAGE = null;
    private JRFillParameter parameter_P_AFPRESTEXTE = null;
    private JRFillParameter parameter_L_16 = null;
    private JRFillParameter parameter_L_2 = null;
    private JRFillParameter parameter_L_3 = null;
    private JRFillParameter parameter_MODEL_PATH = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_P_TEXTELIBRE = null;
    private JRFillParameter parameter_L_10 = null;
    private JRFillParameter parameter_L_7 = null;
    private JRFillParameter parameter_P_HEAD_6 = null;
    private JRFillParameter parameter_L_11 = null;
    private JRFillParameter parameter_P_FFPP = null;
    private JRFillParameter parameter_L_12 = null;
    private JRFillParameter parameter_P_1 = null;
    private JRFillParameter parameter_P_HEAD_4 = null;
    private JRFillParameter parameter_P_TEXTE_CATEGORIE_PERSONNEL = null;
    private JRFillParameter parameter_P_HEAD_1 = null;
    private JRFillParameter parameter_P_ADRESSE = null;
    private JRFillParameter parameter_P_AMAT = null;
    private JRFillParameter parameter_L_9 = null;
    private JRFillParameter parameter_L_14 = null;
    private JRFillParameter parameter_P_HEAD_2 = null;
    private JRFillParameter parameter_P_SUBREPORT_HEADER = null;
    private JRFillParameter parameter_P_LPP = null;
    private JRFillParameter parameter_P_ASSURANCE = null;
    private JRFillParameter parameter_L_20 = null;
    private JRFillParameter parameter_L_6 = null;
    private JRFillParameter parameter_P_SAISONNIER = null;
    private JRFillParameter parameter_L_5 = null;
    private JRFillParameter parameter_P_ANNEEDECLARATION_2 = null;
    private JRFillParameter parameter_L_4 = null;
    private JRFillParameter parameter_L_13 = null;
    private JRFillParameter parameter_P_AFPRES = null;
    private JRFillParameter parameter_P_HEAD_5 = null;

    private JRFillField field_COL_9 = null;
    private JRFillField field_COL_4 = null;
    private JRFillField field_COL_14 = null;
    private JRFillField field_COL_11 = null;
    private JRFillField field_pageDebut = null;
    private JRFillField field_COL_8 = null;
    private JRFillField field_COL_5 = null;
    private JRFillField field_COL_1 = null;
    private JRFillField field_COL_13 = null;
    private JRFillField field_COL_12 = null;
    private JRFillField field_COL_6 = null;
    private JRFillField field_COL_2 = null;
    private JRFillField field_COL_10 = null;
    private JRFillField field_COL_15 = null;
    private JRFillField field_COL_3 = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_LOGO = null;
    private JRFillVariable variable_SUM_COL_9 = null;
    private JRFillVariable variable_SUM_COL_10 = null;
    private JRFillVariable variable_SUM_COL_11 = null;
    private JRFillVariable variable_SUM_COL_13 = null;
    private JRFillVariable variable_SUM_COL_14 = null;
    private JRFillVariable variable_ESSAI_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_P_3 = (JRFillParameter)parsm.get("P_3");
        parameter_P_CAISSE = (JRFillParameter)parsm.get("P_CAISSE");
        parameter_P_AF = (JRFillParameter)parsm.get("P_AF");
        parameter_L_19 = (JRFillParameter)parsm.get("L_19");
        parameter_L_COL_1 = (JRFillParameter)parsm.get("L_COL_1");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_P_CATEGORIE_PERSONNE = (JRFillParameter)parsm.get("P_CATEGORIE_PERSONNE");
        parameter_L_18 = (JRFillParameter)parsm.get("L_18");
        parameter_P_PAGE_DEBUT = (JRFillParameter)parsm.get("P_PAGE_DEBUT");
        parameter_P_CANTON = (JRFillParameter)parsm.get("P_CANTON");
        parameter_L_17 = (JRFillParameter)parsm.get("L_17");
        parameter_P_2 = (JRFillParameter)parsm.get("P_2");
        parameter_P_NOMPRENOMAFFILIE = (JRFillParameter)parsm.get("P_NOMPRENOMAFFILIE");
        parameter_P_PAGE_FIN = (JRFillParameter)parsm.get("P_PAGE_FIN");
        parameter_L_8 = (JRFillParameter)parsm.get("L_8");
        parameter_P_NUMEROAFFILIE = (JRFillParameter)parsm.get("P_NUMEROAFFILIE");
        parameter_P_HEAD_3 = (JRFillParameter)parsm.get("P_HEAD_3");
        parameter_L_15 = (JRFillParameter)parsm.get("L_15");
        parameter_L_1 = (JRFillParameter)parsm.get("L_1");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_P_PAGE = (JRFillParameter)parsm.get("P_PAGE");
        parameter_P_AFPRESTEXTE = (JRFillParameter)parsm.get("P_AFPRESTEXTE");
        parameter_L_16 = (JRFillParameter)parsm.get("L_16");
        parameter_L_2 = (JRFillParameter)parsm.get("L_2");
        parameter_L_3 = (JRFillParameter)parsm.get("L_3");
        parameter_MODEL_PATH = (JRFillParameter)parsm.get("MODEL_PATH");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");
        parameter_P_TEXTELIBRE = (JRFillParameter)parsm.get("P_TEXTELIBRE");
        parameter_L_10 = (JRFillParameter)parsm.get("L_10");
        parameter_L_7 = (JRFillParameter)parsm.get("L_7");
        parameter_P_HEAD_6 = (JRFillParameter)parsm.get("P_HEAD_6");
        parameter_L_11 = (JRFillParameter)parsm.get("L_11");
        parameter_P_FFPP = (JRFillParameter)parsm.get("P_FFPP");
        parameter_L_12 = (JRFillParameter)parsm.get("L_12");
        parameter_P_1 = (JRFillParameter)parsm.get("P_1");
        parameter_P_HEAD_4 = (JRFillParameter)parsm.get("P_HEAD_4");
        parameter_P_TEXTE_CATEGORIE_PERSONNEL = (JRFillParameter)parsm.get("P_TEXTE_CATEGORIE_PERSONNEL");
        parameter_P_HEAD_1 = (JRFillParameter)parsm.get("P_HEAD_1");
        parameter_P_ADRESSE = (JRFillParameter)parsm.get("P_ADRESSE");
        parameter_P_AMAT = (JRFillParameter)parsm.get("P_AMAT");
        parameter_L_9 = (JRFillParameter)parsm.get("L_9");
        parameter_L_14 = (JRFillParameter)parsm.get("L_14");
        parameter_P_HEAD_2 = (JRFillParameter)parsm.get("P_HEAD_2");
        parameter_P_SUBREPORT_HEADER = (JRFillParameter)parsm.get("P_SUBREPORT_HEADER");
        parameter_P_LPP = (JRFillParameter)parsm.get("P_LPP");
        parameter_P_ASSURANCE = (JRFillParameter)parsm.get("P_ASSURANCE");
        parameter_L_20 = (JRFillParameter)parsm.get("L_20");
        parameter_L_6 = (JRFillParameter)parsm.get("L_6");
        parameter_P_SAISONNIER = (JRFillParameter)parsm.get("P_SAISONNIER");
        parameter_L_5 = (JRFillParameter)parsm.get("L_5");
        parameter_P_ANNEEDECLARATION_2 = (JRFillParameter)parsm.get("P_ANNEEDECLARATION_2");
        parameter_L_4 = (JRFillParameter)parsm.get("L_4");
        parameter_L_13 = (JRFillParameter)parsm.get("L_13");
        parameter_P_AFPRES = (JRFillParameter)parsm.get("P_AFPRES");
        parameter_P_HEAD_5 = (JRFillParameter)parsm.get("P_HEAD_5");

        field_COL_9 = (JRFillField)fldsm.get("COL_9");
        field_COL_4 = (JRFillField)fldsm.get("COL_4");
        field_COL_14 = (JRFillField)fldsm.get("COL_14");
        field_COL_11 = (JRFillField)fldsm.get("COL_11");
        field_pageDebut = (JRFillField)fldsm.get("pageDebut");
        field_COL_8 = (JRFillField)fldsm.get("COL_8");
        field_COL_5 = (JRFillField)fldsm.get("COL_5");
        field_COL_1 = (JRFillField)fldsm.get("COL_1");
        field_COL_13 = (JRFillField)fldsm.get("COL_13");
        field_COL_12 = (JRFillField)fldsm.get("COL_12");
        field_COL_6 = (JRFillField)fldsm.get("COL_6");
        field_COL_2 = (JRFillField)fldsm.get("COL_2");
        field_COL_10 = (JRFillField)fldsm.get("COL_10");
        field_COL_15 = (JRFillField)fldsm.get("COL_15");
        field_COL_3 = (JRFillField)fldsm.get("COL_3");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_LOGO = (JRFillVariable)varsm.get("LOGO");
        variable_SUM_COL_9 = (JRFillVariable)varsm.get("SUM_COL_9");
        variable_SUM_COL_10 = (JRFillVariable)varsm.get("SUM_COL_10");
        variable_SUM_COL_11 = (JRFillVariable)varsm.get("SUM_COL_11");
        variable_SUM_COL_13 = (JRFillVariable)varsm.get("SUM_COL_13");
        variable_SUM_COL_14 = (JRFillVariable)varsm.get("SUM_COL_14");
        variable_ESSAI_COUNT = (JRFillVariable)varsm.get("ESSAI_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 4 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 48 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_6.getValue()));
                break;
            }
            case 61 : // textField_29
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_17.getValue()));
                break;
            }
            case 25 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_3.getValue()));
                break;
            }
            case 43 : // textField_13
            {
                value = (java.lang.String)(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getValue())));
                break;
            }
            case 21 : // group_ESSAI
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 15 : // variable_SUM_COL_11
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_11.getValue())));
                break;
            }
            case 62 : // textField_30
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_19.getValue()));
                break;
            }
            case 3 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 33 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SUBREPORT_HEADER.getValue()));
                break;
            }
            case 44 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_1.getValue()));
                break;
            }
            case 63 : // textField_31
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_18.getValue()));
                break;
            }
            case 65 : // textField_33
            {
                value = (java.lang.String)(((java.lang.String)field_COL_1.getValue()));
                break;
            }
            case 67 : // textField_35
            {
                value = (java.lang.String)(((java.lang.String)field_COL_6.getValue()));
                break;
            }
            case 57 : // textField_26
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_15.getValue()));
                break;
            }
            case 0 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 82 : // textField_48
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_11.getValue()));
                break;
            }
            case 77 : // textField_43
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_11.getValue()));
                break;
            }
            case 78 : // textField_44
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_13.getValue()));
                break;
            }
            case 76 : // textField_42
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_10.getValue()));
                break;
            }
            case 34 : // textField_8
            {
                value = (java.lang.String)("Page "+String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getValue())) + "/");
                break;
            }
            case 41 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NOMPRENOMAFFILIE.getValue()));
                break;
            }
            case 68 : // textField_36
            {
                value = (java.lang.String)(((java.lang.String)field_COL_5.getValue()));
                break;
            }
            case 13 : // variable_SUM_COL_10
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_10.getValue())));
                break;
            }
            case 72 : // textField_39
            {
                value = (java.lang.String)(((java.lang.String)field_COL_8.getValue()));
                break;
            }
            case 73 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_1.getValue())!=null));
                break;
            }
            case 60 : // textField_28
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_20.getValue()));
                break;
            }
            case 14 : // variableInitialValue_SUM_COL_10
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 36 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getValue()).intValue()>1));
                break;
            }
            case 26 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_4.getValue()));
                break;
            }
            case 23 : // variableInitialValue_ESSAI_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 40 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getValue()).intValue()>1));
                break;
            }
            case 69 : // textField_37
            {
                value = (java.lang.String)(((java.lang.String)field_COL_4.getValue()));
                break;
            }
            case 10 : // variable_LOGO
            {
                value = (java.lang.String)(((java.lang.String)parameter_MODEL_PATH.getValue())+"caisse_logo.gif");
                break;
            }
            case 11 : // variable_SUM_COL_9
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_9.getValue())));
                break;
            }
            case 47 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_7.getValue()));
                break;
            }
            case 53 : // textField_23
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_2.getValue()));
                break;
            }
            case 32 : // parametersMap_1
            {
                value = (java.util.Map)(new java.util.HashMap(((java.util.Map)parameter_REPORT_PARAMETERS_MAP.getValue())));
                break;
            }
            case 12 : // variableInitialValue_SUM_COL_9
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 17 : // variable_SUM_COL_13
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_13.getValue())));
                break;
            }
            case 83 : // textField_49
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_13.getValue()));
                break;
            }
            case 71 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_L_15.getValue())!=null));
                break;
            }
            case 19 : // variable_SUM_COL_14
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_14.getValue())));
                break;
            }
            case 45 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_4.getValue()));
                break;
            }
            case 1 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 42 : // textField_12
            {
                value = (java.lang.String)("Page "+String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getValue())) + "/");
                break;
            }
            case 64 : // textField_32
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_3.getValue()));
                break;
            }
            case 27 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_6.getValue()));
                break;
            }
            case 79 : // textField_45
            {
                value = (java.lang.String)(((java.lang.String)field_COL_15.getValue()));
                break;
            }
            case 2 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : // parameterDefaultValue_MODEL_PATH
            {
                value = (java.lang.String)("D:/Websphere/webavs_workspace/webavs/Web Content/dracoRoot/model");
                break;
            }
            case 66 : // textField_34
            {
                value = (java.lang.String)(((java.lang.String)field_COL_2.getValue()));
                break;
            }
            case 38 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getValue()).intValue()>1));
                break;
            }
            case 74 : // textField_40
            {
                value = (java.lang.String)(((java.lang.String)field_COL_12.getValue()));
                break;
            }
            case 28 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_5.getValue()));
                break;
            }
            case 59 : // textField_27
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_11.getValue()));
                break;
            }
            case 75 : // textField_41
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_9.getValue()));
                break;
            }
            case 80 : // textField_46
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_9.getValue()));
                break;
            }
            case 81 : // textField_47
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_10.getValue()));
                break;
            }
            case 37 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getValue()).intValue()>1));
                break;
            }
            case 30 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_TEXTE_CATEGORIE_PERSONNEL.getValue())!=null));
                break;
            }
            case 52 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_14.getValue()));
                break;
            }
            case 55 : // textField_25
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_8.getValue()));
                break;
            }
            case 46 : // textField_16
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_5.getValue()));
                break;
            }
            case 9 : // parameterDefaultValue_P_ADRESSE
            {
                value = (java.lang.String)("C'EST VIDE");
                break;
            }
            case 24 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_2.getValue()));
                break;
            }
            case 49 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_13.getValue()));
                break;
            }
            case 50 : // textField_20
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_14.getValue()));
                break;
            }
            case 5 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 58 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_L_15.getValue())!=null));
                break;
            }
            case 7 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 31 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TEXTE_CATEGORIE_PERSONNEL.getValue()));
                break;
            }
            case 16 : // variableInitialValue_SUM_COL_11
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 20 : // variableInitialValue_SUM_COL_14
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 29 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ADRESSE.getValue()));
                break;
            }
            case 70 : // textField_38
            {
                value = (java.lang.String)(((java.lang.String)field_COL_3.getValue()));
                break;
            }
            case 39 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NUMEROAFFILIE.getValue()));
                break;
            }
            case 54 : // textField_24
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_9.getValue()));
                break;
            }
            case 35 : // textField_9
            {
                value = (java.lang.String)(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getValue())));
                break;
            }
            case 56 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_1.getValue())!=null));
                break;
            }
            case 18 : // variableInitialValue_SUM_COL_13
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 6 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 51 : // textField_21
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_13.getValue()));
                break;
            }
            case 22 : // variable_ESSAI_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 4 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 48 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_6.getValue()));
                break;
            }
            case 61 : // textField_29
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_17.getValue()));
                break;
            }
            case 25 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_3.getValue()));
                break;
            }
            case 43 : // textField_13
            {
                value = (java.lang.String)(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())));
                break;
            }
            case 21 : // group_ESSAI
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 15 : // variable_SUM_COL_11
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getOldValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_11.getOldValue())));
                break;
            }
            case 62 : // textField_30
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_19.getValue()));
                break;
            }
            case 3 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 33 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SUBREPORT_HEADER.getValue()));
                break;
            }
            case 44 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_1.getValue()));
                break;
            }
            case 63 : // textField_31
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_18.getValue()));
                break;
            }
            case 65 : // textField_33
            {
                value = (java.lang.String)(((java.lang.String)field_COL_1.getOldValue()));
                break;
            }
            case 67 : // textField_35
            {
                value = (java.lang.String)(((java.lang.String)field_COL_6.getOldValue()));
                break;
            }
            case 57 : // textField_26
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_15.getValue()));
                break;
            }
            case 0 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 82 : // textField_48
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_11.getOldValue()));
                break;
            }
            case 77 : // textField_43
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_11.getOldValue()));
                break;
            }
            case 78 : // textField_44
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_13.getOldValue()));
                break;
            }
            case 76 : // textField_42
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_10.getOldValue()));
                break;
            }
            case 34 : // textField_8
            {
                value = (java.lang.String)("Page "+String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())) + "/");
                break;
            }
            case 41 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NOMPRENOMAFFILIE.getValue()));
                break;
            }
            case 68 : // textField_36
            {
                value = (java.lang.String)(((java.lang.String)field_COL_5.getOldValue()));
                break;
            }
            case 13 : // variable_SUM_COL_10
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getOldValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_10.getOldValue())));
                break;
            }
            case 72 : // textField_39
            {
                value = (java.lang.String)(((java.lang.String)field_COL_8.getOldValue()));
                break;
            }
            case 73 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_1.getValue())!=null));
                break;
            }
            case 60 : // textField_28
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_20.getValue()));
                break;
            }
            case 14 : // variableInitialValue_SUM_COL_10
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 36 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()).intValue()>1));
                break;
            }
            case 26 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_4.getValue()));
                break;
            }
            case 23 : // variableInitialValue_ESSAI_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 40 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()).intValue()>1));
                break;
            }
            case 69 : // textField_37
            {
                value = (java.lang.String)(((java.lang.String)field_COL_4.getOldValue()));
                break;
            }
            case 10 : // variable_LOGO
            {
                value = (java.lang.String)(((java.lang.String)parameter_MODEL_PATH.getValue())+"caisse_logo.gif");
                break;
            }
            case 11 : // variable_SUM_COL_9
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getOldValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_9.getOldValue())));
                break;
            }
            case 47 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_7.getValue()));
                break;
            }
            case 53 : // textField_23
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_2.getValue()));
                break;
            }
            case 32 : // parametersMap_1
            {
                value = (java.util.Map)(new java.util.HashMap(((java.util.Map)parameter_REPORT_PARAMETERS_MAP.getValue())));
                break;
            }
            case 12 : // variableInitialValue_SUM_COL_9
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 17 : // variable_SUM_COL_13
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getOldValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_13.getOldValue())));
                break;
            }
            case 83 : // textField_49
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_13.getOldValue()));
                break;
            }
            case 71 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_L_15.getValue())!=null));
                break;
            }
            case 19 : // variable_SUM_COL_14
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getOldValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_14.getOldValue())));
                break;
            }
            case 45 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_4.getValue()));
                break;
            }
            case 1 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 42 : // textField_12
            {
                value = (java.lang.String)("Page "+String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())) + "/");
                break;
            }
            case 64 : // textField_32
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_3.getValue()));
                break;
            }
            case 27 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_6.getValue()));
                break;
            }
            case 79 : // textField_45
            {
                value = (java.lang.String)(((java.lang.String)field_COL_15.getOldValue()));
                break;
            }
            case 2 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : // parameterDefaultValue_MODEL_PATH
            {
                value = (java.lang.String)("D:/Websphere/webavs_workspace/webavs/Web Content/dracoRoot/model");
                break;
            }
            case 66 : // textField_34
            {
                value = (java.lang.String)(((java.lang.String)field_COL_2.getOldValue()));
                break;
            }
            case 38 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()).intValue()>1));
                break;
            }
            case 74 : // textField_40
            {
                value = (java.lang.String)(((java.lang.String)field_COL_12.getOldValue()));
                break;
            }
            case 28 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_5.getValue()));
                break;
            }
            case 59 : // textField_27
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_11.getValue()));
                break;
            }
            case 75 : // textField_41
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_9.getOldValue()));
                break;
            }
            case 80 : // textField_46
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_9.getOldValue()));
                break;
            }
            case 81 : // textField_47
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_10.getOldValue()));
                break;
            }
            case 37 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()).intValue()>1));
                break;
            }
            case 30 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_TEXTE_CATEGORIE_PERSONNEL.getValue())!=null));
                break;
            }
            case 52 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_14.getValue()));
                break;
            }
            case 55 : // textField_25
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_8.getValue()));
                break;
            }
            case 46 : // textField_16
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_5.getValue()));
                break;
            }
            case 9 : // parameterDefaultValue_P_ADRESSE
            {
                value = (java.lang.String)("C'EST VIDE");
                break;
            }
            case 24 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_2.getValue()));
                break;
            }
            case 49 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_13.getValue()));
                break;
            }
            case 50 : // textField_20
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_14.getValue()));
                break;
            }
            case 5 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 58 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_L_15.getValue())!=null));
                break;
            }
            case 7 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 31 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TEXTE_CATEGORIE_PERSONNEL.getValue()));
                break;
            }
            case 16 : // variableInitialValue_SUM_COL_11
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 20 : // variableInitialValue_SUM_COL_14
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 29 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ADRESSE.getValue()));
                break;
            }
            case 70 : // textField_38
            {
                value = (java.lang.String)(((java.lang.String)field_COL_3.getOldValue()));
                break;
            }
            case 39 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NUMEROAFFILIE.getValue()));
                break;
            }
            case 54 : // textField_24
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_9.getValue()));
                break;
            }
            case 35 : // textField_9
            {
                value = (java.lang.String)(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())));
                break;
            }
            case 56 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_1.getValue())!=null));
                break;
            }
            case 18 : // variableInitialValue_SUM_COL_13
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 6 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 51 : // textField_21
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_13.getValue()));
                break;
            }
            case 22 : // variable_ESSAI_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 4 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 48 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_6.getValue()));
                break;
            }
            case 61 : // textField_29
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_17.getValue()));
                break;
            }
            case 25 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_3.getValue()));
                break;
            }
            case 43 : // textField_13
            {
                value = (java.lang.String)(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())));
                break;
            }
            case 21 : // group_ESSAI
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 15 : // variable_SUM_COL_11
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_11.getValue())));
                break;
            }
            case 62 : // textField_30
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_19.getValue()));
                break;
            }
            case 3 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 33 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SUBREPORT_HEADER.getValue()));
                break;
            }
            case 44 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_1.getValue()));
                break;
            }
            case 63 : // textField_31
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_18.getValue()));
                break;
            }
            case 65 : // textField_33
            {
                value = (java.lang.String)(((java.lang.String)field_COL_1.getValue()));
                break;
            }
            case 67 : // textField_35
            {
                value = (java.lang.String)(((java.lang.String)field_COL_6.getValue()));
                break;
            }
            case 57 : // textField_26
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_15.getValue()));
                break;
            }
            case 0 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 82 : // textField_48
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_11.getEstimatedValue()));
                break;
            }
            case 77 : // textField_43
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_11.getValue()));
                break;
            }
            case 78 : // textField_44
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_13.getValue()));
                break;
            }
            case 76 : // textField_42
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_10.getValue()));
                break;
            }
            case 34 : // textField_8
            {
                value = (java.lang.String)("Page "+String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())) + "/");
                break;
            }
            case 41 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NOMPRENOMAFFILIE.getValue()));
                break;
            }
            case 68 : // textField_36
            {
                value = (java.lang.String)(((java.lang.String)field_COL_5.getValue()));
                break;
            }
            case 13 : // variable_SUM_COL_10
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_10.getValue())));
                break;
            }
            case 72 : // textField_39
            {
                value = (java.lang.String)(((java.lang.String)field_COL_8.getValue()));
                break;
            }
            case 73 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_1.getValue())!=null));
                break;
            }
            case 60 : // textField_28
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_20.getValue()));
                break;
            }
            case 14 : // variableInitialValue_SUM_COL_10
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 36 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()).intValue()>1));
                break;
            }
            case 26 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_4.getValue()));
                break;
            }
            case 23 : // variableInitialValue_ESSAI_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 40 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()).intValue()>1));
                break;
            }
            case 69 : // textField_37
            {
                value = (java.lang.String)(((java.lang.String)field_COL_4.getValue()));
                break;
            }
            case 10 : // variable_LOGO
            {
                value = (java.lang.String)(((java.lang.String)parameter_MODEL_PATH.getValue())+"caisse_logo.gif");
                break;
            }
            case 11 : // variable_SUM_COL_9
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_9.getValue())));
                break;
            }
            case 47 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_7.getValue()));
                break;
            }
            case 53 : // textField_23
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_2.getValue()));
                break;
            }
            case 32 : // parametersMap_1
            {
                value = (java.util.Map)(new java.util.HashMap(((java.util.Map)parameter_REPORT_PARAMETERS_MAP.getValue())));
                break;
            }
            case 12 : // variableInitialValue_SUM_COL_9
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 17 : // variable_SUM_COL_13
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_13.getValue())));
                break;
            }
            case 83 : // textField_49
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_13.getEstimatedValue()));
                break;
            }
            case 71 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_L_15.getValue())!=null));
                break;
            }
            case 19 : // variable_SUM_COL_14
            {
                value = (java.lang.Double)(((((java.lang.String)field_COL_2.getValue()).toString().equals("REPORT"))?new Double(0):((java.lang.Double)field_COL_14.getValue())));
                break;
            }
            case 45 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_4.getValue()));
                break;
            }
            case 1 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 42 : // textField_12
            {
                value = (java.lang.String)("Page "+String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())) + "/");
                break;
            }
            case 64 : // textField_32
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_3.getValue()));
                break;
            }
            case 27 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_6.getValue()));
                break;
            }
            case 79 : // textField_45
            {
                value = (java.lang.String)(((java.lang.String)field_COL_15.getValue()));
                break;
            }
            case 2 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : // parameterDefaultValue_MODEL_PATH
            {
                value = (java.lang.String)("D:/Websphere/webavs_workspace/webavs/Web Content/dracoRoot/model");
                break;
            }
            case 66 : // textField_34
            {
                value = (java.lang.String)(((java.lang.String)field_COL_2.getValue()));
                break;
            }
            case 38 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()).intValue()>1));
                break;
            }
            case 74 : // textField_40
            {
                value = (java.lang.String)(((java.lang.String)field_COL_12.getValue()));
                break;
            }
            case 28 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_5.getValue()));
                break;
            }
            case 59 : // textField_27
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_11.getValue()));
                break;
            }
            case 75 : // textField_41
            {
                value = (java.lang.Double)(((java.lang.Double)field_COL_9.getValue()));
                break;
            }
            case 80 : // textField_46
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_9.getEstimatedValue()));
                break;
            }
            case 81 : // textField_47
            {
                value = (java.lang.Double)(((java.lang.Double)variable_SUM_COL_10.getEstimatedValue()));
                break;
            }
            case 37 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()).intValue()>1));
                break;
            }
            case 30 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_TEXTE_CATEGORIE_PERSONNEL.getValue())!=null));
                break;
            }
            case 52 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_14.getValue()));
                break;
            }
            case 55 : // textField_25
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_8.getValue()));
                break;
            }
            case 46 : // textField_16
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_5.getValue()));
                break;
            }
            case 9 : // parameterDefaultValue_P_ADRESSE
            {
                value = (java.lang.String)("C'EST VIDE");
                break;
            }
            case 24 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_HEAD_2.getValue()));
                break;
            }
            case 49 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_13.getValue()));
                break;
            }
            case 50 : // textField_20
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_14.getValue()));
                break;
            }
            case 5 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 58 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_L_15.getValue())!=null));
                break;
            }
            case 7 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 31 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TEXTE_CATEGORIE_PERSONNEL.getValue()));
                break;
            }
            case 16 : // variableInitialValue_SUM_COL_11
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 20 : // variableInitialValue_SUM_COL_14
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 29 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ADRESSE.getValue()));
                break;
            }
            case 70 : // textField_38
            {
                value = (java.lang.String)(((java.lang.String)field_COL_3.getValue()));
                break;
            }
            case 39 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NUMEROAFFILIE.getValue()));
                break;
            }
            case 54 : // textField_24
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_9.getValue()));
                break;
            }
            case 35 : // textField_9
            {
                value = (java.lang.String)(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())));
                break;
            }
            case 56 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_1.getValue())!=null));
                break;
            }
            case 18 : // variableInitialValue_SUM_COL_13
            {
                value = (java.lang.Double)(new Double(0.00));
                break;
            }
            case 6 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 51 : // textField_21
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_13.getValue()));
                break;
            }
            case 22 : // variable_ESSAI_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
