//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * 
 * Paquet codes application 31 + 32 + 34: Annonce des indemnités assurance-chômage pour l'inscription au CI
 * 
 * 
 * <p>
 * Java class for ALVEntschaedigungenMeldung_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ALVEntschaedigungenMeldung_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KasseZweigstelleIKFuehrend" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
 *         &lt;element name="Verarbeitungsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type"/>
 *         &lt;element name="Aufzeichnungen" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IKKopf">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13StellenOderUnbekannt_Type"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EintragungIKMeldung" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ListeFolgerecordNr" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FolgerecordNr" type="{http://www.zas.admin.ch/RC}FolgerecordNr_Type" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="AKAbrechnungsNr" type="{http://www.zas.admin.ch/RC}AKAbrechnungsNr_Type"/>
 *                             &lt;element name="SchluesselzahlStornoeintrag" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
 *                             &lt;element name="SchluesselzahlBeitragsart" type="{http://www.zas.admin.ch/RC}SchluesselzahlBeitragsart_Type"/>
 *                             &lt;element name="Beitragsdauer">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Anfangsmonat">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *                                             &lt;maxInclusive value="99"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Endmonat">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *                                             &lt;maxInclusive value="99"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Beitragsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type"/>
 *                             &lt;element name="Einkommen" type="{http://www.zas.admin.ch/RC}BetragFR_Type"/>
 *                             &lt;element name="Verarbeitungsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StandIKStatistikNacher">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VorzeichenCode" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
 *                   &lt;element name="SummeEntschaedigungen" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ALVEntschaedigungenMeldung_Type", propOrder = { "kasseZweigstelleIKFuehrend", "verarbeitungsjahr",
        "aufzeichnungen", "standIKStatistikNacher" })
public class ALVEntschaedigungenMeldungType {

    @XmlElement(name = "KasseZweigstelleIKFuehrend", required = true)
    protected String kasseZweigstelleIKFuehrend;
    @XmlElement(name = "Verarbeitungsjahr", required = true)
    protected XMLGregorianCalendar verarbeitungsjahr;
    @XmlElement(name = "Aufzeichnungen")
    protected List<ALVEntschaedigungenMeldungType.Aufzeichnungen> aufzeichnungen;
    @XmlElement(name = "StandIKStatistikNacher", required = true)
    protected ALVEntschaedigungenMeldungType.StandIKStatistikNacher standIKStatistikNacher;

    /**
     * Gets the value of the kasseZweigstelleIKFuehrend property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getKasseZweigstelleIKFuehrend() {
        return kasseZweigstelleIKFuehrend;
    }

    /**
     * Sets the value of the kasseZweigstelleIKFuehrend property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKasseZweigstelleIKFuehrend(String value) {
        kasseZweigstelleIKFuehrend = value;
    }

    /**
     * Gets the value of the verarbeitungsjahr property.
     * 
     * @return
     *         possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getVerarbeitungsjahr() {
        return verarbeitungsjahr;
    }

    /**
     * Sets the value of the verarbeitungsjahr property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setVerarbeitungsjahr(XMLGregorianCalendar value) {
        verarbeitungsjahr = value;
    }

    /**
     * Gets the value of the aufzeichnungen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the aufzeichnungen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAufzeichnungen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ALVEntschaedigungenMeldungType.Aufzeichnungen }
     * 
     * 
     */
    public List<ALVEntschaedigungenMeldungType.Aufzeichnungen> getAufzeichnungen() {
        if (aufzeichnungen == null) {
            aufzeichnungen = new ArrayList<ALVEntschaedigungenMeldungType.Aufzeichnungen>();
        }
        return aufzeichnungen;
    }

    /**
     * Gets the value of the standIKStatistikNacher property.
     * 
     * @return
     *         possible object is {@link ALVEntschaedigungenMeldungType.StandIKStatistikNacher }
     * 
     */
    public ALVEntschaedigungenMeldungType.StandIKStatistikNacher getStandIKStatistikNacher() {
        return standIKStatistikNacher;
    }

    /**
     * Sets the value of the standIKStatistikNacher property.
     * 
     * @param value
     *            allowed object is {@link ALVEntschaedigungenMeldungType.StandIKStatistikNacher }
     * 
     */
    public void setStandIKStatistikNacher(ALVEntschaedigungenMeldungType.StandIKStatistikNacher value) {
        standIKStatistikNacher = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IKKopf">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13StellenOderUnbekannt_Type"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EintragungIKMeldung" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ListeFolgerecordNr" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FolgerecordNr" type="{http://www.zas.admin.ch/RC}FolgerecordNr_Type" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="AKAbrechnungsNr" type="{http://www.zas.admin.ch/RC}AKAbrechnungsNr_Type"/>
     *                   &lt;element name="SchluesselzahlStornoeintrag" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
     *                   &lt;element name="SchluesselzahlBeitragsart" type="{http://www.zas.admin.ch/RC}SchluesselzahlBeitragsart_Type"/>
     *                   &lt;element name="Beitragsdauer">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Anfangsmonat">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
     *                                   &lt;maxInclusive value="99"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Endmonat">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
     *                                   &lt;maxInclusive value="99"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Beitragsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type"/>
     *                   &lt;element name="Einkommen" type="{http://www.zas.admin.ch/RC}BetragFR_Type"/>
     *                   &lt;element name="Verarbeitungsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "ikKopf", "eintragungIKMeldung" })
    public static class Aufzeichnungen {

        @XmlElement(name = "IKKopf", required = true)
        protected ALVEntschaedigungenMeldungType.Aufzeichnungen.IKKopf ikKopf;
        @XmlElement(name = "EintragungIKMeldung", required = true)
        protected List<ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung> eintragungIKMeldung;

        /**
         * Gets the value of the ikKopf property.
         * 
         * @return
         *         possible object is {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.IKKopf }
         * 
         */
        public ALVEntschaedigungenMeldungType.Aufzeichnungen.IKKopf getIKKopf() {
            return ikKopf;
        }

        /**
         * Sets the value of the ikKopf property.
         * 
         * @param value
         *            allowed object is {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.IKKopf }
         * 
         */
        public void setIKKopf(ALVEntschaedigungenMeldungType.Aufzeichnungen.IKKopf value) {
            ikKopf = value;
        }

        /**
         * Gets the value of the eintragungIKMeldung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the eintragungIKMeldung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getEintragungIKMeldung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung }
         * 
         * 
         */
        public List<ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung> getEintragungIKMeldung() {
            if (eintragungIKMeldung == null) {
                eintragungIKMeldung = new ArrayList<ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung>();
            }
            return eintragungIKMeldung;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ListeFolgerecordNr" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FolgerecordNr" type="{http://www.zas.admin.ch/RC}FolgerecordNr_Type" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="AKAbrechnungsNr" type="{http://www.zas.admin.ch/RC}AKAbrechnungsNr_Type"/>
         *         &lt;element name="SchluesselzahlStornoeintrag" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
         *         &lt;element name="SchluesselzahlBeitragsart" type="{http://www.zas.admin.ch/RC}SchluesselzahlBeitragsart_Type"/>
         *         &lt;element name="Beitragsdauer">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Anfangsmonat">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
         *                         &lt;maxInclusive value="99"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Endmonat">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
         *                         &lt;maxInclusive value="99"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Beitragsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type"/>
         *         &lt;element name="Einkommen" type="{http://www.zas.admin.ch/RC}BetragFR_Type"/>
         *         &lt;element name="Verarbeitungsjahr" type="{http://www.zas.admin.ch/RC}AHVDatumJ_Type" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "listeFolgerecordNr", "akAbrechnungsNr", "schluesselzahlStornoeintrag",
                "schluesselzahlBeitragsart", "beitragsdauer", "beitragsjahr", "einkommen", "verarbeitungsjahr" })
        public static class EintragungIKMeldung {

            @XmlElement(name = "ListeFolgerecordNr")
            protected ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.ListeFolgerecordNr listeFolgerecordNr;
            @XmlElement(name = "AKAbrechnungsNr", required = true, nillable = true)
            protected String akAbrechnungsNr;
            @XmlElement(name = "SchluesselzahlStornoeintrag", required = true, type = Short.class, nillable = true)
            protected Short schluesselzahlStornoeintrag;
            @XmlElement(name = "SchluesselzahlBeitragsart", required = true, type = Short.class, nillable = true)
            protected Short schluesselzahlBeitragsart;
            @XmlElement(name = "Beitragsdauer", required = true)
            protected ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.Beitragsdauer beitragsdauer;
            @XmlElement(name = "Beitragsjahr", required = true)
            protected XMLGregorianCalendar beitragsjahr;
            @XmlElement(name = "Einkommen", required = true)
            protected BigDecimal einkommen;
            @XmlElement(name = "Verarbeitungsjahr")
            protected XMLGregorianCalendar verarbeitungsjahr;

            /**
             * Gets the value of the listeFolgerecordNr property.
             * 
             * @return
             *         possible object is
             *         {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.ListeFolgerecordNr }
             * 
             */
            public ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.ListeFolgerecordNr getListeFolgerecordNr() {
                return listeFolgerecordNr;
            }

            /**
             * Sets the value of the listeFolgerecordNr property.
             * 
             * @param value
             *            allowed object is
             *            {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.ListeFolgerecordNr }
             * 
             */
            public void setListeFolgerecordNr(
                    ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.ListeFolgerecordNr value) {
                listeFolgerecordNr = value;
            }

            /**
             * Gets the value of the akAbrechnungsNr property.
             * 
             * @return
             *         possible object is {@link String }
             * 
             */
            public String getAKAbrechnungsNr() {
                return akAbrechnungsNr;
            }

            /**
             * Sets the value of the akAbrechnungsNr property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setAKAbrechnungsNr(String value) {
                akAbrechnungsNr = value;
            }

            /**
             * Gets the value of the schluesselzahlStornoeintrag property.
             * 
             * @return
             *         possible object is {@link Short }
             * 
             */
            public Short getSchluesselzahlStornoeintrag() {
                return schluesselzahlStornoeintrag;
            }

            /**
             * Sets the value of the schluesselzahlStornoeintrag property.
             * 
             * @param value
             *            allowed object is {@link Short }
             * 
             */
            public void setSchluesselzahlStornoeintrag(Short value) {
                schluesselzahlStornoeintrag = value;
            }

            /**
             * Gets the value of the schluesselzahlBeitragsart property.
             * 
             * @return
             *         possible object is {@link Short }
             * 
             */
            public Short getSchluesselzahlBeitragsart() {
                return schluesselzahlBeitragsart;
            }

            /**
             * Sets the value of the schluesselzahlBeitragsart property.
             * 
             * @param value
             *            allowed object is {@link Short }
             * 
             */
            public void setSchluesselzahlBeitragsart(Short value) {
                schluesselzahlBeitragsart = value;
            }

            /**
             * Gets the value of the beitragsdauer property.
             * 
             * @return
             *         possible object is
             *         {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.Beitragsdauer }
             * 
             */
            public ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.Beitragsdauer getBeitragsdauer() {
                return beitragsdauer;
            }

            /**
             * Sets the value of the beitragsdauer property.
             * 
             * @param value
             *            allowed object is
             *            {@link ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.Beitragsdauer }
             * 
             */
            public void setBeitragsdauer(
                    ALVEntschaedigungenMeldungType.Aufzeichnungen.EintragungIKMeldung.Beitragsdauer value) {
                beitragsdauer = value;
            }

            /**
             * Gets the value of the beitragsjahr property.
             * 
             * @return
             *         possible object is {@link XMLGregorianCalendar }
             * 
             */
            public XMLGregorianCalendar getBeitragsjahr() {
                return beitragsjahr;
            }

            /**
             * Sets the value of the beitragsjahr property.
             * 
             * @param value
             *            allowed object is {@link XMLGregorianCalendar }
             * 
             */
            public void setBeitragsjahr(XMLGregorianCalendar value) {
                beitragsjahr = value;
            }

            /**
             * Gets the value of the einkommen property.
             * 
             * @return
             *         possible object is {@link BigDecimal }
             * 
             */
            public BigDecimal getEinkommen() {
                return einkommen;
            }

            /**
             * Sets the value of the einkommen property.
             * 
             * @param value
             *            allowed object is {@link BigDecimal }
             * 
             */
            public void setEinkommen(BigDecimal value) {
                einkommen = value;
            }

            /**
             * Gets the value of the verarbeitungsjahr property.
             * 
             * @return
             *         possible object is {@link XMLGregorianCalendar }
             * 
             */
            public XMLGregorianCalendar getVerarbeitungsjahr() {
                return verarbeitungsjahr;
            }

            /**
             * Sets the value of the verarbeitungsjahr property.
             * 
             * @param value
             *            allowed object is {@link XMLGregorianCalendar }
             * 
             */
            public void setVerarbeitungsjahr(XMLGregorianCalendar value) {
                verarbeitungsjahr = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * 
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Anfangsmonat">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
             *               &lt;maxInclusive value="99"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Endmonat">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
             *               &lt;maxInclusive value="99"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "anfangsmonat", "endmonat" })
            public static class Beitragsdauer {

                @XmlElement(name = "Anfangsmonat")
                protected short anfangsmonat;
                @XmlElement(name = "Endmonat")
                protected short endmonat;

                /**
                 * Gets the value of the anfangsmonat property.
                 * 
                 */
                public short getAnfangsmonat() {
                    return anfangsmonat;
                }

                /**
                 * Sets the value of the anfangsmonat property.
                 * 
                 */
                public void setAnfangsmonat(short value) {
                    anfangsmonat = value;
                }

                /**
                 * Gets the value of the endmonat property.
                 * 
                 */
                public short getEndmonat() {
                    return endmonat;
                }

                /**
                 * Sets the value of the endmonat property.
                 * 
                 */
                public void setEndmonat(short value) {
                    endmonat = value;
                }

            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * 
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FolgerecordNr" type="{http://www.zas.admin.ch/RC}FolgerecordNr_Type" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "folgerecordNr" })
            public static class ListeFolgerecordNr {

                @XmlElement(name = "FolgerecordNr", required = true, nillable = true)
                protected List<Integer> folgerecordNr;

                /**
                 * Gets the value of the folgerecordNr property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification
                 * you make to the returned list will be present inside the JAXB object. This is why there is not a
                 * <CODE>set</CODE> method for the folgerecordNr property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * 
                 * <pre>
                 * getFolgerecordNr().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list {@link Integer }
                 * 
                 * 
                 */
                public List<Integer> getFolgerecordNr() {
                    if (folgerecordNr == null) {
                        folgerecordNr = new ArrayList<Integer>();
                    }
                    return folgerecordNr;
                }

            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13StellenOderUnbekannt_Type"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "versichertennummer" })
        public static class IKKopf {

            @XmlList
            @XmlElement(name = "Versichertennummer", required = true)
            protected List<String> versichertennummer;

            /**
             * Gets the value of the versichertennummer property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the versichertennummer property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getVersichertennummer().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getVersichertennummer() {
                if (versichertennummer == null) {
                    versichertennummer = new ArrayList<String>();
                }
                return versichertennummer;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VorzeichenCode" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
     *         &lt;element name="SummeEntschaedigungen" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "vorzeichenCode", "summeEntschaedigungen" })
    public static class StandIKStatistikNacher {

        @XmlElement(name = "VorzeichenCode")
        protected short vorzeichenCode;
        @XmlElement(name = "SummeEntschaedigungen", required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger summeEntschaedigungen;

        /**
         * Gets the value of the vorzeichenCode property.
         * 
         */
        public short getVorzeichenCode() {
            return vorzeichenCode;
        }

        /**
         * Sets the value of the vorzeichenCode property.
         * 
         */
        public void setVorzeichenCode(short value) {
            vorzeichenCode = value;
        }

        /**
         * Gets the value of the summeEntschaedigungen property.
         * 
         * @return
         *         possible object is {@link BigInteger }
         * 
         */
        public BigInteger getSummeEntschaedigungen() {
            return summeEntschaedigungen;
        }

        /**
         * Sets the value of the summeEntschaedigungen property.
         * 
         * @param value
         *            allowed object is {@link BigInteger }
         * 
         */
        public void setSummeEntschaedigungen(BigInteger value) {
            summeEntschaedigungen = value;
        }

    }

}
