package ch.globaz.perseus.business.constantes.document;

public enum DocumentTypes {
    OCTROI_AJOUT_AIDES_CATEGORIELLES,
    OCTROI_ANNONCE_CHANGEMENT,
    OCTROI_HORS_RI,
    OCTROI_PARTIEL,
    OCTROI_PARTIEL_MODIF_ECONOMIQUE,
    OCTROI_RI_AVEC_PROJET,
    OCTROI_RI_SANS_PROJET,
    PROJET,
    REFUS,
    RENONCIATION,
    SUPPRESSION,
    SUPPRESSION_VOLONTAIRE,
    NON_ENTREE_MATIERE
}
