package ch.globaz.exceptions;

public enum ExceptionMessage {

    ERREUR_INCONNUE("ERREUR_INCONNUE"),
    ERREUR_TECHNIQUE("ERREUR_TECHNIQUE"),
    TRAVAILLEUR_DEJA_EXISTANT("TRAVAILLEUR_DEJA_EXISTANT"),
    TRAVAILLEUR_CREATION_IMPOSSIBLE_SANS_TIERS("TRAVAILLEUR_CREATION_IMPOSSIBLE_SANS_TIERS"),
    TRAVAILLEUR_SUPPRESSION_IMPOSSIBLE_CAR_LIE_A_POSTE_TRAVAIL(
            "TRAVAILLEUR_SUPPRESSION_IMPOSSIBLE_CAR_LIE_A_POSTE_TRAVAIL"),
    NUM_REFERENCE_TROP_LONG("NUM_REFERENCE_TROP_LONG"),
    INVALID_VALUE_CODE_SYSTEME("INVALID_VALUE_CODE_SYSTEME"),
    UNKNOWN_VALUE_CODE_SYSTEME("UNKNOWN_VALUE_CODE_SYSTEME"),
    DECOMPTE_ERREUR_PARAMETRAGE_AC2("DECOMPTE_ERREUR_PARAMETRAGE_AC2"),
    PARAMETRE_SYNDICAT_INVALIDE_POUR_ANNEE("PARAMETRE_SYNDICAT_INVALIDE_POUR_ANNEE");

    private String message;

    private ExceptionMessage(final String message) {
        this.message = message;
    }

    @Override
    public String toString() {
        return message;
    }
}
