//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.07 at 01:02:49 PM CET
//

package ch.globaz.perseus.businessimpl.services.impotsource.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DecompteContribuableType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecompteContribuableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identite" type="{http://www.vd.ch/fiscalite/impotsource/liste-impot-source/4}IdentiteType"/>
 *         &lt;element name="salaire" type="{http://www.vd.ch/fiscalite/impotsource/liste-impot-source/4}SalaireType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="noSequenceDecompte" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecompteContribuableType", propOrder = { "identite", "salaire" })
public class DecompteContribuableType {

    @XmlElement(required = true)
    protected IdentiteType identite;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger noSequenceDecompte;
    @XmlElement(required = true)
    protected List<SalaireType> salaire;

    /**
     * Gets the value of the identite property.
     * 
     * @return possible object is {@link IdentiteType }
     * 
     */
    public IdentiteType getIdentite() {
        return identite;
    }

    /**
     * Gets the value of the noSequenceDecompte property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNoSequenceDecompte() {
        return noSequenceDecompte;
    }

    /**
     * Gets the value of the salaire property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the salaire property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSalaire().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SalaireType }
     * 
     * 
     */
    public List<SalaireType> getSalaire() {
        if (salaire == null) {
            salaire = new ArrayList<SalaireType>();
        }
        return salaire;
    }

    /**
     * Sets the value of the identite property.
     * 
     * @param value
     *            allowed object is {@link IdentiteType }
     * 
     */
    public void setIdentite(IdentiteType value) {
        identite = value;
    }

    /**
     * Sets the value of the noSequenceDecompte property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setNoSequenceDecompte(BigInteger value) {
        noSequenceDecompte = value;
    }

}
