//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.03.22 at 02:10:43 PM CET
//

package ch.globaz.perseus.businessimpl.services.impotsource.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="typeListe" type="{http://www.vd.ch/fiscalite/impotsource/liste-impot-source/4}TypeListType"/>
 *         &lt;element name="numDebiteur" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="montantBrut" type="{http://www.vd.ch/fiscalite/impotsource/liste-impot-source/4}DecimalFractionTwoDigits"/>
 *         &lt;element name="montantCommission" type="{http://www.vd.ch/fiscalite/impotsource/liste-impot-source/4}PositiveDecimalFractionTwoDigits"/>
 *         &lt;element name="decompteContribuable" type="{http://www.vd.ch/fiscalite/impotsource/liste-impot-source/4}DecompteContribuableType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="debutPeriodeDeclaration" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="finPeriodeDeclaration" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "typeListe", "numDebiteur", "montantBrut", "montantCommission",
        "decompteContribuable" })
@XmlRootElement(name = "listeImpotSource")
public class ListeImpotSource {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar debutPeriodeDeclaration;
    protected List<DecompteContribuableType> decompteContribuable;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar finPeriodeDeclaration;
    @XmlElement(required = true)
    protected BigDecimal montantBrut;
    @XmlElement(required = true)
    protected BigDecimal montantCommission;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numDebiteur;
    @XmlElement(required = true)
    protected TypeListType typeListe;

    /**
     * Gets the value of the debutPeriodeDeclaration property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDebutPeriodeDeclaration() {
        return debutPeriodeDeclaration;
    }

    /**
     * Gets the value of the decompteContribuable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the decompteContribuable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDecompteContribuable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DecompteContribuableType }
     * 
     * 
     */
    public List<DecompteContribuableType> getDecompteContribuable() {
        if (decompteContribuable == null) {
            decompteContribuable = new ArrayList<DecompteContribuableType>();
        }
        return decompteContribuable;
    }

    /**
     * Gets the value of the finPeriodeDeclaration property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getFinPeriodeDeclaration() {
        return finPeriodeDeclaration;
    }

    /**
     * Gets the value of the montantBrut property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMontantBrut() {
        return montantBrut;
    }

    /**
     * Gets the value of the montantCommission property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMontantCommission() {
        return montantCommission;
    }

    /**
     * Gets the value of the numDebiteur property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumDebiteur() {
        return numDebiteur;
    }

    /**
     * Gets the value of the typeListe property.
     * 
     * @return possible object is {@link TypeListType }
     * 
     */
    public TypeListType getTypeListe() {
        return typeListe;
    }

    /**
     * Sets the value of the debutPeriodeDeclaration property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDebutPeriodeDeclaration(XMLGregorianCalendar value) {
        debutPeriodeDeclaration = value;
    }

    /**
     * Sets the value of the finPeriodeDeclaration property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setFinPeriodeDeclaration(XMLGregorianCalendar value) {
        finPeriodeDeclaration = value;
    }

    /**
     * Sets the value of the montantBrut property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMontantBrut(BigDecimal value) {
        montantBrut = value;
    }

    /**
     * Sets the value of the montantCommission property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMontantCommission(BigDecimal value) {
        montantCommission = value;
    }

    /**
     * Sets the value of the numDebiteur property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setNumDebiteur(BigInteger value) {
        numDebiteur = value;
    }

    /**
     * Sets the value of the typeListe property.
     * 
     * @param value
     *            allowed object is {@link TypeListType }
     * 
     */
    public void setTypeListe(TypeListType value) {
        typeListe = value;
    }

}
