include:
  - project: 'ci-cd/product-currents-gitlab-ci'
    ref: master
    file: '/mvn-gitlab-ci.yml'

build-maven:
  before_script:
    - echo $JAVA_OPTS
    - export JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=Cp1252 -Dsun.jnu.encoding=ISO-8859-1 -Duser.timezone=Europe/Zurich -Duser.country=CH"
    - echo $JAVA_OPTS
    - echo $MAVEN_OPTS
    - export MAVEN_OPTS="$MAVEN_OPTS -Dfile.encoding=Cp1252 -Dsun.jnu.encoding=ISO-8859-1 -Duser.timezone=Europe/Zurich -Duser.country=CH -e"
    - mvn -v -e
