---------------------------------------------------------------
-----   AL.SQL
---------------------------------------------------------------
-- S220616_004 RaFam 4 nouvelles plausibilités
INSERT INTO SCHEMA.FWCOSP (PCOSID, PPTYGR, PCONCS, PPTYCN, PPTYCL, PPTYSA, PCOSLI, PCOSDF, PCOSDM, PCOSDP, PCOIAN, PCOIDE, PCODFI, PCOITC, PCOISE, PSPY) VALUES (61360215, 'ALRAFAMCOE', 1, 1, 0, 0, 'Allocation différentielle annoncée sur une période chevauchant une allocation de base chômage', 2, 1, 2, 2, 2, 2, 60360000, 0, to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOSP (PCOSID, PPTYGR, PCONCS, PPTYCN, PPTYCL, PPTYSA, PCOSLI, PCOSDF, PCOSDM, PCOSDP, PCOIAN, PCOIDE, PCODFI, PCOITC, PCOISE, PSPY) VALUES (61360216, 'ALRAFAMCOE', 1, 1, 0, 0, 'Allocation enfant annoncée sur une période chevauchant une allocation différentielle', 2, 1, 2, 2, 2, 2, 60360000, 0, to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOSP (PCOSID, PPTYGR, PCONCS, PPTYCN, PPTYCL, PPTYSA, PCOSLI, PCOSDF, PCOSDM, PCOSDP, PCOIAN, PCOIDE, PCODFI, PCOITC, PCOISE, PSPY) VALUES (61360217, 'ALRAFAMCOE', 1, 1, 0, 0, 'Allocation formation annoncée sur une période chevauchant une allocation différentielle', 2, 1, 2, 2, 2, 2, 60360000, 0, to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOSP (PCOSID, PPTYGR, PCONCS, PPTYCN, PPTYCL, PPTYSA, PCOSLI, PCOSDF, PCOSDM, PCOSDP, PCOIAN, PCOIDE, PCODFI, PCOITC, PCOISE, PSPY) VALUES (61360218, 'ALRAFAMCOE', 1, 1, 0, 0, 'Allocation formation anticipée annoncée sur une période chevauchant une allocation différentielle', 2, 1, 2, 2, 2, 2, 60360000, 0, to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');

INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360215, 'D', '215       ', 'Allocation différentielle annoncée sur une période chevauchant une allocation de base chômage', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360215, 'F', '215       ', 'Allocation différentielle annoncée sur une période chevauchant une allocation de base chômage', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360216, 'D', '216       ', 'Allocation enfant annoncée sur une période chevauchant une allocation différentielle', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360216, 'F', '216       ', 'Allocation enfant annoncée sur une période chevauchant une allocation différentielle', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360217, 'D', '217       ', 'Allocation formation annoncée sur une période chevauchant une allocation différentielle', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360217, 'F', '217       ', 'Allocation formation annoncée sur une période chevauchant une allocation différentielle', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360218, 'D', '218       ', 'Allocation formation anticipée annoncée sur une période chevauchant une allocation différentielle', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (61360218, 'F', '218       ', 'Allocation formation anticipée annoncée sur une période chevauchant une allocation différentielle', to_char(current timestamp, 'YYYYMMDDHH24MISS') concat 'globaz');