-- S200417_007 - Pandémie-APG - Attestations fiscales : Mise à jour des catalogues de texte
-- Pandemie
INSERT INTO SCHEMA.CTDOCUME (CBIDOC, CBLNOM, CBBACT, CBBDEF, CBDDES, CBTEDI, CBTDES, CBITYD, PSPY, CBBSTY)
SELECT '84200000001',
       'attestation_pandemie',
	   CBBACT, CBBDEF, CBDDES, CBTEDI, CBTDES, CBITYD, '20201001120000globaz   ', CBBSTY
from SCHEMA.CTDOCUME
         INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
where CATDOM = 52018001
  and CATTYP = 52019007
  and CBBACT = 1
  and CBBDEF = 1
  and CBLNOM = 'normal';


INSERT INTO SCHEMA.CTELEMEN (CCIELE, CCIDOC, CCNPOS, CCNNIV, PSPY, CCBSBD, CCBDES, CCBSEL, CCBEDI)
SELECT CONCAT('84200000000', RIGHT(CCIELE, 3)),
       (select CBIDOC
        FROM SCHEMA.CTDOCUME
                 INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
        WHERE CATDOM = 52018001
          AND CATTYP = 52019007
          and CBBACT = 1
          and CBBDEF = 1
          and CBLNOM = 'attestation_pandemie'),
       CCNPOS,CCNNIV, '20201001120000globaz', CCBSBD, CCBDES, CCBSEL, CCBEDI
FROM SCHEMA.CTELEMEN
WHERE CCIDOC = (select CBIDOC
                FROM SCHEMA.CTDOCUME
                         INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
                WHERE CATDOM = 52018001
                  AND CATTYP = 52019007
                  and CBBACT = 1
                  and CBBDEF = 1
                  and CBLNOM = 'normal');


INSERT INTO SCHEMA.CTTEXTES(CDITXT, CDLDES, CDLCIL, CDIELE, PSPY)
SELECT CONCAT('84200000000', RIGHT(CDITXT, 3)),
       CDLDES, CDLCIL,
       CONCAT('84200000000', RIGHT(CDIELE, 3)),
       '20201001120000globaz   '
from SCHEMA.CTTEXTES
         INNER JOIN SCHEMA.CTELEMEN ON CDIELE = CCIELE
WHERE CCIDOC = (select CBIDOC
                FROM SCHEMA.CTDOCUME
                         INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
                WHERE CATDOM = 52018001
                  AND CATTYP = 52019007
                  and CBBACT = 1
                  and CBBDEF = 1
                  and CBLNOM = 'normal');

-- Maternite
INSERT INTO SCHEMA.CTTYPDOC (CAITYD, CATDOM, CATTYP, PSPY, CANBIN, CAIGAN) VALUES (500, 52020001, 52021007, '                        ', 84300000000, null);

INSERT INTO SCHEMA.CTDOCUME (CBIDOC, CBLNOM, CBBACT, CBBDEF, CBDDES, CBTEDI, CBTDES, CBITYD, PSPY, CBBSTY)
SELECT '84300000001',
       'normal',
	   CBBACT, CBBDEF, CBDDES, CBTEDI, CBTDES, '500', '20201001120000globaz   ', CBBSTY
from SCHEMA.CTDOCUME
         INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
where CATDOM = 52018001
  and CATTYP = 52019007
  and CBBACT = 1
  and CBBDEF = 1
  and CBLNOM = 'normal';

INSERT INTO SCHEMA.CTELEMEN (CCIELE, CCIDOC, CCNPOS, CCNNIV, PSPY, CCBSBD, CCBDES, CCBSEL, CCBEDI)
SELECT CONCAT('84300000000' ,RIGHT(CCIELE, 3)),
       '84300000001',
       CCNPOS,CCNNIV, '20201001120000globaz', CCBSBD, CCBDES, CCBSEL, CCBEDI
FROM SCHEMA.CTELEMEN
WHERE CCIDOC = (select CBIDOC
                FROM SCHEMA.CTDOCUME
                         INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
                WHERE CATDOM = 52018001
                  AND CATTYP = 52019007
                  and CBBACT = 1
                  and CBBDEF = 1
                  and CBLNOM = 'normal');

INSERT INTO SCHEMA.CTTEXTES(CDITXT, CDLDES, CDLCIL, CDIELE, PSPY)
SELECT CONCAT('84300000000', RIGHT(CDITXT, 3)),
       CDLDES, CDLCIL,
       CONCAT('84300000000', RIGHT(CDIELE, 3)),
       '20201001120000globaz   '
from SCHEMA.CTTEXTES
         INNER JOIN SCHEMA.CTELEMEN ON CDIELE = CCIELE
WHERE CCIDOC = (select CBIDOC
                FROM SCHEMA.CTDOCUME
                         INNER JOIN SCHEMA.CTTYPDOC ON CBITYD = CAITYD
                WHERE CATDOM = 52018001
                  AND CATTYP = 52019007
                  and CBBACT = 1
                  and CBBDEF = 1
                  and CBLNOM = 'normal');

INSERT INTO SCHEMA.FWINCP (PINCID, PCOSID, PINCAN, PINCLI, PINCVA, PSPY) VALUES ('CTDOCUME', 52021007, 0, '', 1, '20201001080000globaz');
INSERT INTO SCHEMA.FWINCP (PINCID, PCOSID, PINCAN, PINCLI, PINCVA, PSPY) VALUES ('CTELEMEN', 52021007, 0, '', 16, '20201001080000globaz');
INSERT INTO SCHEMA.FWINCP (PINCID, PCOSID, PINCAN, PINCLI, PINCVA, PSPY) VALUES ('CTTEXTES', 52021007, 0, '', 48, '20201001080000globaz');