--D0013
UPDATE SCHEMA.FWCOUP SET PCOLUT='Hinterlassenenrente dauert fort' WHERE PCOSID=52801004 AND PLAIDE='D';
UPDATE SCHEMA.FWCOUP SET PCOLUT='Rente de survivant perdure' WHERE PCOSID=52801004 AND PLAIDE='F';
UPDATE SCHEMA.FWCOUP SET PCOLUT='rendita per superstiti perdura' WHERE PCOSID=52801004 AND PLAIDE='I';