CREATE TABLE SCHEMA.REDNRAJ
(
   DNRAID NUMERIC(15,0) PRIMARY KEY NOT NULL,
   DNRANOM VARCHAR(50),
   DNRANBMUT NUMERIC(10,0),
   PSPY VARCHAR(24) NOT NULL
);

INSERT INTO SCHEMA.JADEPROP (PROPNAME,PROPVAL) VALUES ('corvus.dnra.process.emails','');