/* Corrections d'internationalisation pour la CCVS (I170313_009): */
ALTER TABLE SCHEMA.LYECHEAN ADD WMLDESF VARCHAR (40);
ALTER TABLE SCHEMA.LYECHEAN ADD WMLDESD VARCHAR (40);
ALTER TABLE SCHEMA.LYECHEAN ADD WMLDESI VARCHAR (40);
UPDATE SCHEMA.LYECHEAN SET WMLDESF = WMLDES;
UPDATE SCHEMA.LYECHEAN SET WMLDESI = CONCAT('[it]', WMLDES);
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Fälligkeitsliste IV-TG 18 - 25 Jahre' WHERE WMIECH = 1 AND WMTDAP = 52500002;
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Liste der Beschlüsse von mehr als 2 Jahren' WHERE WMIECH = 2 AND WMTDAP = 52500002;
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Fallrevision' WHERE WMIECH = 3 AND WMTDAP = 52500002;
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Renten-Herabsetzung 25 Jahre' WHERE WMIECH = 5 AND WMTDAP = 52500003;
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Liste der überfälligen Arbeiten' WHERE WMIECH = 7 AND WMTDAP = 52500003;
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Herabsetzung Kinderrenten' WHERE WMIECH = 8 AND WMTDAP = 52500003;
UPDATE SCHEMA.LYECHEAN SET WMLDESD = 'Liste der auszuführenden Arbeiten' WHERE WMIECH = 10 AND WMTDAP = 52500003;