INSERT INTO SCHEMA.FAMODUP (IDMODFAC,LIBELLEFR,LIBELLEDE,LIBELLEIT,NOMCLASSE,IDTYPEMODULE,NIVEAUAPPEL,MODIFIERAFACT,PSPY)
VALUES ((SELECT COALESCE(MAX(IDMODFAC),0) FROM SCHEMA.FAMODUP) + 1,'Impression de factures eBill','[de]Impression de factures eBill','[it]Impression de factures eBill','globaz.musca.api.musca.FAImpressionFactureEBill',905027,7,2,'20210212120000Globaz');

INSERT INTO SCHEMA.FAMODUP (IDMODFAC,LIBELLEFR,LIBELLEDE,LIBELLEIT,NOMCLASSE,IDTYPEMODULE,NIVEAUAPPEL,MODIFIERAFACT,PSPY)
VALUES ((SELECT COALESCE(MAX(IDMODFAC),0) FROM SCHEMA.FAMODUP) + 1,'Bulletins de solde eBill','[de]Saldo ESR eBill','[it]Soldes BVR eBill','globaz.musca.api.musca.FASolde_EBill',905046,150,2,'20210312120000Globaz');

INSERT INTO SCHEMA.FAMODUP (IDMODFAC,LIBELLEFR,LIBELLEDE,LIBELLEIT,NOMCLASSE,IDTYPEMODULE,NIVEAUAPPEL,MODIFIERAFACT,PSPY)
VALUES ((SELECT COALESCE(MAX(IDMODFAC),0) FROM SCHEMA.FAMODUP) + 1,'Impression facture Sans LSV / Remb eBill','[de]Impression facture Sans LSV / Remb eBill','[it]Impression facture Sans LSV / Remb eBill','globaz.musca.api.musca.FAImpressionFactureSansLSVRembEBill',905027,7,2,'20210312120000Globaz');

UPDATE SCHEMA.FWINCP SET PINCVA=(SELECT COALESCE(MAX(IDMODFAC),0) FROM SCHEMA.FAMODUP), PSPY='20210212120000ccjuglo' WHERE PINCID='FAMODUP';

ALTER TABLE SCHEMA.FAENTFP
    ADD COLUMN EBILLTRANSACTIONID VARCHAR(50);

REORG TABLE SCHEMA.FAENTFP;

-- S200701_007 e-Bill: Nouveau type de module de facturation pour bulletin de soldes eBill
INSERT INTO SCHEMA.FWCOSP (PCOSID, PPTYGR, PCONCS, PPTYCN, PPTYCL, PPTYSA, PCOSLI, PCOSDF, PCOSDM, PCOSDP, PCOIAN, PCOIDE, PCODFI, PCOITC, PCOISE, PSPY) VALUES (905046, 'MUTYPMODUL', 1, 1, 0, 0, 'Module_Bulletin_De_Soldes_EBill', 2, 1, 2, 2, 2, 2, 10900005, 0, '20210701120000Globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (905046, 'D', '', 'Bulletin de Soldes EBill', '20210701120000Globaz');
INSERT INTO SCHEMA.FWCOUP (PCOSID, PLAIDE, PCOUID, PCOLUT, PSPY) VALUES (905046, 'F', '', 'Bulletin de Soldes EBill', '20210701120000Globaz');