--D0222 - S170621_002 - EBU - Confirmation exactitude déclaration
ALTER TABLE SCHEMA.EBPUCS_FILE ADD COLUMN CERTIFIE_EXACT DECIMAL(1,0)
ALTER TABLE SCHEMA.EBPUCS_FILE ADD COLUMN DATE_VALIDATION DECIMAL(12,0);
ALTER TABLE SCHEMA.EBPUCS_FILE ADD COLUMN NOM_VALIDATION VARCHAR(255);