--FERCIAM  S181016_002 Ajout mode de transfert organes exécutions

INSERT INTO SCHEMA.FWCOSP (PCOSID,PPTYGR,PCONCS,PPTYCN,PPTYCL,PPTYSA,PCOSLI,PCOSDF,PCOSDM,PCOSDP,PCOIAN,PCOIDE,PCODFI,PCOITC,PCOISE,PSPY) VALUES (246003,'OSIMODTRA ',1,2,0,0,'TRANSFERT_PAR_REPERTOIRE',2,2,2,2,2,2,10200046,0,'                        ');
INSERT INTO SCHEMA.FWCOUP (PCOSID,PLAIDE,PCOUID,PCOLUT,PSPY) VALUES (246003,'D','REP       ','?Transfert dans un répertoire','                        ');
INSERT INTO SCHEMA.FWCOUP (PCOSID,PLAIDE,PCOUID,PCOLUT,PSPY) VALUES (246003,'F','REP       ','Transfert dans un répertoire','                        ');
INSERT INTO SCHEMA.FWCOUP (PCOSID,PLAIDE,PCOUID,PCOLUT,PSPY) VALUES (246003,'I','REP       ','?Transfert dans un répertoire','                        ');

INSERT INTO SCHEMA.JADEPROP (PROPNAME,PROPVAL,CSPY,PSPY) VALUES ('osiris.DossierRacineOrganeExe','/job/jobadm1/','20190329120000Globaz    ','20180101120000Globaz    ');

ALTER TABLE SCHEMA.CAOREXP ADD COLUMN NOMREPERTOIRE VARCHAR(255);
REORG table SCHEMA.CAOREXP;

