-- Modification de la taille du numéro de poursuite dans CASection
ALTER TABLE SCHEMA.CASECTP
ALTER COLUMN NOPOURSUITE SET DATA TYPE CHAR(20);

reorg Table SCHEMA.CASECTP;

ALTER TABLE SCHEMA.COHISTP
ALTER COLUMN OELNPO SET DATA TYPE VARCHAR(20);

reorg Table SCHEMA.COHISTP;
