--WEBAVS-2627
INSERT INTO SCHEMA.JADEPROP (PROPNAME,PROPVAL) VALUES ('pavo.activerParsingPUCS4','true');
INSERT INTO SCHEMA.FWDDOC (IDDOC,IDCONF,NUMREF,DESCFR,DESCDE,DESCIT,DOCTYP,PSPY,OUTXML,OUTPDF) VALUES (328,1,'0319CCI','Protocole Excel d''importation d''une DS électronique',null,null,null,'20160816000000MMO','2','1');