-- ****************************************************
-- ***************   CREATE TABLES WEBMETIER ************
-- ****************************************************

--  Create Tables 
CREATE TABLE SCHEMA.PT_ABSENCES ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_DECOMPTE_LIGNES DECIMAL(9) NOT NULL,
	CS_TYPE DECIMAL(8),
	DATE DECIMAL(8),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);

CREATE TABLE SCHEMA.PT_ADHESIONS_COTIS_POSTES ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_POSTES_TRAVAILS DECIMAL(9) NOT NULL,
	ID_AFCOTIP DECIMAL(15) NOT NULL,
	DATE_DEBUT DECIMAL(8) NOT NULL,
	DATE_FIN DECIMAL(8),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_CONV_QUALIFICATIONS ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_TIADMIP_CONVENTION DECIMAL(15) NOT NULL,
	CS_QUALIFICATION DECIMAL(8) NOT NULL,
	CS_PERSONNEL DECIMAL(8) NOT NULL,
	CS_OUVRIER_EMPLOYEUR DECIMAL(8) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);

CREATE TABLE SCHEMA.PT_COTISATION_DECOMPTES ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_DECOMPTE_LIGNES DECIMAL(8),
	ID_AFCOTIP DECIMAL(8) NOT NULL,
	MASSE DECIMAL(15,2) NOT NULL,
	MASSE_FORCEE DECIMAL(1),
	TAUX DECIMAL(8,5) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);

CREATE TABLE SCHEMA.PT_DECOMPTE_LIGNES ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_DECOMPTES DECIMAL(9) NOT NULL,
	ID_PT_POSTES_TRAVAIL DECIMAL(9) NOT NULL,
	NOMBRE_HEURES DECIMAL(7,2),
	SALAIRE_HORAIRE DECIMAL(15,2),
	SALAIRE_TOTAL DECIMAL(15,2),
	TAUX_CONTRIBUABLE DECIMAL(8,5),
	MONTANT_FRANCHISE DECIMAL(15,2),
	PERIODE_DEBUT NUMERIC(8,0),
	PERIODE_FIN NUMERIC(8,0),
	DATE_ANNONCE char(24),
	DATE_ANNONCE_LPP DECIMAL(8),
	SEQUENCE SMALLINT,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);



CREATE TABLE SCHEMA.PT_DECOMPTES ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_EMPLOYEURS DECIMAL(9) NOT NULL,
	ID_PASSAGE_FACTURATION INTEGER,
	ID_CECONTP DECIMAL(9),
	CS_INTERETS DECIMAL(9),
	NUMERO_DECOMPTE VARCHAR(20),
	DESCRIPTION VARCHAR(100),
	DATE_ETABLISSEMENT DECIMAL(8),
	DATE_RECEPTION DECIMAL(8),
	DATE_RAPPEL DECIMAL(9),
	MONTANT_CONTROLE DECIMAL(15,2),
	PERIODE_DEBUT DECIMAL(6),
	PERIODE_FIN DECIMAL(6),
	CS_TYPE DECIMAL(8),
	CS_ETAT DECIMAL(8),
	REMARQUE_RECTIFICATION VARCHAR(5000),
	MANUEL NUMERIC(1,0),
	RECTIFIE DECIMAL(1),
	CS_MOTIF_PROLONGATION DECIMAL(8),
	CONTROLEAC2 DECIMAL(1),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);

CREATE TABLE SCHEMA.PT_EMPLOYEURS ( 
	ID_AFAFFIP DECIMAL(15) NOT NULL PRIMARY KEY,
	BVR DECIMAL(1) DEFAULT 2 NOT NULL,
	CS_TYPE_FACTURATION NUMERIC(9) NOT NULL,
	EDITER_SANS_TRAV DECIMAL(1),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_HISTORIQUE_DECOMPTES ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_DECOMPTES DECIMAL(9) NOT NULL,
	DATE DECIMAL(8) NOT NULL,
	HEURE DECIMAL(6) NOT NULL,
	CS_ETAT DECIMAL(8) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_POSTES_TRAVAILS ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_TRAVAILLEURS DECIMAL(9) NOT NULL,
	ID_AFAFFIP DECIMAL(15) NOT NULL,
	DATE_DEBUT_ACTIVITE DECIMAL(8) NOT NULL,
	DATE_FIN_ACTIVITE DECIMAL(8),
	CS_QUALIFICATION DECIMAL(8) NOT NULL,
	CS_ETAT_POSTE DECIMAL(8) NOT NULL,
	CS_GENRE_SALAIRE DECIMAL(8),
	POSTE_FRANCHISE_AVS DECIMAL(1) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);
COMMENT ON COLUMN SCHEMA.PT_POSTES_TRAVAILS.ID_AFAFFIP IS 'idEmployeur';

CREATE TABLE SCHEMA.PT_TAUX_OCCUPATIONS ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_PT_POSTES_TRAVAILS DECIMAL(9) NOT NULL,
	DATE_VALIDITE DECIMAL(8) NOT NULL,
	TAUX DECIMAL(8,5) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_TRAVAILLEURS ( 
	ID DECIMAL(9) NOT NULL PRIMARY KEY,
	ID_TITIERP DECIMAL(15) NOT NULL,
	CS_GENRE_PERMIS_TRAVAIL DECIMAL(8) NOT NULL,
	REFERENCE_PERMIS VARCHAR(11),
	ANNONCE_MEROBA DECIMAL(1) NOT NULL,
	DATE_ANNONCE_MEROBA DECIMAL(8),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);

CREATE TABLE SCHEMA.PT_LIGNES_TAXATIONS ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_PT_TAXATIONS_OFFICE DECIMAL(15) NOT NULL,
	ID_AFCOTIP DECIMAL(15) NOT NULL,
	MASSE DECIMAL(15,2) NOT NULL,
	TAUX DECIMAL(8,5) NOT NULL,
	MONTANT DECIMAL(15,2) NOT NULL,
	CSPY VARCHAR(24) NOT NULL,
	PSPY VARCHAR(24) NOT NULL
);

CREATE TABLE SCHEMA.PT_TAXATIONS_OFFICE ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_PT_DECOMPTES DECIMAL(15) NOT NULL,
	ID_FAPASSP DECIMAL(15),
	CS_ETAT DECIMAL(9) NOT NULL,
	CSPY VARCHAR(24) NOT NULL,
	PSPY VARCHAR(24) NOT NULL
);

CREATE TABLE SCHEMA.PT_ABSENCES_JUSTIFIEES (
	ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
	ID_FAPASSP NUMERIC(15,0),
	ID_PT_POSTES_TRAVAILS NUMERIC(15,0),
	CS_ETAT NUMERIC(15,0),
	CS_TYPE NUMERIC(15,0),
	DATE_DEBUT_ABSENCE NUMERIC(8,0),
	DATE_FIN_ABSENCE NUMERIC(8,0),
	MONTANT_BRUT NUMERIC(15,2),
	MONTANT_VERSE NUMERIC(15,2),
	TAUX_AVS NUMERIC(8,5),
	TAUX_AC NUMERIC(8,5),
	NB_JOURS NUMERIC(5,2),
	NB_HEURES_PAR_JOUR NUMERIC(5,2),
	CS_BENEFICIAIRE NUMERIC(15,0),
	CS_LIEN_PARENTE NUMERIC(15,0),
	SALAIRE_HORAIRE DECIMAL(15,2),
	PSPY VARCHAR(24) NOT NULL, 
	CSPY VARCHAR(24) NOT NULL
);
COMMENT ON TABLE SCHEMA.PT_ABSENCES_JUSTIFIEES is '';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.ID is 'Id de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.CS_ETAT is 'état de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.CS_TYPE is 'type d''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.DATE_DEBUT_ABSENCE is 'date du début de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.DATE_FIN_ABSENCE is 'date de fin de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.MONTANT_BRUT is 'montant brut de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.MONTANT_VERSE is 'montant versé de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.ID_PT_POSTES_TRAVAILS is 'id posteTravail';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.TAUX_AVS is 'taux AVS';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.TAUX_AC is 'taux AC';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.NB_JOURS is 'nombre de jours de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.NB_HEURES_PAR_JOUR is 'nombre d''heures effectuées par jour pour ce poste';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.ID_FAPASSP is 'id du passage facturation';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.CS_BENEFICIAIRE is 'bénéficiaire de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.CS_LIEN_PARENTE is 'lien de parenté pour l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.SALAIRE_HORAIRE is 'salaire horaire pour l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.PSPY is 'spy - Champ espion, défini quand et qui a effectué la dernière modification de l''entité';
COMMENT ON COLUMN SCHEMA.PT_ABSENCES_JUSTIFIEES.CSPY is 'spy - Champ espion, défini quand et qui a créé l''entité';


CREATE TABLE SCHEMA.PT_COMPTEURS (
	ID  NUMERIC(15,0)  NOT NULL PRIMARY KEY, 
	ID_PT_POSTES_TRAVAILS  NUMERIC(15,0)  , 
	ANNEE  NUMERIC(15,0)  , 
	CUMUL_COTISATION  NUMERIC(15,2)  , 
	MONTANT_RESTANT NUMERIC(15,2) , 
	CSPY  VARCHAR(24)  NOT NULL, 
	PSPY  VARCHAR(24)  NOT NULL
);
COMMENT ON TABLE SCHEMA.PT_COMPTEURS is '';
COMMENT ON COLUMN SCHEMA.PT_COMPTEURS.ID is 'Id du compteur';
COMMENT ON COLUMN SCHEMA.PT_COMPTEURS.PSPY is 'spy - Champ espion, défini quand et qui a effectué la dernière modification de l''entité';
COMMENT ON COLUMN SCHEMA.PT_COMPTEURS.CUMUL_COTISATION is 'salaire cumulé pour cette année';
COMMENT ON COLUMN SCHEMA.PT_COMPTEURS.ID_PT_POSTES_TRAVAILS is 'id posteTravail';
COMMENT ON COLUMN SCHEMA.PT_COMPTEURS.ANNEE is 'année du salaire';
COMMENT ON COLUMN SCHEMA.PT_COMPTEURS.CSPY is 'spy - Champ espion, défini quand et qui a créé l''entité';

CREATE TABLE SCHEMA.PT_CONGES_PAYES (
	ID NUMERIC(15,0)  NOT NULL PRIMARY KEY, 
	ID_FAPASSP NUMERIC(15,0), 
	ID_PT_POSTES_TRAVAILS NUMERIC(15,0),
	CS_ETAT NUMERIC(15,0), 
	CS_BENEFICIAIRE  NUMERIC(15,0), 
	ANNEE_DEBUT  NUMERIC(4,0), 
	ANNEE_FIN  NUMERIC(4,0), 
	SALAIRE_NON_DECLARE  NUMERIC(15,2), 
	DATE_SALAIRE_NON_DECLARE  NUMERIC(8,0), 
	TAUX_CP  NUMERIC(8,5), 
	MONTANT_NET  NUMERIC(15,2),
	SALAIRE_DECLARE  NUMERIC(15,2),
	TOTAL_SALAIRE  NUMERIC(15,2),
	CSPY VARCHAR(24) NOT NULL, 
	PSPY VARCHAR(24) NOT NULL
);
COMMENT ON TABLE SCHEMA.PT_CONGES_PAYES is '';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.ID is 'Id du congé payé';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.TAUX_CP is 'taux congé payé';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.ID_FAPASSP is 'id du passage facturation';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.ID_PT_POSTES_TRAVAILS is 'id posteTravail';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.MONTANT_NET is 'montant du congé payé';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.CS_ETAT is 'état du congé payé';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.CS_BENEFICIAIRE is 'bénéficiaire de l''absence justifiée';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.ANNEE_FIN is 'année de fin du congé payé';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.DATE_SALAIRE_NON_DECLARE is 'date du salaire non déclaré';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.ANNEE_DEBUT is 'année de début du congé payé';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.SALAIRE_NON_DECLARE is 'salaire non déclaré';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.CSPY is 'spy - Champ espion, défini quand et qui a créé l''entité';
COMMENT ON COLUMN SCHEMA.PT_CONGES_PAYES.PSPY is 'spy - Champ espion, défini quand et qui a effectué la dernière modification de l''entité';


CREATE TABLE SCHEMA.PT_LIGNES_COMPTEURS (
	ID NUMERIC(15) NOT NULL PRIMARY KEY,
	ID_PT_COMPTEURS NUMERIC(15) NOT NULL,
	ID_PT_CONGES_PAYES NUMERIC(15) NOT NULL,
	MONTANT NUMERIC(15,2) NOT NULL,
	CSPY VARCHAR(24) NOT NULL,
	PSPY VARCHAR(24) NOT NULL
);

CREATE TABLE SCHEMA.PT_TAUX_CONGES_PAYES (
	ID NUMERIC(15) NOT NULL PRIMARY KEY,	
	ID_PT_CONGES_PAYES NUMERIC(15) NOT NULL,
	ID_AFASSUP NUMERIC(15) NOT NULL,
	TAUX NUMERIC(8,5) NOT NULL,
	CSPY VARCHAR(24) NOT NULL,
	PSPY VARCHAR(24) NOT NULL
);


CREATE TABLE SCHEMA.PT_SERVICES_MILITAIRES(
	ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
	ID_PT_POSTES_TRAVAILS NUMERIC(15,0) NOT NULL,
	ID_FAPASSP NUMERIC(15,0) NOT NULL,
	CS_GENRE NUMERIC(15,0),
	DATE_DEBUT NUMERIC(8,0),
	DATE_FIN NUMERIC(8,0),
	CS_BENEFICIAIRE NUMERIC(9,0),
	CS_ETAT NUMERIC(9,0),
	NB_JOURS NUMERIC(15,2),
	NB_HEURES_JOUR NUMERIC(4,2),
	SALAIRE_HORAIRE NUMERIC(15,2),
	COUVERTURE_APG NUMERIC(8,5),
	VERSEMENT_APG NUMERIC(15,2),
	COMPENSATION_APG NUMERIC(15,2),
	MONTANT_BRUT NUMERIC(15,2),
	MONTANT_A_VERSER NUMERIC(15,2),
	BASE_SALAIRE NUMERIC(15,2),
	TAUX_GRATIFICATION NUMERIC(15,3),
	TAUX_CP NUMERIC(15,3),
	PSPY VARCHAR(24) NOT NULL,
	CSPY VARCHAR(24) NOT NULL
);


CREATE TABLE SCHEMA.PT_TAUX_SERVICES_MILITAIRES (
	ID NUMERIC(15) NOT NULL PRIMARY KEY,
	ID_AFASSUP NUMERIC(15) NOT NULL,
	ID_PT_SERVICES_MILITAIRES NUMERIC(15) NOT NULL,
	TAUX NUMERIC(8,5) NOT NULL,
	CSPY VARCHAR(24) NOT NULL,
	PSPY VARCHAR(24) NOT NULL
);



CREATE TABLE SCHEMA.PT_ASSOCIATION_COTISATION ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_PT_COTISATIONS_AP DECIMAL(15) NOT NULL,
	ID_PT_EMPLOYEURS NUMERIC(15) NOT NULL,
	CS_GENRE NUMERIC(8) NOT NULL,
	DATE_DEBUT NUMERIC(8) NOT NULL,
	DATE_FIN NUMERIC(8) NOT NULL,
	MASSE_SALARIALE NUMERIC(15,2) NOT NULL,
	REDUCTION_FACTURE NUMERIC(8,5) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);



CREATE TABLE SCHEMA.PT_CAISSES_MALADIES (
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_PT_TRAVAILLEURS DECIMAL(15) NOT NULL,
	ID_PT_POSTES_TRAVAILS numeric(15,0),
	ID_TIADMIP DECIMAL(15) NOT NULL,
	MOIS_DEBUT DECIMAL(6) NOT NULL,
	MOIS_FIN DECIMAL(6),
	DATE_DEBUT_ANNONCE DECIMAL(8) NOT NULL,
	DATE_FIN_ANNONCE DECIMAL(8) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_SYNDICATS ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_TIADMIP DECIMAL(15) NOT NULL,
	ID_PT_TRAVAILLEURS NUMERIC(15) NOT NULL,
	DATE_DEBUT NUMERIC(8) NOT NULL,
	DATE_FIN NUMERIC(8) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_COTISATIONS_AP (
	ID NUMERIC(15) NOT NULL PRIMARY KEY,
	LIBELLE VARCHAR(255) NOT NULL,
	LIBELLE_UPPER VARCHAR(255) NOT NULL,
	MONTANT_BASE NUMERIC(15,2) NOT NULL,
	MONTANT_MINIMUM NUMERIC(15,2) NOT NULL,
	MONTANT_MAXIMUM NUMERIC(15,2) NOT NULL,
	ID_TIADMIP NUMERIC(15) NOT NULL,
	CS_GENRE NUMERIC(8) NOT NULL,
	CSPY VARCHAR(24) NOT NULL,
	PSPY VARCHAR(24) NOT NULL
);


CREATE TABLE SCHEMA.PT_PARAMETRES_COT_AP ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_COTISATIONS_AP DECIMAL(15),
	TAUX DECIMAL(8,5),
	FOURCHETTE_DEBUT DECIMAL(15,2),
	FOURCHETTE_FIN DECIMAL(15,2),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_TAUX_IMPOSITION (
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	PERIODE_DEBUT NUMERIC(8) NOT NULL,
	PERIODE_FIN NUMERIC(8),
	CS_CANTON NUMERIC(8) NOT NULL,
	CS_TYPE_IMP NUMERIC(8) NOT NULL,
	TAUX NUMERIC(8,5) NOT NULL,
	CSPY CHAR(24),
	PSPY CHAR(24)
);


CREATE TABLE SCHEMA.PT_HISTORIQUE_PROCESSUS_AF ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_PROCESSUS DECIMAL(15) NOT NULL,
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_SUIVI_CAISSE_MALADIE ( 
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	ID_TRAVAILLEUR DECIMAL(15) NOT NULL,
	ID_CAISSE_MALADIE DECIMAL(15) NOT NULL,
	CS_TYPE_DOCUMENT DECIMAL(9) NOT NULL,
	DATE_ENVOI DECIMAL(8),
	IS_ENVOYE DECIMAL(1),
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);


CREATE TABLE SCHEMA.PT_PARAMETRES_SYNDICATS(
	ID NUMERIC(15) NOT NULL PRIMARY KEY,
	ID_TIADMIP NUMERIC(15) NOT NULL,
	ID_CAISSE_METIER NUMERIC(15) NOT NULL,
	POURCENTAGE NUMERIC(8,5) NOT NULL,
	MONTANT_PAR_TRAVAILLEUR NUMERIC(15,2) NOT NULL,
	DATE_DEBUT NUMERIC(8,0) NOT NULL,
	DATE_FIN NUMERIC(8,0),
	CSPY CHAR(24),
	PSPY CHAR(24)
);


CREATE TABLE SCHEMA.PT_NOTIFICATIONS(
	ID DECIMAL(15) NOT NULL PRIMARY KEY,
	INFOTYPE VARCHAR(100),
	TARGETID DECIMAL(15),
	EXTRA VARCHAR(255),
	DATETIME_TRAITEMENT DECIMAL(17),
	RESULT_TRAITEMENT VARCHAR(100),
	ERROR_MSG VARCHAR(2000) DEFAULT '',
	CSPY VARCHAR(24),
	PSPY VARCHAR(24)
);



--  Create Foreign Key Constraints 

ALTER TABLE SCHEMA.PT_POSTES_TRAVAILS ADD CONSTRAINT FK_PT_POSTES_PT_TRAVAILLEURS FOREIGN KEY (ID_PT_TRAVAILLEURS) REFERENCES SCHEMA.PT_TRAVAILLEURS (ID);
ALTER TABLE SCHEMA.PT_POSTES_TRAVAILS ADD CONSTRAINT FK_PT_POSTES_PT_EMPLOYEUR FOREIGN KEY (ID_AFAFFIP) REFERENCES SCHEMA.PT_EMPLOYEURS (ID_AFAFFIP);

ALTER TABLE SCHEMA.PT_ABSENCES_JUSTIFIEES ADD CONSTRAINT FK_PT_ABSENCES_JUSTIFIEES_FAPASSP FOREIGN KEY (ID_FAPASSP) REFERENCES SCHEMA.FAPASSP (IDPASSAGE);

ALTER TABLE SCHEMA.PT_CONGES_PAYES ADD CONSTRAINT FK_PT_CONGES_PAYES_FAPASSP FOREIGN KEY (ID_FAPASSP) REFERENCES SCHEMA.FAPASSP (IDPASSAGE);

ALTER TABLE SCHEMA.PT_LIGNES_COMPTEURS ADD CONSTRAINT FK_PT_LIGNES_COMPTEURS_PT_CONGES_PAYES FOREIGN KEY (ID_PT_CONGES_PAYES) REFERENCES SCHEMA.PT_CONGES_PAYES(ID) ON DELETE CASCADE;
ALTER TABLE SCHEMA.PT_TAUX_CONGES_PAYES ADD CONSTRAINT FK_PT_TAUX_CONGES_PAYES_PT_CONGES_PAYES FOREIGN KEY (ID_PT_CONGES_PAYES) REFERENCES SCHEMA.PT_CONGES_PAYES(ID) ON DELETE CASCADE;
ALTER TABLE SCHEMA.PT_TAUX_CONGES_PAYES ADD CONSTRAINT FK_ID_AFASSUP FOREIGN KEY(ID_AFASSUP) REFERENCES SCHEMA.AFASSUP(MBIASS);

ALTER TABLE SCHEMA.PT_SERVICES_MILITAIRES ADD CONSTRAINT FK_PT_SERVICES_MILITAIRES_FAPASSP FOREIGN KEY (ID_FAPASSP) REFERENCES SCHEMA.FAPASSP(IDPASSAGE);
ALTER TABLE SCHEMA.PT_TAUX_SERVICES_MILITAIRES ADD CONSTRAINT FK_PT_TAUX_SERVICES_MILITAIRES_AFASSUP FOREIGN KEY (ID_AFASSUP) REFERENCES SCHEMA.AFASSUP(MBIASS);
ALTER TABLE SCHEMA.PT_TAUX_SERVICES_MILITAIRES ADD CONSTRAINT FK_PT_TAUX_SERVICES_MILITAIRES_PT_SERVICES_MILITAIRES FOREIGN KEY (ID_PT_SERVICES_MILITAIRES) REFERENCES SCHEMA.PT_SERVICES_MILITAIRES(ID) ON DELETE CASCADE;
ALTER TABLE SCHEMA.PT_COTISATIONS_AP ADD CONSTRAINT FK_TIADMIP_COTI FOREIGN KEY (ID_TIADMIP) REFERENCES SCHEMA.TIADMIP(HTITIE);
ALTER TABLE SCHEMA.PT_PARAMETRES_SYNDICATS ADD CONSTRAINT FK_TIADMIP_SYNDICAT FOREIGN KEY (ID_TIADMIP) REFERENCES SCHEMA.TIADMIP(HTITIE);
ALTER TABLE SCHEMA.PT_PARAMETRES_SYNDICATS ADD CONSTRAINT FK_TIADMIP_CAISSE_METIER FOREIGN KEY (ID_CAISSE_METIER) REFERENCES SCHEMA.TIADMIP(HTITIE);	

ALTER TABLE SCHEMA.PT_LIGNES_TAXATIONS ADD CONSTRAINT FK_PT_LIGNES_TAXATIONS_PT_TAXATIONS_OFFICE FOREIGN KEY (ID_PT_TAXATIONS_OFFICE) REFERENCES SCHEMA.PT_TAXATIONS_OFFICE (ID) ON DELETE CASCADE;

ALTER TABLE SCHEMA.PT_TAUX_OCCUPATIONS ADD CONSTRAINT FK_PT_TAUX_OCCU_PT_POSTES FOREIGN KEY (ID_PT_POSTES_TRAVAILS) REFERENCES SCHEMA.PT_POSTES_TRAVAILS (ID) ON DELETE CASCADE;
ALTER TABLE SCHEMA.PT_ADHESIONS_COTIS_POSTES  ADD CONSTRAINT FK_PT_ADHESIONS_COTISATIONS_POSTES_PT_POSTES_TRAVAILS FOREIGN KEY (ID_PT_POSTES_TRAVAILS) REFERENCES SCHEMA.PT_POSTES_TRAVAILS (ID) ON DELETE CASCADE;
ALTER TABLE SCHEMA.PT_HISTORIQUE_DECOMPTES ADD CONSTRAINT FK_PT_HISTORIQUE_DECOMPTES_PT_DECOMPTES 	FOREIGN KEY (ID_PT_DECOMPTES) REFERENCES SCHEMA.PT_DECOMPTES (ID) ON DELETE CASCADE;
ALTER TABLE SCHEMA.PT_COTISATION_DECOMPTES ADD CONSTRAINT FK_PT_COTISATION_DECOMPTES_PT_DECOMPTE_LIGNES FOREIGN KEY (ID_PT_DECOMPTE_LIGNES) REFERENCES SCHEMA.PT_DECOMPTE_LIGNES (ID) ON DELETE CASCADE;

ALTER TABLE SCHEMA.PT_ABSENCES ADD CONSTRAINT FK_PT_ABSENCES_PT_DECOMPTE_LIGNES FOREIGN KEY (ID_PT_DECOMPTE_LIGNES) REFERENCES SCHEMA.PT_DECOMPTE_LIGNES(ID) ON DELETE CASCADE;




CREATE INDEX SCHEMA.PT_COTISATION_DECOMPTES_IDX01 ON SCHEMA.PT_COTISATION_DECOMPTES (ID_PT_DECOMPTE_LIGNES);
CREATE INDEX SCHEMA.PT_DECOMPTE_LIGNES_IDX01 ON SCHEMA.PT_DECOMPTE_LIGNES(ID_PT_DECOMPTES);
CREATE INDEX IDX_ID_PT_POSTES_TRAVAILS ON SCHEMA.PT_DECOMPTE_LIGNES(ID_PT_POSTES_TRAVAIL);
CREATE INDEX IDX_ETAT_RAPPEL ON SCHEMA.PT_DECOMPTES (CS_ETAT, DATE_RAPPEL);
CREATE INDEX IDX_NOTIFICATIONS_TARGETID ON SCHEMA.PT_NOTIFICATIONS(TARGETID);



REORG TABLE SCHEMA.PT_ABSENCES;
REORG TABLE SCHEMA.PT_ADHESIONS_COTIS_POSTES;
REORG TABLE SCHEMA.PT_CONV_QUALIFICATIONS;
REORG TABLE SCHEMA.PT_COTISATION_DECOMPTES;
REORG TABLE SCHEMA.PT_DECOMPTE_LIGNES;
REORG TABLE SCHEMA.PT_DECOMPTES;
REORG TABLE SCHEMA.PT_EMPLOYEURS;
REORG TABLE SCHEMA.PT_HISTORIQUE_DECOMPTES;
REORG TABLE SCHEMA.PT_POSTES_TRAVAILS;
REORG TABLE SCHEMA.PT_TAUX_OCCUPATIONS;
REORG TABLE SCHEMA.PT_TRAVAILLEURS;
REORG TABLE SCHEMA.PT_LIGNES_TAXATIONS;
REORG TABLE SCHEMA.PT_TAXATIONS_OFFICE;
REORG TABLE SCHEMA.PT_ABSENCES_JUSTIFIEES;
REORG TABLE SCHEMA.PT_COMPTEURS;
REORG TABLE SCHEMA.PT_CONGES_PAYES;
REORG TABLE SCHEMA.PT_LIGNES_COMPTEURS;
REORG TABLE SCHEMA.PT_TAUX_CONGES_PAYES;
REORG TABLE SCHEMA.PT_SERVICES_MILITAIRES;
REORG TABLE SCHEMA.PT_TAUX_SERVICES_MILITAIRES;
REORG TABLE SCHEMA.PT_ASSOCIATION_COTISATION;
REORG TABLE SCHEMA.PT_CAISSES_MALADIES;
REORG TABLE SCHEMA.PT_SYNDICATS;
REORG TABLE SCHEMA.PT_COTISATIONS_AP;
REORG TABLE SCHEMA.PT_PARAMETRES_COT_AP;
REORG TABLE SCHEMA.PT_TAUX_IMPOSITION;
REORG TABLE SCHEMA.PT_HISTORIQUE_PROCESSUS_AF;
REORG TABLE SCHEMA.PT_SUIVI_CAISSE_MALADIE;
REORG TABLE SCHEMA.PT_PARAMETRES_SYNDICATS;
REORG TABLE SCHEMA.PT_NOTIFICATIONS;


--************************************************************************
--*************   0.01.01
--************************************************************************
ALTER TABLE SCHEMA.caorexp ADD COLUMN NOMSEARCH varchar(255);
ALTER TABLE SCHEMA.afaffip ADD COLUMN MACONV NUMERIC(15,0);

REORG TABLE SCHEMA.caorexp;
REORG TABLE SCHEMA.afaffip;

