//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * 
 * Meldung des EL-Fälle mit Anspruch auf AHV/IV-Leistungen, Rückmeldung der ZAS.
 * Code Anwendungsgebiet 61
 * 
 * 
 * <p>
 * Java class for ELRueckMeldung_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ELRueckMeldung_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ELStelleZweigstelle" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
 *         &lt;element name="NummerLeistungsauszahlendeAKZweigstelle" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType" minOccurs="0"/>
 *         &lt;element name="InternerHinweisELStelle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VNrLeistungsberechtigtePerson" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type" minOccurs="0"/>
 *         &lt;element name="VNr1Ergaenzend" type="{http://www.zas.admin.ch/RC}VersichertennummerErgaenzend_Type" minOccurs="0"/>
 *         &lt;element name="Zivilstand" type="{http://www.zas.admin.ch/RC}ZivilstandNr_Type" minOccurs="0"/>
 *         &lt;element name="Fluechtling" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="WohnkantonStaat" type="{http://www.zas.admin.ch/RC}WohnkantonStaatBSV_weakType" minOccurs="0"/>
 *         &lt;element name="Anspruchsbeginn" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type" minOccurs="0"/>
 *         &lt;element name="AnspruchsEnde" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type" minOccurs="0"/>
 *         &lt;element name="Berichtsmonat" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type" minOccurs="0"/>
 *         &lt;element name="Mutationscode" type="{http://www.zas.admin.ch/RC}Mutationscode_Type" minOccurs="0"/>
 *         &lt;element name="ZustaendigeIVStelle" type="{http://www.zas.admin.ch/RC}IVStelle_strongType" minOccurs="0"/>
 *         &lt;element name="Invaliditaetsgrad" type="{http://www.zas.admin.ch/RC}Invaliditaetsgrad_weakType" minOccurs="0"/>
 *         &lt;element name="Gebrechensschluessel" type="{http://www.zas.admin.ch/RC}UnsignedInt5stellig_Type" minOccurs="0"/>
 *         &lt;element name="InvalideHinterlassene" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Leistungsart" type="{http://www.zas.admin.ch/RC}Leistungsart_alle_Revisionen_strongType" minOccurs="0"/>
 *         &lt;element name="BruchteilRente" type="{http://www.zas.admin.ch/RC}IVRentenbruchteil_Type" minOccurs="0"/>
 *         &lt;element name="MonatsbetragNeu" type="{http://www.zas.admin.ch/RC}BetragFR5MitNull_Type" minOccurs="0"/>
 *         &lt;element name="MonatsbetragAlt" type="{http://www.zas.admin.ch/RC}BetragFR5MitNull_Type" minOccurs="0"/>
 *         &lt;element name="BemerkungenZAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Verarbeitungscode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ELRueckMeldung_Type", propOrder = { "elStelleZweigstelle", "nummerLeistungsauszahlendeAKZweigstelle",
        "internerHinweisELStelle", "vNrLeistungsberechtigtePerson", "vNr1Ergaenzend", "zivilstand", "fluechtling",
        "wohnkantonStaat", "anspruchsbeginn", "anspruchsEnde", "berichtsmonat", "mutationscode", "zustaendigeIVStelle",
        "invaliditaetsgrad", "gebrechensschluessel", "invalideHinterlassene", "leistungsart", "bruchteilRente",
        "monatsbetragNeu", "monatsbetragAlt", "bemerkungenZAS", "verarbeitungscode" })
public class ELRueckMeldungType {

    @XmlElement(name = "ELStelleZweigstelle", required = true)
    protected String elStelleZweigstelle;
    @XmlElement(name = "NummerLeistungsauszahlendeAKZweigstelle")
    protected String nummerLeistungsauszahlendeAKZweigstelle;
    @XmlElement(name = "InternerHinweisELStelle")
    protected String internerHinweisELStelle;
    @XmlElement(name = "VNrLeistungsberechtigtePerson")
    protected String vNrLeistungsberechtigtePerson;
    @XmlList
    @XmlElement(name = "VNr1Ergaenzend")
    protected List<String> vNr1Ergaenzend;
    @XmlElement(name = "Zivilstand")
    protected Short zivilstand;
    @XmlElement(name = "Fluechtling")
    protected Boolean fluechtling;
    @XmlElement(name = "WohnkantonStaat")
    protected String wohnkantonStaat;
    @XmlElement(name = "Anspruchsbeginn")
    protected XMLGregorianCalendar anspruchsbeginn;
    @XmlElement(name = "AnspruchsEnde")
    protected XMLGregorianCalendar anspruchsEnde;
    @XmlElement(name = "Berichtsmonat")
    protected XMLGregorianCalendar berichtsmonat;
    @XmlElement(name = "Mutationscode")
    protected Short mutationscode;
    @XmlElement(name = "ZustaendigeIVStelle")
    protected Integer zustaendigeIVStelle;
    @XmlElement(name = "Invaliditaetsgrad")
    protected Short invaliditaetsgrad;
    @XmlElement(name = "Gebrechensschluessel")
    protected Long gebrechensschluessel;
    @XmlElement(name = "InvalideHinterlassene")
    protected Boolean invalideHinterlassene;
    @XmlList
    @XmlElement(name = "Leistungsart")
    protected List<String> leistungsart;
    @XmlElement(name = "BruchteilRente")
    protected Short bruchteilRente;
    @XmlElement(name = "MonatsbetragNeu")
    protected Integer monatsbetragNeu;
    @XmlElement(name = "MonatsbetragAlt")
    protected Integer monatsbetragAlt;
    @XmlElement(name = "BemerkungenZAS")
    protected String bemerkungenZAS;
    @XmlElement(name = "Verarbeitungscode")
    protected String verarbeitungscode;

    /**
     * Gets the value of the elStelleZweigstelle property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getELStelleZweigstelle() {
        return elStelleZweigstelle;
    }

    /**
     * Sets the value of the elStelleZweigstelle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setELStelleZweigstelle(String value) {
        elStelleZweigstelle = value;
    }

    /**
     * Gets the value of the nummerLeistungsauszahlendeAKZweigstelle property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getNummerLeistungsauszahlendeAKZweigstelle() {
        return nummerLeistungsauszahlendeAKZweigstelle;
    }

    /**
     * Sets the value of the nummerLeistungsauszahlendeAKZweigstelle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNummerLeistungsauszahlendeAKZweigstelle(String value) {
        nummerLeistungsauszahlendeAKZweigstelle = value;
    }

    /**
     * Gets the value of the internerHinweisELStelle property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getInternerHinweisELStelle() {
        return internerHinweisELStelle;
    }

    /**
     * Sets the value of the internerHinweisELStelle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInternerHinweisELStelle(String value) {
        internerHinweisELStelle = value;
    }

    /**
     * Gets the value of the vNrLeistungsberechtigtePerson property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getVNrLeistungsberechtigtePerson() {
        return vNrLeistungsberechtigtePerson;
    }

    /**
     * Sets the value of the vNrLeistungsberechtigtePerson property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVNrLeistungsberechtigtePerson(String value) {
        vNrLeistungsberechtigtePerson = value;
    }

    /**
     * Gets the value of the vNr1Ergaenzend property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the vNr1Ergaenzend property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getVNr1Ergaenzend().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getVNr1Ergaenzend() {
        if (vNr1Ergaenzend == null) {
            vNr1Ergaenzend = new ArrayList<String>();
        }
        return vNr1Ergaenzend;
    }

    /**
     * Gets the value of the zivilstand property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getZivilstand() {
        return zivilstand;
    }

    /**
     * Sets the value of the zivilstand property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setZivilstand(Short value) {
        zivilstand = value;
    }

    /**
     * Gets the value of the fluechtling property.
     * 
     * @return
     *         possible object is {@link Boolean }
     * 
     */
    public Boolean isFluechtling() {
        return fluechtling;
    }

    /**
     * Sets the value of the fluechtling property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setFluechtling(Boolean value) {
        fluechtling = value;
    }

    /**
     * Gets the value of the wohnkantonStaat property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getWohnkantonStaat() {
        return wohnkantonStaat;
    }

    /**
     * Sets the value of the wohnkantonStaat property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWohnkantonStaat(String value) {
        wohnkantonStaat = value;
    }

    /**
     * Gets the value of the anspruchsbeginn property.
     * 
     * @return
     *         possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getAnspruchsbeginn() {
        return anspruchsbeginn;
    }

    /**
     * Sets the value of the anspruchsbeginn property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setAnspruchsbeginn(XMLGregorianCalendar value) {
        anspruchsbeginn = value;
    }

    /**
     * Gets the value of the anspruchsEnde property.
     * 
     * @return
     *         possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getAnspruchsEnde() {
        return anspruchsEnde;
    }

    /**
     * Sets the value of the anspruchsEnde property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setAnspruchsEnde(XMLGregorianCalendar value) {
        anspruchsEnde = value;
    }

    /**
     * Gets the value of the berichtsmonat property.
     * 
     * @return
     *         possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getBerichtsmonat() {
        return berichtsmonat;
    }

    /**
     * Sets the value of the berichtsmonat property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setBerichtsmonat(XMLGregorianCalendar value) {
        berichtsmonat = value;
    }

    /**
     * Gets the value of the mutationscode property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getMutationscode() {
        return mutationscode;
    }

    /**
     * Sets the value of the mutationscode property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setMutationscode(Short value) {
        mutationscode = value;
    }

    /**
     * Gets the value of the zustaendigeIVStelle property.
     * 
     * @return
     *         possible object is {@link Integer }
     * 
     */
    public Integer getZustaendigeIVStelle() {
        return zustaendigeIVStelle;
    }

    /**
     * Sets the value of the zustaendigeIVStelle property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setZustaendigeIVStelle(Integer value) {
        zustaendigeIVStelle = value;
    }

    /**
     * Gets the value of the invaliditaetsgrad property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getInvaliditaetsgrad() {
        return invaliditaetsgrad;
    }

    /**
     * Sets the value of the invaliditaetsgrad property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setInvaliditaetsgrad(Short value) {
        invaliditaetsgrad = value;
    }

    /**
     * Gets the value of the gebrechensschluessel property.
     * 
     * @return
     *         possible object is {@link Long }
     * 
     */
    public Long getGebrechensschluessel() {
        return gebrechensschluessel;
    }

    /**
     * Sets the value of the gebrechensschluessel property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setGebrechensschluessel(Long value) {
        gebrechensschluessel = value;
    }

    /**
     * Gets the value of the invalideHinterlassene property.
     * 
     * @return
     *         possible object is {@link Boolean }
     * 
     */
    public Boolean isInvalideHinterlassene() {
        return invalideHinterlassene;
    }

    /**
     * Sets the value of the invalideHinterlassene property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setInvalideHinterlassene(Boolean value) {
        invalideHinterlassene = value;
    }

    /**
     * Gets the value of the leistungsart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the leistungsart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLeistungsart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getLeistungsart() {
        if (leistungsart == null) {
            leistungsart = new ArrayList<String>();
        }
        return leistungsart;
    }

    /**
     * Gets the value of the bruchteilRente property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getBruchteilRente() {
        return bruchteilRente;
    }

    /**
     * Sets the value of the bruchteilRente property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setBruchteilRente(Short value) {
        bruchteilRente = value;
    }

    /**
     * Gets the value of the monatsbetragNeu property.
     * 
     * @return
     *         possible object is {@link Integer }
     * 
     */
    public Integer getMonatsbetragNeu() {
        return monatsbetragNeu;
    }

    /**
     * Sets the value of the monatsbetragNeu property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setMonatsbetragNeu(Integer value) {
        monatsbetragNeu = value;
    }

    /**
     * Gets the value of the monatsbetragAlt property.
     * 
     * @return
     *         possible object is {@link Integer }
     * 
     */
    public Integer getMonatsbetragAlt() {
        return monatsbetragAlt;
    }

    /**
     * Sets the value of the monatsbetragAlt property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setMonatsbetragAlt(Integer value) {
        monatsbetragAlt = value;
    }

    /**
     * Gets the value of the bemerkungenZAS property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getBemerkungenZAS() {
        return bemerkungenZAS;
    }

    /**
     * Sets the value of the bemerkungenZAS property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBemerkungenZAS(String value) {
        bemerkungenZAS = value;
    }

    /**
     * Gets the value of the verarbeitungscode property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getVerarbeitungscode() {
        return verarbeitungscode;
    }

    /**
     * Sets the value of the verarbeitungscode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVerarbeitungscode(String value) {
        verarbeitungscode = value;
    }

}
