//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Code application 24: communication de l'état du registre des assurés de la Centrale
 * 
 * <p>
 * Java class for IKBestandesmeldung_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IKBestandesmeldung_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IKKopf">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="KasseZweigstelleIKFuehrend" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
 *                   &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type"/>
 *                   &lt;element name="VersichertenNrFruehere" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type" minOccurs="0"/>
 *                   &lt;element name="VersichertenAngaben" type="{http://www.zas.admin.ch/RC}TVersicherteAngabenVoll"/>
 *                   &lt;element name="MZRSchluesselzahl" type="{http://www.zas.admin.ch/RC}MZRSchluesselzahl_weakType"/>
 *                   &lt;element name="IKEroeffnungsdatum" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FruehererAuftrag" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="KasseZweigstelleAuftraggebend" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
 *                   &lt;element name="MZRSchluesselzahl" type="{http://www.zas.admin.ch/RC}MZRSchluesselzahl_weakType"/>
 *                   &lt;element name="ZIK">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Abschlussdatum" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IKBestandesmeldung_Type", propOrder = { "ikKopf", "fruehererAuftrag" })
public class IKBestandesmeldungType {

    @XmlElement(name = "IKKopf", required = true)
    protected IKBestandesmeldungType.IKKopf ikKopf;
    @XmlElement(name = "FruehererAuftrag")
    protected IKBestandesmeldungType.FruehererAuftrag fruehererAuftrag;

    /**
     * Gets the value of the ikKopf property.
     * 
     * @return
     *         possible object is {@link IKBestandesmeldungType.IKKopf }
     * 
     */
    public IKBestandesmeldungType.IKKopf getIKKopf() {
        return ikKopf;
    }

    /**
     * Sets the value of the ikKopf property.
     * 
     * @param value
     *            allowed object is {@link IKBestandesmeldungType.IKKopf }
     * 
     */
    public void setIKKopf(IKBestandesmeldungType.IKKopf value) {
        ikKopf = value;
    }

    /**
     * Gets the value of the fruehererAuftrag property.
     * 
     * @return
     *         possible object is {@link IKBestandesmeldungType.FruehererAuftrag }
     * 
     */
    public IKBestandesmeldungType.FruehererAuftrag getFruehererAuftrag() {
        return fruehererAuftrag;
    }

    /**
     * Sets the value of the fruehererAuftrag property.
     * 
     * @param value
     *            allowed object is {@link IKBestandesmeldungType.FruehererAuftrag }
     * 
     */
    public void setFruehererAuftrag(IKBestandesmeldungType.FruehererAuftrag value) {
        fruehererAuftrag = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="KasseZweigstelleAuftraggebend" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
     *         &lt;element name="MZRSchluesselzahl" type="{http://www.zas.admin.ch/RC}MZRSchluesselzahl_weakType"/>
     *         &lt;element name="ZIK">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Abschlussdatum" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "kasseZweigstelleAuftraggebend", "mzrSchluesselzahl", "zik" })
    public static class FruehererAuftrag {

        @XmlElement(name = "KasseZweigstelleAuftraggebend", required = true)
        protected String kasseZweigstelleAuftraggebend;
        @XmlElement(name = "MZRSchluesselzahl", required = true, type = Short.class, nillable = true)
        protected Short mzrSchluesselzahl;
        @XmlElement(name = "ZIK", required = true)
        protected IKBestandesmeldungType.FruehererAuftrag.ZIK zik;

        /**
         * Gets the value of the kasseZweigstelleAuftraggebend property.
         * 
         * @return
         *         possible object is {@link String }
         * 
         */
        public String getKasseZweigstelleAuftraggebend() {
            return kasseZweigstelleAuftraggebend;
        }

        /**
         * Sets the value of the kasseZweigstelleAuftraggebend property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setKasseZweigstelleAuftraggebend(String value) {
            kasseZweigstelleAuftraggebend = value;
        }

        /**
         * Gets the value of the mzrSchluesselzahl property.
         * 
         * @return
         *         possible object is {@link Short }
         * 
         */
        public Short getMZRSchluesselzahl() {
            return mzrSchluesselzahl;
        }

        /**
         * Sets the value of the mzrSchluesselzahl property.
         * 
         * @param value
         *            allowed object is {@link Short }
         * 
         */
        public void setMZRSchluesselzahl(Short value) {
            mzrSchluesselzahl = value;
        }

        /**
         * Gets the value of the zik property.
         * 
         * @return
         *         possible object is {@link IKBestandesmeldungType.FruehererAuftrag.ZIK }
         * 
         */
        public IKBestandesmeldungType.FruehererAuftrag.ZIK getZIK() {
            return zik;
        }

        /**
         * Sets the value of the zik property.
         * 
         * @param value
         *            allowed object is {@link IKBestandesmeldungType.FruehererAuftrag.ZIK }
         * 
         */
        public void setZIK(IKBestandesmeldungType.FruehererAuftrag.ZIK value) {
            zik = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Abschlussdatum" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "abschlussdatum" })
        public static class ZIK {

            @XmlElement(name = "Abschlussdatum", required = true)
            protected XMLGregorianCalendar abschlussdatum;

            /**
             * Gets the value of the abschlussdatum property.
             * 
             * @return
             *         possible object is {@link XMLGregorianCalendar }
             * 
             */
            public XMLGregorianCalendar getAbschlussdatum() {
                return abschlussdatum;
            }

            /**
             * Sets the value of the abschlussdatum property.
             * 
             * @param value
             *            allowed object is {@link XMLGregorianCalendar }
             * 
             */
            public void setAbschlussdatum(XMLGregorianCalendar value) {
                abschlussdatum = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="KasseZweigstelleIKFuehrend" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
     *         &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type"/>
     *         &lt;element name="VersichertenNrFruehere" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type" minOccurs="0"/>
     *         &lt;element name="VersichertenAngaben" type="{http://www.zas.admin.ch/RC}TVersicherteAngabenVoll"/>
     *         &lt;element name="MZRSchluesselzahl" type="{http://www.zas.admin.ch/RC}MZRSchluesselzahl_weakType"/>
     *         &lt;element name="IKEroeffnungsdatum" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "kasseZweigstelleIKFuehrend", "versichertennummer", "versichertenNrFruehere",
            "versichertenAngaben", "mzrSchluesselzahl", "ikEroeffnungsdatum" })
    public static class IKKopf {

        @XmlElement(name = "KasseZweigstelleIKFuehrend", required = true)
        protected String kasseZweigstelleIKFuehrend;
        @XmlElement(name = "Versichertennummer", required = true)
        protected String versichertennummer;
        @XmlElement(name = "VersichertenNrFruehere")
        protected String versichertenNrFruehere;
        @XmlElement(name = "VersichertenAngaben", required = true)
        protected TVersicherteAngabenVoll versichertenAngaben;
        @XmlElement(name = "MZRSchluesselzahl", required = true, type = Short.class, nillable = true)
        protected Short mzrSchluesselzahl;
        @XmlElement(name = "IKEroeffnungsdatum")
        protected XMLGregorianCalendar ikEroeffnungsdatum;

        /**
         * Gets the value of the kasseZweigstelleIKFuehrend property.
         * 
         * @return
         *         possible object is {@link String }
         * 
         */
        public String getKasseZweigstelleIKFuehrend() {
            return kasseZweigstelleIKFuehrend;
        }

        /**
         * Sets the value of the kasseZweigstelleIKFuehrend property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setKasseZweigstelleIKFuehrend(String value) {
            kasseZweigstelleIKFuehrend = value;
        }

        /**
         * Gets the value of the versichertennummer property.
         * 
         * @return
         *         possible object is {@link String }
         * 
         */
        public String getVersichertennummer() {
            return versichertennummer;
        }

        /**
         * Sets the value of the versichertennummer property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setVersichertennummer(String value) {
            versichertennummer = value;
        }

        /**
         * Gets the value of the versichertenNrFruehere property.
         * 
         * @return
         *         possible object is {@link String }
         * 
         */
        public String getVersichertenNrFruehere() {
            return versichertenNrFruehere;
        }

        /**
         * Sets the value of the versichertenNrFruehere property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setVersichertenNrFruehere(String value) {
            versichertenNrFruehere = value;
        }

        /**
         * Gets the value of the versichertenAngaben property.
         * 
         * @return
         *         possible object is {@link TVersicherteAngabenVoll }
         * 
         */
        public TVersicherteAngabenVoll getVersichertenAngaben() {
            return versichertenAngaben;
        }

        /**
         * Sets the value of the versichertenAngaben property.
         * 
         * @param value
         *            allowed object is {@link TVersicherteAngabenVoll }
         * 
         */
        public void setVersichertenAngaben(TVersicherteAngabenVoll value) {
            versichertenAngaben = value;
        }

        /**
         * Gets the value of the mzrSchluesselzahl property.
         * 
         * @return
         *         possible object is {@link Short }
         * 
         */
        public Short getMZRSchluesselzahl() {
            return mzrSchluesselzahl;
        }

        /**
         * Sets the value of the mzrSchluesselzahl property.
         * 
         * @param value
         *            allowed object is {@link Short }
         * 
         */
        public void setMZRSchluesselzahl(Short value) {
            mzrSchluesselzahl = value;
        }

        /**
         * Gets the value of the ikEroeffnungsdatum property.
         * 
         * @return
         *         possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getIKEroeffnungsdatum() {
            return ikEroeffnungsdatum;
        }

        /**
         * Sets the value of the ikEroeffnungsdatum property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setIKEroeffnungsdatum(XMLGregorianCalendar value) {
            ikEroeffnungsdatum = value;
        }

    }

}
