/*
 * Generated by JasperReports - 25.01.13 09:56
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class PHENIX_DETAIL_SEDEX extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_P_REF_INTERNE = null;
    private JRFillParameter parameter_L_RENTE_NE = null;
    private JRFillParameter parameter_P_NSS_CONJOINT = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_L_DATE_NAISSANCE = null;
    private JRFillParameter parameter_L_ANNEE = null;
    private JRFillParameter parameter_P_DATE_NAISSANCE_CONTRIBUABLE = null;
    private JRFillParameter parameter_L_SALAIRE = null;
    private JRFillParameter parameter_P_RACHAT_LPP = null;
    private JRFillParameter parameter_P_RENTE_PONT = null;
    private JRFillParameter parameter_L_REVENU_IND = null;
    private JRFillParameter parameter_L_DATE_MARIAGE = null;
    private JRFillParameter parameter_L_TYPE_REPONSE = null;
    private JRFillParameter parameter_P_TYPE_EVALUATION = null;
    private JRFillParameter parameter_L_REVENU_AGRICOLE = null;
    private JRFillParameter parameter_L_DATERECEPTION = null;
    private JRFillParameter parameter_P_REVENU_ETRANGER_CJT = null;
    private JRFillParameter parameter_P_RENTE_PONT_CJT = null;
    private JRFillParameter parameter_L_GENREAFFILIE = null;
    private JRFillParameter parameter_L_SEXE = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_P_ETATCIVIL_CONJOINT = null;
    private JRFillParameter parameter_P_CAPITAL_CJT = null;
    private JRFillParameter parameter_L_GENRE_TAXATION = null;
    private JRFillParameter parameter_MODEL_PATH = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_P_DATE_NAISSANCE_CONJOINT = null;
    private JRFillParameter parameter_P_DESC_CONJOINT = null;
    private JRFillParameter parameter_P_ANNEE = null;
    private JRFillParameter parameter_P_DATE_MARIAGE_CONTRIBUABLE = null;
    private JRFillParameter parameter_P_REVENU_AGRICOLE = null;
    private JRFillParameter parameter_L_DATE_ENTREE = null;
    private JRFillParameter parameter_P_REVENU_AGRICOLE_CJT = null;
    private JRFillParameter parameter_L_CAPITAL = null;
    private JRFillParameter parameter_P_CAPITAL = null;
    private JRFillParameter parameter_P_DATE_MARIAGE_CONJOINT = null;
    private JRFillParameter parameter_P_SEXE_CONJOINT = null;
    private JRFillParameter parameter_P_REMARQUE = null;
    private JRFillParameter parameter_L_RENTE_PONT = null;
    private JRFillParameter parameter_L_REVENU_ETRANGER = null;
    private JRFillParameter parameter_P_DATE_ASSIETTE = null;
    private JRFillParameter parameter_P_REF_EXTERNE = null;
    private JRFillParameter parameter_P_DATE_ENTREE_CONTRIBUABLE = null;
    private JRFillParameter parameter_P_PATRIMOINE_COMMERCIAL_CJT = null;
    private JRFillParameter parameter_P_RACHAT_LPP_CJT = null;
    private JRFillParameter parameter_L_PATRIMOINE_COMMERCIAL = null;
    private JRFillParameter parameter_P_SENDER_ID = null;
    private JRFillParameter parameter_L_CONTRIBUABLE = null;
    private JRFillParameter parameter_P_REVENU_ETRANGER = null;
    private JRFillParameter parameter_P_RENTE_NE_CJT = null;
    private JRFillParameter parameter_P_DATERECEPTION = null;
    private JRFillParameter parameter_L_RACHAT_LPP = null;
    private JRFillParameter parameter_P_GENRE_TAXATION = null;
    private JRFillParameter parameter_P_NSS_CONTRIBUABLE = null;
    private JRFillParameter parameter_L_CONJOINT = null;
    private JRFillParameter parameter_P_DATE_ENTREE_CONJOINT = null;
    private JRFillParameter parameter_P_SALAIRE_CJT = null;
    private JRFillParameter parameter_P_SEDEX_TITRE = null;
    private JRFillParameter parameter_L_DONNEE_RECAP = null;
    private JRFillParameter parameter_P_REVENU_IND = null;
    private JRFillParameter parameter_P_DATE_IMP = null;
    private JRFillParameter parameter_P_DESC_CONTRIBUABLE = null;
    private JRFillParameter parameter_L_REMARQUE = null;
    private JRFillParameter parameter_P_REVENU_IND_CJT = null;
    private JRFillParameter parameter_P_GENREAFFILIE = null;
    private JRFillParameter parameter_L_TYPE_EVALUATION = null;
    private JRFillParameter parameter_L_REF_EXTERNE = null;
    private JRFillParameter parameter_P_RENTE_NE = null;
    private JRFillParameter parameter_L_REF_INTERNE = null;
    private JRFillParameter parameter_L_DATE_ASSIETTE = null;
    private JRFillParameter parameter_L_DONNEE_BASE = null;
    private JRFillParameter parameter_L_ETATCIVIL = null;
    private JRFillParameter parameter_P_PATRIMOINE_COMMERCIAL = null;
    private JRFillParameter parameter_P_SEXE_CONTRIBUABLE = null;
    private JRFillParameter parameter_P_SALAIRE = null;
    private JRFillParameter parameter_P_ETATCIVIL_CONTRIBUABLE = null;
    private JRFillParameter parameter_P_TYPE_REPONSE = null;


    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_IMAGE_LOGO = null;
    private JRFillVariable variable_GRP_1_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_P_REF_INTERNE = (JRFillParameter)parsm.get("P_REF_INTERNE");
        parameter_L_RENTE_NE = (JRFillParameter)parsm.get("L_RENTE_NE");
        parameter_P_NSS_CONJOINT = (JRFillParameter)parsm.get("P_NSS_CONJOINT");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_L_DATE_NAISSANCE = (JRFillParameter)parsm.get("L_DATE_NAISSANCE");
        parameter_L_ANNEE = (JRFillParameter)parsm.get("L_ANNEE");
        parameter_P_DATE_NAISSANCE_CONTRIBUABLE = (JRFillParameter)parsm.get("P_DATE_NAISSANCE_CONTRIBUABLE");
        parameter_L_SALAIRE = (JRFillParameter)parsm.get("L_SALAIRE");
        parameter_P_RACHAT_LPP = (JRFillParameter)parsm.get("P_RACHAT_LPP");
        parameter_P_RENTE_PONT = (JRFillParameter)parsm.get("P_RENTE_PONT");
        parameter_L_REVENU_IND = (JRFillParameter)parsm.get("L_REVENU_IND");
        parameter_L_DATE_MARIAGE = (JRFillParameter)parsm.get("L_DATE_MARIAGE");
        parameter_L_TYPE_REPONSE = (JRFillParameter)parsm.get("L_TYPE_REPONSE");
        parameter_P_TYPE_EVALUATION = (JRFillParameter)parsm.get("P_TYPE_EVALUATION");
        parameter_L_REVENU_AGRICOLE = (JRFillParameter)parsm.get("L_REVENU_AGRICOLE");
        parameter_L_DATERECEPTION = (JRFillParameter)parsm.get("L_DATERECEPTION");
        parameter_P_REVENU_ETRANGER_CJT = (JRFillParameter)parsm.get("P_REVENU_ETRANGER_CJT");
        parameter_P_RENTE_PONT_CJT = (JRFillParameter)parsm.get("P_RENTE_PONT_CJT");
        parameter_L_GENREAFFILIE = (JRFillParameter)parsm.get("L_GENREAFFILIE");
        parameter_L_SEXE = (JRFillParameter)parsm.get("L_SEXE");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_P_ETATCIVIL_CONJOINT = (JRFillParameter)parsm.get("P_ETATCIVIL_CONJOINT");
        parameter_P_CAPITAL_CJT = (JRFillParameter)parsm.get("P_CAPITAL_CJT");
        parameter_L_GENRE_TAXATION = (JRFillParameter)parsm.get("L_GENRE_TAXATION");
        parameter_MODEL_PATH = (JRFillParameter)parsm.get("MODEL_PATH");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");
        parameter_P_DATE_NAISSANCE_CONJOINT = (JRFillParameter)parsm.get("P_DATE_NAISSANCE_CONJOINT");
        parameter_P_DESC_CONJOINT = (JRFillParameter)parsm.get("P_DESC_CONJOINT");
        parameter_P_ANNEE = (JRFillParameter)parsm.get("P_ANNEE");
        parameter_P_DATE_MARIAGE_CONTRIBUABLE = (JRFillParameter)parsm.get("P_DATE_MARIAGE_CONTRIBUABLE");
        parameter_P_REVENU_AGRICOLE = (JRFillParameter)parsm.get("P_REVENU_AGRICOLE");
        parameter_L_DATE_ENTREE = (JRFillParameter)parsm.get("L_DATE_ENTREE");
        parameter_P_REVENU_AGRICOLE_CJT = (JRFillParameter)parsm.get("P_REVENU_AGRICOLE_CJT");
        parameter_L_CAPITAL = (JRFillParameter)parsm.get("L_CAPITAL");
        parameter_P_CAPITAL = (JRFillParameter)parsm.get("P_CAPITAL");
        parameter_P_DATE_MARIAGE_CONJOINT = (JRFillParameter)parsm.get("P_DATE_MARIAGE_CONJOINT");
        parameter_P_SEXE_CONJOINT = (JRFillParameter)parsm.get("P_SEXE_CONJOINT");
        parameter_P_REMARQUE = (JRFillParameter)parsm.get("P_REMARQUE");
        parameter_L_RENTE_PONT = (JRFillParameter)parsm.get("L_RENTE_PONT");
        parameter_L_REVENU_ETRANGER = (JRFillParameter)parsm.get("L_REVENU_ETRANGER");
        parameter_P_DATE_ASSIETTE = (JRFillParameter)parsm.get("P_DATE_ASSIETTE");
        parameter_P_REF_EXTERNE = (JRFillParameter)parsm.get("P_REF_EXTERNE");
        parameter_P_DATE_ENTREE_CONTRIBUABLE = (JRFillParameter)parsm.get("P_DATE_ENTREE_CONTRIBUABLE");
        parameter_P_PATRIMOINE_COMMERCIAL_CJT = (JRFillParameter)parsm.get("P_PATRIMOINE_COMMERCIAL_CJT");
        parameter_P_RACHAT_LPP_CJT = (JRFillParameter)parsm.get("P_RACHAT_LPP_CJT");
        parameter_L_PATRIMOINE_COMMERCIAL = (JRFillParameter)parsm.get("L_PATRIMOINE_COMMERCIAL");
        parameter_P_SENDER_ID = (JRFillParameter)parsm.get("P_SENDER_ID");
        parameter_L_CONTRIBUABLE = (JRFillParameter)parsm.get("L_CONTRIBUABLE");
        parameter_P_REVENU_ETRANGER = (JRFillParameter)parsm.get("P_REVENU_ETRANGER");
        parameter_P_RENTE_NE_CJT = (JRFillParameter)parsm.get("P_RENTE_NE_CJT");
        parameter_P_DATERECEPTION = (JRFillParameter)parsm.get("P_DATERECEPTION");
        parameter_L_RACHAT_LPP = (JRFillParameter)parsm.get("L_RACHAT_LPP");
        parameter_P_GENRE_TAXATION = (JRFillParameter)parsm.get("P_GENRE_TAXATION");
        parameter_P_NSS_CONTRIBUABLE = (JRFillParameter)parsm.get("P_NSS_CONTRIBUABLE");
        parameter_L_CONJOINT = (JRFillParameter)parsm.get("L_CONJOINT");
        parameter_P_DATE_ENTREE_CONJOINT = (JRFillParameter)parsm.get("P_DATE_ENTREE_CONJOINT");
        parameter_P_SALAIRE_CJT = (JRFillParameter)parsm.get("P_SALAIRE_CJT");
        parameter_P_SEDEX_TITRE = (JRFillParameter)parsm.get("P_SEDEX_TITRE");
        parameter_L_DONNEE_RECAP = (JRFillParameter)parsm.get("L_DONNEE_RECAP");
        parameter_P_REVENU_IND = (JRFillParameter)parsm.get("P_REVENU_IND");
        parameter_P_DATE_IMP = (JRFillParameter)parsm.get("P_DATE_IMP");
        parameter_P_DESC_CONTRIBUABLE = (JRFillParameter)parsm.get("P_DESC_CONTRIBUABLE");
        parameter_L_REMARQUE = (JRFillParameter)parsm.get("L_REMARQUE");
        parameter_P_REVENU_IND_CJT = (JRFillParameter)parsm.get("P_REVENU_IND_CJT");
        parameter_P_GENREAFFILIE = (JRFillParameter)parsm.get("P_GENREAFFILIE");
        parameter_L_TYPE_EVALUATION = (JRFillParameter)parsm.get("L_TYPE_EVALUATION");
        parameter_L_REF_EXTERNE = (JRFillParameter)parsm.get("L_REF_EXTERNE");
        parameter_P_RENTE_NE = (JRFillParameter)parsm.get("P_RENTE_NE");
        parameter_L_REF_INTERNE = (JRFillParameter)parsm.get("L_REF_INTERNE");
        parameter_L_DATE_ASSIETTE = (JRFillParameter)parsm.get("L_DATE_ASSIETTE");
        parameter_L_DONNEE_BASE = (JRFillParameter)parsm.get("L_DONNEE_BASE");
        parameter_L_ETATCIVIL = (JRFillParameter)parsm.get("L_ETATCIVIL");
        parameter_P_PATRIMOINE_COMMERCIAL = (JRFillParameter)parsm.get("P_PATRIMOINE_COMMERCIAL");
        parameter_P_SEXE_CONTRIBUABLE = (JRFillParameter)parsm.get("P_SEXE_CONTRIBUABLE");
        parameter_P_SALAIRE = (JRFillParameter)parsm.get("P_SALAIRE");
        parameter_P_ETATCIVIL_CONTRIBUABLE = (JRFillParameter)parsm.get("P_ETATCIVIL_CONTRIBUABLE");
        parameter_P_TYPE_REPONSE = (JRFillParameter)parsm.get("P_TYPE_REPONSE");


        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_IMAGE_LOGO = (JRFillVariable)varsm.get("IMAGE_LOGO");
        variable_GRP_1_COUNT = (JRFillVariable)varsm.get("GRP_1_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 304 : // textField_28
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NSS_CONTRIBUABLE.getValue()));
                break;
            }
            case 349 : // textField_73
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_CAPITAL_CJT.getValue()));
                break;
            }
            case 339 : // textField_63
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_ETATCIVIL.getValue()));
                break;
            }
            case 297 : // textField_21
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_TYPE_EVALUATION.getValue()));
                break;
            }
            case 316 : // textField_40
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_MARIAGE_CONJOINT.getValue()));
                break;
            }
            case 321 : // textField_45
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_SALAIRE.getValue()));
                break;
            }
            case 294 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATERECEPTION.getValue()));
                break;
            }
            case 283 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RACHAT_LPP.getValue()));
                break;
            }
            case 298 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_GENRE_TAXATION.getValue()));
                break;
            }
            case 289 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_GENREAFFILIE.getValue()));
                break;
            }
            case 317 : // textField_41
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ENTREE_CONJOINT.getValue()));
                break;
            }
            case 324 : // textField_48
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_IND.getValue()));
                break;
            }
            case 343 : // textField_67
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_PONT_CJT.getValue()));
                break;
            }
            case 279 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_ETRANGER.getValue()));
                break;
            }
            case 320 : // textField_44
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_NAISSANCE_CONJOINT.getValue()));
                break;
            }
            case 307 : // textField_31
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_MARIAGE.getValue()));
                break;
            }
            case 312 : // textField_36
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DESC_CONJOINT.getValue()));
                break;
            }
            case 309 : // textField_33
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_ENTREE.getValue()));
                break;
            }
            case 282 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_PONT.getValue()));
                break;
            }
            case 274 : // group_GRP_1
            {
                value = (java.lang.Object)("ff");
                break;
            }
            case 350 : // textField_74
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONTRIBUABLE.getValue()));
                break;
            }
            case 348 : // textField_72
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_AGRICOLE_CJT.getValue()));
                break;
            }
            case 311 : // textField_35
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONJOINT.getValue()));
                break;
            }
            case 305 : // textField_29
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEXE_CONTRIBUABLE.getValue()));
                break;
            }
            case 265 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 266 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 264 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 341 : // textField_65
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_PATRIMOINE_COMMERCIAL_CJT.getValue()));
                break;
            }
            case 338 : // textField_62
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_SEXE.getValue()));
                break;
            }
            case 337 : // textField_61
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ASSIETTE.getValue()));
                break;
            }
            case 335 : // textField_59
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TYPE_REPONSE.getValue()));
                break;
            }
            case 290 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REF_INTERNE.getValue()));
                break;
            }
            case 326 : // textField_50
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RENTE_NE.getValue()));
                break;
            }
            case 302 : // textField_26
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONTRIBUABLE.getValue()));
                break;
            }
            case 272 : // parameterDefaultValue_MODEL_PATH
            {
                value = (java.lang.String)("");
                break;
            }
            case 287 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REF_INTERNE.getValue()));
                break;
            }
            case 308 : // textField_32
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_MARIAGE_CONTRIBUABLE.getValue()));
                break;
            }
            case 276 : // variableInitialValue_GRP_1_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 314 : // textField_38
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEXE_CONJOINT.getValue()));
                break;
            }
            case 292 : // textField_16
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_GENREAFFILIE.getValue()));
                break;
            }
            case 280 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_ETRANGER.getValue()));
                break;
            }
            case 327 : // textField_51
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_NE.getValue()));
                break;
            }
            case 347 : // textField_71
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_NE_CJT.getValue()));
                break;
            }
            case 351 : // textField_75
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONJOINT.getValue()));
                break;
            }
            case 318 : // textField_42
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_NAISSANCE.getValue()));
                break;
            }
            case 291 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ANNEE.getValue()));
                break;
            }
            case 271 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 315 : // textField_39
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ETATCIVIL_CONJOINT.getValue()));
                break;
            }
            case 313 : // textField_37
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NSS_CONJOINT.getValue()));
                break;
            }
            case 269 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 330 : // textField_54
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CAPITAL.getValue()));
                break;
            }
            case 332 : // textField_56
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REMARQUE.getValue()));
                break;
            }
            case 295 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REF_EXTERNE.getValue()));
                break;
            }
            case 334 : // textField_58
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_TYPE_REPONSE.getValue()));
                break;
            }
            case 325 : // textField_49
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_IND.getValue()));
                break;
            }
            case 281 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RENTE_PONT.getValue()));
                break;
            }
            case 270 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 278 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_PATRIMOINE_COMMERCIAL.getValue()));
                break;
            }
            case 340 : // textField_64
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SENDER_ID.getValue()));
                break;
            }
            case 284 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RACHAT_LPP.getValue()));
                break;
            }
            case 277 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_PATRIMOINE_COMMERCIAL.getValue()));
                break;
            }
            case 268 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 306 : // textField_30
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ETATCIVIL_CONTRIBUABLE.getValue()));
                break;
            }
            case 299 : // textField_23
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DONNEE_RECAP.getValue()));
                break;
            }
            case 300 : // textField_24
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TYPE_EVALUATION.getValue()));
                break;
            }
            case 319 : // textField_43
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_NAISSANCE_CONTRIBUABLE.getValue()));
                break;
            }
            case 310 : // textField_34
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ENTREE_CONTRIBUABLE.getValue()));
                break;
            }
            case 296 : // textField_20
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATERECEPTION.getValue()));
                break;
            }
            case 286 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_IMP.getValue()));
                break;
            }
            case 322 : // textField_46
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DONNEE_BASE.getValue()));
                break;
            }
            case 328 : // textField_52
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_AGRICOLE.getValue()));
                break;
            }
            case 346 : // textField_70
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_IND_CJT.getValue()));
                break;
            }
            case 303 : // textField_27
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DESC_CONTRIBUABLE.getValue()));
                break;
            }
            case 285 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEDEX_TITRE.getValue()));
                break;
            }
            case 345 : // textField_69
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SALAIRE_CJT.getValue()));
                break;
            }
            case 323 : // textField_47
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SALAIRE.getValue()));
                break;
            }
            case 329 : // textField_53
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_AGRICOLE.getValue()));
                break;
            }
            case 267 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 288 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_ANNEE.getValue()));
                break;
            }
            case 273 : // variable_IMAGE_LOGO
            {
                value = (java.lang.String)(((java.lang.String)parameter_MODEL_PATH.getValue())+"cfc_logo.gif");
                break;
            }
            case 333 : // textField_57
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REMARQUE.getValue()));
                break;
            }
            case 293 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REF_EXTERNE.getValue()));
                break;
            }
            case 331 : // textField_55
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_CAPITAL.getValue()));
                break;
            }
            case 275 : // variable_GRP_1_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 301 : // textField_25
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_GENRE_TAXATION.getValue()));
                break;
            }
            case 342 : // textField_66
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_ETRANGER_CJT.getValue()));
                break;
            }
            case 344 : // textField_68
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RACHAT_LPP_CJT.getValue()));
                break;
            }
            case 336 : // textField_60
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_ASSIETTE.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 304 : // textField_28
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NSS_CONTRIBUABLE.getValue()));
                break;
            }
            case 349 : // textField_73
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_CAPITAL_CJT.getValue()));
                break;
            }
            case 339 : // textField_63
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_ETATCIVIL.getValue()));
                break;
            }
            case 297 : // textField_21
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_TYPE_EVALUATION.getValue()));
                break;
            }
            case 316 : // textField_40
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_MARIAGE_CONJOINT.getValue()));
                break;
            }
            case 321 : // textField_45
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_SALAIRE.getValue()));
                break;
            }
            case 294 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATERECEPTION.getValue()));
                break;
            }
            case 283 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RACHAT_LPP.getValue()));
                break;
            }
            case 298 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_GENRE_TAXATION.getValue()));
                break;
            }
            case 289 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_GENREAFFILIE.getValue()));
                break;
            }
            case 317 : // textField_41
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ENTREE_CONJOINT.getValue()));
                break;
            }
            case 324 : // textField_48
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_IND.getValue()));
                break;
            }
            case 343 : // textField_67
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_PONT_CJT.getValue()));
                break;
            }
            case 279 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_ETRANGER.getValue()));
                break;
            }
            case 320 : // textField_44
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_NAISSANCE_CONJOINT.getValue()));
                break;
            }
            case 307 : // textField_31
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_MARIAGE.getValue()));
                break;
            }
            case 312 : // textField_36
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DESC_CONJOINT.getValue()));
                break;
            }
            case 309 : // textField_33
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_ENTREE.getValue()));
                break;
            }
            case 282 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_PONT.getValue()));
                break;
            }
            case 274 : // group_GRP_1
            {
                value = (java.lang.Object)("ff");
                break;
            }
            case 350 : // textField_74
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONTRIBUABLE.getValue()));
                break;
            }
            case 348 : // textField_72
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_AGRICOLE_CJT.getValue()));
                break;
            }
            case 311 : // textField_35
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONJOINT.getValue()));
                break;
            }
            case 305 : // textField_29
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEXE_CONTRIBUABLE.getValue()));
                break;
            }
            case 265 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 266 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 264 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 341 : // textField_65
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_PATRIMOINE_COMMERCIAL_CJT.getValue()));
                break;
            }
            case 338 : // textField_62
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_SEXE.getValue()));
                break;
            }
            case 337 : // textField_61
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ASSIETTE.getValue()));
                break;
            }
            case 335 : // textField_59
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TYPE_REPONSE.getValue()));
                break;
            }
            case 290 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REF_INTERNE.getValue()));
                break;
            }
            case 326 : // textField_50
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RENTE_NE.getValue()));
                break;
            }
            case 302 : // textField_26
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONTRIBUABLE.getValue()));
                break;
            }
            case 272 : // parameterDefaultValue_MODEL_PATH
            {
                value = (java.lang.String)("");
                break;
            }
            case 287 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REF_INTERNE.getValue()));
                break;
            }
            case 308 : // textField_32
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_MARIAGE_CONTRIBUABLE.getValue()));
                break;
            }
            case 276 : // variableInitialValue_GRP_1_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 314 : // textField_38
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEXE_CONJOINT.getValue()));
                break;
            }
            case 292 : // textField_16
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_GENREAFFILIE.getValue()));
                break;
            }
            case 280 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_ETRANGER.getValue()));
                break;
            }
            case 327 : // textField_51
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_NE.getValue()));
                break;
            }
            case 347 : // textField_71
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_NE_CJT.getValue()));
                break;
            }
            case 351 : // textField_75
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONJOINT.getValue()));
                break;
            }
            case 318 : // textField_42
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_NAISSANCE.getValue()));
                break;
            }
            case 291 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ANNEE.getValue()));
                break;
            }
            case 271 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 315 : // textField_39
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ETATCIVIL_CONJOINT.getValue()));
                break;
            }
            case 313 : // textField_37
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NSS_CONJOINT.getValue()));
                break;
            }
            case 269 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 330 : // textField_54
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CAPITAL.getValue()));
                break;
            }
            case 332 : // textField_56
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REMARQUE.getValue()));
                break;
            }
            case 295 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REF_EXTERNE.getValue()));
                break;
            }
            case 334 : // textField_58
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_TYPE_REPONSE.getValue()));
                break;
            }
            case 325 : // textField_49
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_IND.getValue()));
                break;
            }
            case 281 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RENTE_PONT.getValue()));
                break;
            }
            case 270 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 278 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_PATRIMOINE_COMMERCIAL.getValue()));
                break;
            }
            case 340 : // textField_64
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SENDER_ID.getValue()));
                break;
            }
            case 284 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RACHAT_LPP.getValue()));
                break;
            }
            case 277 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_PATRIMOINE_COMMERCIAL.getValue()));
                break;
            }
            case 268 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 306 : // textField_30
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ETATCIVIL_CONTRIBUABLE.getValue()));
                break;
            }
            case 299 : // textField_23
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DONNEE_RECAP.getValue()));
                break;
            }
            case 300 : // textField_24
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TYPE_EVALUATION.getValue()));
                break;
            }
            case 319 : // textField_43
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_NAISSANCE_CONTRIBUABLE.getValue()));
                break;
            }
            case 310 : // textField_34
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ENTREE_CONTRIBUABLE.getValue()));
                break;
            }
            case 296 : // textField_20
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATERECEPTION.getValue()));
                break;
            }
            case 286 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_IMP.getValue()));
                break;
            }
            case 322 : // textField_46
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DONNEE_BASE.getValue()));
                break;
            }
            case 328 : // textField_52
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_AGRICOLE.getValue()));
                break;
            }
            case 346 : // textField_70
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_IND_CJT.getValue()));
                break;
            }
            case 303 : // textField_27
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DESC_CONTRIBUABLE.getValue()));
                break;
            }
            case 285 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEDEX_TITRE.getValue()));
                break;
            }
            case 345 : // textField_69
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SALAIRE_CJT.getValue()));
                break;
            }
            case 323 : // textField_47
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SALAIRE.getValue()));
                break;
            }
            case 329 : // textField_53
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_AGRICOLE.getValue()));
                break;
            }
            case 267 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 288 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_ANNEE.getValue()));
                break;
            }
            case 273 : // variable_IMAGE_LOGO
            {
                value = (java.lang.String)(((java.lang.String)parameter_MODEL_PATH.getValue())+"cfc_logo.gif");
                break;
            }
            case 333 : // textField_57
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REMARQUE.getValue()));
                break;
            }
            case 293 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REF_EXTERNE.getValue()));
                break;
            }
            case 331 : // textField_55
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_CAPITAL.getValue()));
                break;
            }
            case 275 : // variable_GRP_1_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 301 : // textField_25
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_GENRE_TAXATION.getValue()));
                break;
            }
            case 342 : // textField_66
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_ETRANGER_CJT.getValue()));
                break;
            }
            case 344 : // textField_68
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RACHAT_LPP_CJT.getValue()));
                break;
            }
            case 336 : // textField_60
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_ASSIETTE.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 304 : // textField_28
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NSS_CONTRIBUABLE.getValue()));
                break;
            }
            case 349 : // textField_73
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_CAPITAL_CJT.getValue()));
                break;
            }
            case 339 : // textField_63
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_ETATCIVIL.getValue()));
                break;
            }
            case 297 : // textField_21
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_TYPE_EVALUATION.getValue()));
                break;
            }
            case 316 : // textField_40
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_MARIAGE_CONJOINT.getValue()));
                break;
            }
            case 321 : // textField_45
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_SALAIRE.getValue()));
                break;
            }
            case 294 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATERECEPTION.getValue()));
                break;
            }
            case 283 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RACHAT_LPP.getValue()));
                break;
            }
            case 298 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_GENRE_TAXATION.getValue()));
                break;
            }
            case 289 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_GENREAFFILIE.getValue()));
                break;
            }
            case 317 : // textField_41
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ENTREE_CONJOINT.getValue()));
                break;
            }
            case 324 : // textField_48
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_IND.getValue()));
                break;
            }
            case 343 : // textField_67
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_PONT_CJT.getValue()));
                break;
            }
            case 279 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_ETRANGER.getValue()));
                break;
            }
            case 320 : // textField_44
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_NAISSANCE_CONJOINT.getValue()));
                break;
            }
            case 307 : // textField_31
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_MARIAGE.getValue()));
                break;
            }
            case 312 : // textField_36
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DESC_CONJOINT.getValue()));
                break;
            }
            case 309 : // textField_33
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_ENTREE.getValue()));
                break;
            }
            case 282 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_PONT.getValue()));
                break;
            }
            case 274 : // group_GRP_1
            {
                value = (java.lang.Object)("ff");
                break;
            }
            case 350 : // textField_74
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONTRIBUABLE.getValue()));
                break;
            }
            case 348 : // textField_72
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_AGRICOLE_CJT.getValue()));
                break;
            }
            case 311 : // textField_35
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONJOINT.getValue()));
                break;
            }
            case 305 : // textField_29
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEXE_CONTRIBUABLE.getValue()));
                break;
            }
            case 265 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 266 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 264 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 341 : // textField_65
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_PATRIMOINE_COMMERCIAL_CJT.getValue()));
                break;
            }
            case 338 : // textField_62
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_SEXE.getValue()));
                break;
            }
            case 337 : // textField_61
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ASSIETTE.getValue()));
                break;
            }
            case 335 : // textField_59
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TYPE_REPONSE.getValue()));
                break;
            }
            case 290 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REF_INTERNE.getValue()));
                break;
            }
            case 326 : // textField_50
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RENTE_NE.getValue()));
                break;
            }
            case 302 : // textField_26
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONTRIBUABLE.getValue()));
                break;
            }
            case 272 : // parameterDefaultValue_MODEL_PATH
            {
                value = (java.lang.String)("");
                break;
            }
            case 287 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REF_INTERNE.getValue()));
                break;
            }
            case 308 : // textField_32
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_MARIAGE_CONTRIBUABLE.getValue()));
                break;
            }
            case 276 : // variableInitialValue_GRP_1_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 314 : // textField_38
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEXE_CONJOINT.getValue()));
                break;
            }
            case 292 : // textField_16
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_GENREAFFILIE.getValue()));
                break;
            }
            case 280 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_ETRANGER.getValue()));
                break;
            }
            case 327 : // textField_51
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_NE.getValue()));
                break;
            }
            case 347 : // textField_71
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RENTE_NE_CJT.getValue()));
                break;
            }
            case 351 : // textField_75
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CONJOINT.getValue()));
                break;
            }
            case 318 : // textField_42
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_NAISSANCE.getValue()));
                break;
            }
            case 291 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ANNEE.getValue()));
                break;
            }
            case 271 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 315 : // textField_39
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ETATCIVIL_CONJOINT.getValue()));
                break;
            }
            case 313 : // textField_37
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_NSS_CONJOINT.getValue()));
                break;
            }
            case 269 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 330 : // textField_54
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_CAPITAL.getValue()));
                break;
            }
            case 332 : // textField_56
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REMARQUE.getValue()));
                break;
            }
            case 295 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REF_EXTERNE.getValue()));
                break;
            }
            case 334 : // textField_58
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_TYPE_REPONSE.getValue()));
                break;
            }
            case 325 : // textField_49
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_IND.getValue()));
                break;
            }
            case 281 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_RENTE_PONT.getValue()));
                break;
            }
            case 270 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 278 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_PATRIMOINE_COMMERCIAL.getValue()));
                break;
            }
            case 340 : // textField_64
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SENDER_ID.getValue()));
                break;
            }
            case 284 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RACHAT_LPP.getValue()));
                break;
            }
            case 277 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_PATRIMOINE_COMMERCIAL.getValue()));
                break;
            }
            case 268 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 306 : // textField_30
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_ETATCIVIL_CONTRIBUABLE.getValue()));
                break;
            }
            case 299 : // textField_23
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DONNEE_RECAP.getValue()));
                break;
            }
            case 300 : // textField_24
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_TYPE_EVALUATION.getValue()));
                break;
            }
            case 319 : // textField_43
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_NAISSANCE_CONTRIBUABLE.getValue()));
                break;
            }
            case 310 : // textField_34
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_ENTREE_CONTRIBUABLE.getValue()));
                break;
            }
            case 296 : // textField_20
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATERECEPTION.getValue()));
                break;
            }
            case 286 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DATE_IMP.getValue()));
                break;
            }
            case 322 : // textField_46
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DONNEE_BASE.getValue()));
                break;
            }
            case 328 : // textField_52
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REVENU_AGRICOLE.getValue()));
                break;
            }
            case 346 : // textField_70
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_IND_CJT.getValue()));
                break;
            }
            case 303 : // textField_27
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DESC_CONTRIBUABLE.getValue()));
                break;
            }
            case 285 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SEDEX_TITRE.getValue()));
                break;
            }
            case 345 : // textField_69
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SALAIRE_CJT.getValue()));
                break;
            }
            case 323 : // textField_47
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SALAIRE.getValue()));
                break;
            }
            case 329 : // textField_53
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_AGRICOLE.getValue()));
                break;
            }
            case 267 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 288 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_ANNEE.getValue()));
                break;
            }
            case 273 : // variable_IMAGE_LOGO
            {
                value = (java.lang.String)(((java.lang.String)parameter_MODEL_PATH.getValue())+"cfc_logo.gif");
                break;
            }
            case 333 : // textField_57
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REMARQUE.getValue()));
                break;
            }
            case 293 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_REF_EXTERNE.getValue()));
                break;
            }
            case 331 : // textField_55
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_CAPITAL.getValue()));
                break;
            }
            case 275 : // variable_GRP_1_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 301 : // textField_25
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_GENRE_TAXATION.getValue()));
                break;
            }
            case 342 : // textField_66
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_REVENU_ETRANGER_CJT.getValue()));
                break;
            }
            case 344 : // textField_68
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_RACHAT_LPP_CJT.getValue()));
                break;
            }
            case 336 : // textField_60
            {
                value = (java.lang.String)(((java.lang.String)parameter_L_DATE_ASSIETTE.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
