package ch.globaz.pegasus.business.constantes;

public interface IPCValeursPlanCalcul {

    String CLE_DEPEN_BES_VITA_TOTAL = "64039071";
    String CLE_DEPEN_COT_PSAL_TOTAL = "64039088";
    String CLE_DEPEN_FRAIS_GARDE_TOTAL = "64039179";
    String CLE_DEPEN_PRIME_ASSURANCE_MALADIE_TOTAL= "64039180";

    String CLE_DEPEN_DEP_RECO_SOUS_TOTAL = "64039127";
    String CLE_DEPEN_DEP_RECO_TOTAL = "64039098";
    String CLE_DEPEN_DEPPERSO_TOTAL = "64039097";
    String CLE_DEPEN_FRAISIMM_FRAIS_ENTRETIEN_IMMEUBLE = "64039086";
    String CLE_DEPEN_FRAISIMM_INTERET_HYPOTHECAIRE = "64039085";
    String CLE_DEPEN_FRAISIMM_REVENU = "64039106";
    String CLE_DEPEN_FRAISIMM_TOTAL = "64039095";
    String CLE_DEPEN_FRAISIMM_TOTAL_PLAFONNE = "64039147";
    String CLE_DEPEN_GR_LOYER_ACCOMPTE_CHARGES = "64039077";
    String CLE_DEPEN_GR_LOYER_CHARGES_FORFAITAIRES = "64039079";
    String CLE_DEPEN_GR_LOYER_DROIT_HABITATION = "64039082";
    String CLE_DEPEN_GR_LOYER_FRAIS_CHAUFFAGE = "64039083";
    String CLE_DEPEN_GR_LOYER_LOYER_BRUT = "64039075";
    String CLE_DEPEN_GR_LOYER_LOYER_NET = "64039076";

    String CLE_INTER_FRAIS_COMPTEBANCAIRECPP = "FRAIS_COMPTE_BANCAIRE_CPP";
    String CLE_INTER_INTERETS_COMPTEBANCAIRECPP = "INTERETS_COMPTE_BANCAIRE_CPP";
    String CLE_INTER_BIEN_IMMOBILIER_HABITATION_PRINCIPALE_MOINS_DE_10_ANS = "BIEN_IMMOBILIER_HABITATION_PRINCIPALE_MOINS_DE_10_ANS";
    String CLE_INTER_BIEN_IMMOBILIER_HABITATION_PRINCIPALE_PLUS_DE_20_ANS = "BIEN_IMMOBILIER_HABITATION_PRINCIPALE_PLUS_DE_20_ANS";
    String CLE_INTER_BIEN_IMMOBILIER_HABITATION_ANNEXE_PLUS_DE_20_ANS = "BIEN_IMMOBILIER_HABITATION_ANNEXE_PLUS_DE_20_ANS";
    String CLE_INTER_BIEN_IMMOBILIER_COMMERCIALE_PRINCIPALE = "BIEN_IMMOBILIER_COMMERCIALE_PRINCIPALE";
    String CLE_INTER_BIEN_IMMOBILIER_COMMERCIALE_ANNEXE = "BIEN_IMMOBILIER_COMMERCIALE_ANNEXE";
    String CLE_INTER_LOYER_ENCAISSE_PRINCIPAL_PLAFOND = "BIEN_IMMOBILIER_LOYER_ENCAISSE_PRINCIPAL_PLAFOND";
    String CLE_INTER_LOYER_ENCAISSE_ANNEXE_PLAFOND = "BIEN_IMMOBILIER_LOYER_ENCAISSE_ANNEXE_PLAFOND";

    String CLE_DEPEN_GR_LOYER_PLAFOND = "64039138";
    String CLE_DEPEN_GR_LOYER_PLAFOND_FEDERAL = "64039157";
    String CLE_DEPEN_GR_LOYER_DIFF_PART_CANTONALE = "DIFF_PART_CANTONALE";
    String CLE_DEPEN_GR_LOYER_PART_CANTONALE = "PART_CANTONALE";
    String CLE_DEPEN_GR_LOYER_TAXES_PENSION_NON_RECONNUE = "64039080";
    String CLE_DEPEN_GR_LOYER_TAXES_PENSION_RECONNUE = "64039137";
    String CLE_DEPEN_GR_LOYER_FRAIS_LONGUE_DUREE = "64039151";

    String CLE_DEPEN_GR_LOYER_TOTAL = "64039096";
    String CLE_DEPEN_GR_LOYER_TOTAL_NON_PLAFONNE = "64039139";
    String CLE_DEPEN_GR_LOYER_VALEUR_LOCATIVE_APP_HABITE = "64039081";
    String CLE_DEPEN_PENSVERS_TOTAL = "64039087";
    String CLE_DEPEN_TAXEHOME_TOTAL = "64039073";
    String CLE_FORTU_AUT_DETT_TOTAL = "64039022";
    String CLE_FORTU_DED_LEGA_TOTAL = "64039023";
    String CLE_FORTU_DETE_HYP_TOTAL = "64039021";

    String CLE_FORTU_DETE_HYP_REAL_PROPERTY = "64039182";
    String CLE_FORTU_DETE_HYP_SELF_INHABITED = "64039183";
    String CLE_FORTU_DETE_HYP_NOT_HABITED = "64039188";

    String CLE_FORTU_DETE_HYP_ANNEXE_PLAFONNEE = "CLE_FORTU_DETE_HYP_ANNEXE_PLAFONNEE";
    String CLE_FORTU_DETE_HYP_PRINCIPAL_PLAFONNEE = "CLE_FORTU_DETE_HYP_PRINCIPAL_PLAFONNEE";
    String CLE_FORTU_DETE_HYP_NON_HABITABLE_PLAFONNEE = "CLE_FORTU_DETE_HYP_NON_HABITABLE_PLAFONNEE";

    String CLE_FAMILY_SIZE = "64039184";

    String CLE_FORTU_FOR_DESS_TOTAL = "64039016";
    String CLE_FORTU_FOR_IMMO_BIENS_IMMO_HABIT_PRINCIPALE = "64039017";
    String CLE_FORTU_FOR_IMMO_BIENS_NON_HABIT_PRINCIPALE = "64039019";
    String CLE_FORTU_FOR_IMMO_BIENS_NON_HABITABLES = "64039020";
    String CLE_FORTU_FOR_IMMO_BIENS_PRINCIPAL_DEDUIT = "64039122";
    String CLE_FORTU_FOR_IMMO_DEDUCTION_FOFAITAIRE = "64039018";
    String CLE_FORTU_FOR_IMMO_TOTAL = "64039102";
    String CLE_FORTU_FOR_MOBI_ASSURANCE_RENTE_VIAGERE = "64039012";
    String CLE_FORTU_FOR_MOBI_ASSURANCE_VIE = "64039011";
    String CLE_FORTU_FOR_MOBI_AUTRE = "64039006";
    String CLE_FORTU_FOR_MOBI_BETAIL = "64039014";
    String CLE_FORTU_FOR_MOBI_BIJOUX = "64039003";
    String CLE_FORTU_FOR_MOBI_CAPITAL_LPP = "64039010";
    String CLE_FORTU_FOR_MOBI_COMPTE_BANCAIRE = "64039007";
    String CLE_FORTU_FOR_MOBI_MARCHANDISES_STOCK = "64039013";
    String CLE_FORTU_FOR_MOBI_METAUX_PRECIEUX = "64039004";
    String CLE_FORTU_FOR_MOBI_NUMERAIRES = "64039001";
    String CLE_FORTU_FOR_MOBI_PRET_ENVERS_TIERS = "64039009";
    String CLE_FORTU_FOR_MOBI_TABLEAUX = "64039002";
    String CLE_FORTU_FOR_MOBI_TIMBRES = "64039005";
    String CLE_FORTU_FOR_MOBI_TITRES = "64039008";
    String CLE_FORTU_FOR_MOBI_TOTAL = "64039103";
    String CLE_FORTU_FOR_MOBI_VEHICULES = "64039015";
    String CLE_FORTU_SOUS_TOTAL = "64039148";
    String CLE_FORTU_TOTALNET_TOTAL = "64039024";

    String CLE_IS_DIVESTED_WEALTH = "64039185";
    String CLE_TYPE_DIVESTED_WEALTH = "64039186";

    String CLE_INTER_BISHP_ROLE_PROPRIETAIRE = "BISHP_ROLE_PROPRIETAIRE";
    String CLE_INTER_DATE_ENTREE_HOME = "DATE_ENTREE_HOME";
    String CLE_INTER_DEPENSE_CS_TYPE_CHAMBRE = "TAXE_JOURNALIERE_CS_TYPE_CHAMBRE";
    String CLE_INTER_DEPENSE_CS_TYPE_ARGENT_DE_POCHE_TYPE_CHAMBRE = "ARGENT_DE_POCHE_CS_TYPE_CHAMBRE";
    String CLE_INTER_FORTUNE_DESSAISIE_DATE = "FORTUNE_DESSAISIE_DATE";
    String CLE_INTER_FORTUNE_DESSAISIE_MONTANT = "FORTUNE_DESSAISIE_MONTANT";
    String CLE_INTER_FORTUNES_DESSAISIES = "FORTUNES_DESSAISIES";
    String CLE_INTER_FORTUNE_IMMOBILIER_TOTAL_PRINCIPAL = "FORTUNE_IMMOBILIER_TOTAL_PRINCIPAL";
    String CLE_INTER_FORTUNE_IMMOBILIER_TOTAL_SECONDAIRE = "FORTUNE_IMMOBILIER_TOTAL_SECONDAIRE";
    String CLE_INTER_FORTUNE_IMMOBILIER_TOTAL_NON_HABITABLE= "FORTUNE_IMMOBILIER_TOTAL_NON_HABITABLE";
    String CLE_INTER_HABITATION_PRINCIPAL_TYPE_PROPRIETE = "HABITATION_PRINCIPAL_TYPE_PROPRIETE";
    String CLE_INTER_HABITATION_PRINCIPALE = "HABITATION_PRINCIPALE";
    String CLE_INTER_HABITATION_PRINCIPALE_NBPERSONNES = "HABITATION_PRINCIPALE_NBPERSONNES";
    String CLE_INTER_ID_HOME = "ID_HOME";
    String CLE_INTER_IS_ENTREE_HOME = "IS_ENTREE_HOME";
    String CLE_INTER_IS_FORFAIT_REVENU_NATURE_TENUE_MENAGE = "IS_FORFAIT_REVENU_NATURE_TENUE_MENAGE";
    String CLE_INTER_LOYER_FORFAIT = "LOYER_FORFAIT";
    String CLE_INTER_LOYER_IS_FAUTEUIL_ROULANT = "LOYER_IS_FAUTEUIL_ROULANT";
    String CLE_INTER_LOYER_MONTANT_BRUT = "LOYER_MONTANT_BRUT";
    String CLE_INTER_LOYER_MONTANT_NET = "LOYER_MONTANT_NET";
    String CLE_INTER_LOYER_NB_PERSONNES = "LOYER_NB_PERSONNES";
    String CLE_INTER_LOYER_PROPRIETAIRE = "LOYER_PROPRIETAIRE";

    String CLE_INTER_LOYER_ROLE_PROPRIETAIRE = "LOYER_ROLE_PROPRIETAIRE";
    String CLE_INTER_LOYER_SOUS_LOCATIONS_CALCULE = "CLE_SOUS_LOCATION_CALCULE";
    String CLE_INTER_LOYER_TAXE_JOURNALIERE_PENSION_NON_RECONNUE = "LOYER_TAXE_JOURNALIERE_PENSION_NON_RECONNUE";
    String CLE_INTER_LOYER_CS_DEPLAFONNEMENT_APPARTEMENT_PARTAGE = "LOYER_CS_DEPLAFONNEMENT_APPARTEMENT_PARTAGE";
    String CLE_INTER_LOYERS = "LOYERS";
    String CLE_INTER_LOYERS_ID = "LOYER_ID_";
    String CLE_INTER_NB_RENTES_PRINCIPALES_COUPLE_A_DOM = "NB_RENTES_PRINCIPALES_COUPLE_A_DOM";
    String CLE_INTER_NOMBRE_CHAMBRES = "NOMBRE_CHAMBRES";
    String CLE_INTER_TYPE_RENTE_CONJOINT = "TYPE_RENTE_CONJOINT";
    String CLE_INTER_TYPE_RENTE_ENFANT = "TYPE_RENTE_ENFANT";

    String CLE_INTER_TYPE_RENTE_REQUERANT = "TYPE_RENTE_REQUERANT";
    String CLE_IS_API_ENCODE = "IS_API_ENCODE"; // Stetction si une api a été saisi
    String CLE_REVEN_ACT_LUCR_ACTIVITE_DEPENDANTE = "64039036";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_DEPENDANTE_CONJOINT = "64039159";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_DEPENDANTE_ENFANT = "64039169";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_INDEPENDANTE = "64039037";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_INDEPENDANTE_CONJOINT = "64039160";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_INDEPENDANTE_ENFANT = "64039170";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_INDEPENDANTE_AGRICOLE = "64039072";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_INDEPENDANTE_AGRICOLE_CONJOINT = "64039161";
    String CLE_REVEN_ACT_LUCR_ACTIVITE_INDEPENDANTE_AGRICOLE_ENFANT = "64039171";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_FORFAITAIRE_REVENU = "64039042";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_LPP = "64039040";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_LPP_CONJOINT = "64039163";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_LPP_ENFANT = "64039172";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_SOCIALES = "64039039";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_SOCIALES_CONJOINT = "64039164";
    String CLE_REVEN_ACT_LUCR_DEDUCTION_SOCIALES_ENFANT = "64039173";
    String CLE_REVEN_ACT_LUCR_FRAIS_OBTENTION_REVENU = "64039041";
    String CLE_REVEN_ACT_LUCR_FRAIS_OBTENTION_REVENU_CONJOINT = "64039165";
    String CLE_REVEN_ACT_LUCR_FRAIS_OBTENTION_REVENU_ENFANT = "64039174";
    String CLE_REVEN_ACT_LUCR_REVENU_HYPOTHETIQUE = "64039038";
    String CLE_REVEN_ACT_LUCR_REVENU_HYPOTHETIQUE_CONJOINT = "64039162";
    String CLE_REVEN_ACT_LUCR_REVENU_HYPOTHETIQUE_ENFANT = "64039175";
    String CLE_REVEN_ACT_LUCR_REVENU_PRIVILEGIE = "64039043";
    String CLE_REVEN_ACT_LUCR_REVENU_PRIVILEGIE_CONJOINT = "64039166";
    String CLE_REVEN_ACT_LUCR_REVENU_PRIVILEGIE_ENFANT = "64039176";
    String CLE_REVEN_ACT_LUCR_REVENU_PRIS_EN_COMPTE = "64039155";
    String CLE_REVEN_ACT_LUCR_REVENU_PRIS_EN_COMPTE_CONJOINT = "64039167";
    String CLE_REVEN_ACT_LUCR_REVENU_PRIS_EN_COMPTE_ENFANT = "64039177";
    String CLE_REVEN_ACT_LUCR_TOTAL = "64039112";
    String CLE_REVEN_ACT_LUCR_TOTAL_CONJOINT = "64039168";
    String CLE_REVEN_ACT_LUCR_TOTAL_ENFANT = "64039178";
    String CLE_REVEN_ACT_LUCR_TOTAL_NON_PLAFFONNE = "64039070";

    String CLE_REVEN_ALLOCAPI_AUTRE_API = "64039056";
    String CLE_REVEN_ALLOCAPI_AVS_AI = "64039053";
    String CLE_REVEN_ALLOCAPI_LAA = "64039054";
    String CLE_REVEN_ALLOCAPI_LAM = "64039055";
    String CLE_REVEN_ALLOCAPI_TOTAL = "64039113";
    String CLE_REVEN_AUTREREV_ALLOCATIONS_FAMILLIALES = "64039065";
    String CLE_REVEN_AUTREREV_APG = "64039062";
    String CLE_REVEN_AUTREREV_AUTRE_IJ = "64039063";
    String CLE_REVEN_AUTREREV_AUTRE_REVENUS = "64039068";
    String CLE_REVEN_AUTREREV_CONTRAT_ENTRETIEN_VIAGER = "64039067";
    String CLE_REVEN_AUTREREV_IJ_CHOMAGE = "64039058";
    String CLE_REVEN_AUTREREV_IJ_LAA = "64039059";
    String CLE_REVEN_AUTREREV_IJ_LAM = "64039060";
    String CLE_REVEN_AUTREREV_IJ_LAMAL = "64039061";
    String CLE_REVEN_AUTREREV_IJ_LCA = "64039064";
    String CLE_REVEN_AUTREREV_IJAI = "64039057";
    String CLE_REVEN_AUTREREV_PENSION_ALIM_RECUE = "64039066";
    String CLE_REVEN_AUTREREV_TOTAL = "64039114";
    String CLE_REVEN_DESS_REV_TOTAL = "64039069";
    String CLE_REVEN_IMP_FORT_TOTAL = "64039093";
    String CLE_REVEN_INTDESFO_TOTAL = "64039030";
    String CLE_REVEN_INTFORMO_INTERETS_CAPITAL_LPP = "64039029";
    String CLE_REVEN_INTFORMO_INTERETS_COMPTES_BANCAIRE = "64039026";
    String CLE_REVEN_INTFORMO_INTERETS_NUMERAIRES = "64039025";
    String CLE_REVEN_INTFORMO_INTERETS_PRETS = "64039028";
    String CLE_REVEN_INTFORMO_RENDEMENT_TITRES = "64039027";
    String CLE_REVEN_INTFORMO_TOTAL = "64039118";
    String CLE_REVEN_LOYER_SOUS_LOCATION_NET = "64039089";
    String CLE_REVEN_RENAUTRE_AUTRE_RENTE = "64039052";
    String CLE_REVEN_RENAUTRE_RENTE_3EME_PILLIER = "64039049";
    String CLE_REVEN_RENAUTRE_RENTE_ASSURANCE_PRIVEE = "64039048";
    String CLE_REVEN_RENAUTRE_RENTE_ASSURANCE_RENTE_VIAGERE = "64039051";
    String CLE_REVEN_RENAUTRE_RENTE_ETRANGERE = "64039047";
    String CLE_REVEN_RENAUTRE_RENTE_ETRANGERE_TAUX_CHANGE = "64039154";
    String CLE_REVEN_RENAUTRE_RENTE_LAA = "64039045";
    String CLE_REVEN_RENAUTRE_RENTE_LAM = "64039050";
    String CLE_REVEN_RENAUTRE_RENTE_LPP = "64039046";
    String CLE_REVEN_RENAUTRE_TOTAL = "64039115";
    String CLE_REVEN_RENAVSAI_TOTAL = "64039044";
    String CLE_REVEN_RENFORMO_BIENS_IMMO_NON_HABITABLES = "64039035";
    String CLE_REVEN_RENFORMO_DROIT_HABITATION = "64039032";
    String CLE_REVEN_RENFORMO_REVENUS_LOCATIONS = "64039033";
    String CLE_REVEN_RENFORMO_REVENUS_SOUS_LOCATIONS = "64039034";
    String CLE_REVEN_RENFORMO_TOTAL = "64039117";
    String CLE_REVEN_RENFORMO_VALEUR_LOCATIVE = "64039031";
    String CLE_REVEN_REV_DETE_TOTAL = "64039116";
    String CLE_REVEN_REV_SOUS_TOTAL_RECONNU = "64039126";
    String CLE_REVEN_SUBSIDE_ASSURANCE_MALADIE_TOTAL= "64039181";

    String CLE_TOTAL_CC = "64039120";
    String CLE_TOTAL_CC_DEDUIT = "64039123";
    String CLE_TOTAL_CC_DEDUIT_MENSUEL = "64039124";
    String CLE_TOTAL_CC_MENSUEL_CALCULE_FEDERAL = "64039152";
    String CLE_TOTAL_CC_MENSUEL_MINIMAL_APPLIQUE_FEDERAL = "64039153";
    String CLE_TOTAL_CC_STATUS = "64039144";
    String CLE_TOTAL_CC_STATUS_FEDERAL = "64039156";
    String CLE_TOTAL_DEDUIT_MENSUEL_CONJOINT = "64039142";
    String CLE_TOTAL_DEDUIT_MENSUEL_REQ = "64039141";
    String CLE_TOTAL_PRIMEMAL_REQUERANT = "64039146";
    String CLE_TOTAL_PRIMEMAL_TOTAL = "64039125";
    String CLE_TOTAL_REVENUS_COMMUN = "64039149";

    String CLE_TOTAL_REVENUS_COMMUN_POUR_MOITIE = "64039150";
    String CLE_TOTAL_TYPE_SEPARATION_CC = "64039145";
    String STATUS_CALCUL_DOM2_PRINCIPALE = "64062001";
    String STATUS_CALCUL_SANS_SEPARATION = "64062002";
    String STATUS_CALCUL_SEPARE_MALADIE = "64062003";
    String STATUS_OCTROI = "64061001";
    String STATUS_OCTROI_PARTIEL = "64061002";
    String STATUS_REFUS = "64061003";
    String PERSONNE_EN_COURS_ISREQUERANT = "PERSONNE_EN_COURS_ISREQUERANT";

    String CLE_FORTU_TOTALNET_TOTAL_PART = "64039158";
    String CLE_FORTU_TOTALNET_TOTAL_AVANT_FRACTION = "CLE_FORTU_TOTALNET_TOTAL_AVANT_FRACTION";
    String CLE_REFUS_SEUIL_FORTUNE = "REFUS_SEUIL_FORTUNE";
    String PERSONNE_EN_COURS = "PERSONNE_EN_COURS";
    String PERSONNE_EN_COURS_ISHOME = "PERSONNE_EN_COURS_ISHOME";

    String LOCALITE_LOYER = "LOCALITE_LOYER";
    String PLAFOND_LOYER_LOCALITE = "PLAFOND_LOYER_LOCALITE";
    String PLAFOND_LOYER_NBTOTALFAMILLE = "PLAFOND_LOYER_NBTOTALFAMILLE";
    String PLAFOND_LOYER_DATEDEBUT = "PLAFOND_LOYER_DATEDEBUT";
    String PLAFOND_LOYER_ZONE = "PLAFOND_LOYER_ZONE";

    // nouveaux champs réformes
    String PC_MINIMALE = "PC_MINIMALE";
    String MONTANT_VERSE_CAISSE_MALADIE = "MONTANT_VERSE_CAISSE_MALADIE";

    String CLE_DEPEN_SEJOUR_MOIS_PARTIEL_TOTAL = "64039187";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL = "INTER_SEJOUR_MOIS_PARTIEL";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_PRIX_JOURNALIER = "INTER_SEJOUR_MOIS_PARTIEL_PRIX_JOURNALIER";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_FRAIS_NOURRITURE = "INTER_SEJOUR_MOIS_PARTIEL_FRAIS_NOURRITURE";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_NOMBRE_JOURS = "INTER_SEJOUR_MOIS_PARTIEL_NOMBRE_JOURS";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_NOMBRE_JOURS_REQUERANT = "INTER_SEJOUR_MOIS_PARTIEL_NOMBRE_JOURS_REQUERANT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_NOMBRE_JOURS_CONJOINT = "INTER_SEJOUR_MOIS_PARTIEL_NOMBRE_JOURS_CONJOINT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_VERSEMENT_DIRECT = "INTER_SEJOUR_MOIS_PARTIEL_VERSEMENT_DIRECT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_HOME = "INTER_SEJOUR_MOIS_PARTIEL_HOME";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_HOME_REQUERANT = "INTER_SEJOUR_MOIS_PARTIEL_HOME_REQUERANT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_HOME_CONJOINT = "INTER_SEJOUR_MOIS_PARTIEL_HOME_CONJOINT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_MONTANT_REQUERANT = "INTER_SEJOUR_MOIS_PARTIEL_MONTANT_REQUERANT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_MONTANT_CONJOINT = "INTER_SEJOUR_MOIS_PARTIEL_MONTANT_CONJOINT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_VERSEMENT_DIRECT_CONJOINT = "INTER_SEJOUR_MOIS_PARTIEL_VERSEMENT_DIRECT_CONJOINT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_VERSEMENT_DIRECT_REQUERANT = "INTER_SEJOUR_MOIS_PARTIEL_VERSEMENT_DIRECT_REQUERANT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_IDTIER_REQUERANT = "INTER_SEJOUR_MOIS_PARTIEL_IDTIER_REQUERANT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_IDTIER_CONJOINT = "INTER_SEJOUR_MOIS_PARTIEL_IDTIER_CONJOINT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_DATE_DEBUT = "INTER_SEJOUR_MOIS_PARTIEL_DATE_DEBUT";
    String CLE_INTER_SEJOUR_MOIS_PARTIEL_DATE_FIN = "INTER_SEJOUR_MOIS_PARTIEL_DATE_FIN";

}

