//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DJE10Beschreibung_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DJE10Beschreibung_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DurchschnittlichesJahreseinkommen" type="{http://www.zas.admin.ch/RC}BetragFR_Type"/>
 *         &lt;element name="BeitragsdauerDurchschnittlichesJahreseinkommen" type="{http://www.zas.admin.ch/RC}BeitragsdauerDurchschnittlichesJahreseinkommen_Type"/>
 *         &lt;element name="GesplitteteEinkommen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DJE10Beschreibung_Type", propOrder = { "durchschnittlichesJahreseinkommen",
        "beitragsdauerDurchschnittlichesJahreseinkommen", "gesplitteteEinkommen" })
public class DJE10BeschreibungType {

    @XmlElement(name = "DurchschnittlichesJahreseinkommen", required = true)
    protected BigDecimal durchschnittlichesJahreseinkommen;
    @XmlElement(name = "BeitragsdauerDurchschnittlichesJahreseinkommen", required = true)
    protected BigDecimal beitragsdauerDurchschnittlichesJahreseinkommen;
    @XmlElement(name = "GesplitteteEinkommen")
    protected boolean gesplitteteEinkommen;

    /**
     * Gets the value of the durchschnittlichesJahreseinkommen property.
     * 
     * @return
     *         possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getDurchschnittlichesJahreseinkommen() {
        return durchschnittlichesJahreseinkommen;
    }

    /**
     * Sets the value of the durchschnittlichesJahreseinkommen property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setDurchschnittlichesJahreseinkommen(BigDecimal value) {
        durchschnittlichesJahreseinkommen = value;
    }

    /**
     * Gets the value of the beitragsdauerDurchschnittlichesJahreseinkommen property.
     * 
     * @return
     *         possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getBeitragsdauerDurchschnittlichesJahreseinkommen() {
        return beitragsdauerDurchschnittlichesJahreseinkommen;
    }

    /**
     * Sets the value of the beitragsdauerDurchschnittlichesJahreseinkommen property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setBeitragsdauerDurchschnittlichesJahreseinkommen(BigDecimal value) {
        beitragsdauerDurchschnittlichesJahreseinkommen = value;
    }

    /**
     * Gets the value of the gesplitteteEinkommen property.
     * 
     */
    public boolean isGesplitteteEinkommen() {
        return gesplitteteEinkommen;
    }

    /**
     * Sets the value of the gesplitteteEinkommen property.
     * 
     */
    public void setGesplitteteEinkommen(boolean value) {
        gesplitteteEinkommen = value;
    }

}
