//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * 
 * Meldung der IV-Taggelder an die ZAS. Code Anwendungsgebiet 8G
 * 
 * 
 * <p>
 * Java class for IVTaggelderMeldung_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IVTaggelderMeldung_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KasseZweigstelle" type="{http://www.zas.admin.ch/RC}IrgendeineZweigstelle_weakType"/>
 *         &lt;element name="BuchungsmonatJahr" type="{http://www.zas.admin.ch/RC}AHVDatumJM_Type" minOccurs="0"/>
 *         &lt;element name="MeldungsInhalt" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Taggeldart" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type" minOccurs="0"/>
 *         &lt;element name="VNrEhepartner" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type" minOccurs="0"/>
 *         &lt;element name="Zivilstand" type="{http://www.zas.admin.ch/RC}ZivilstandIVTaggelder5Rev_Type" minOccurs="0"/>
 *         &lt;element name="AnzahlKinder" type="{http://www.zas.admin.ch/RC}AnzahlKinder_Type" minOccurs="0"/>
 *         &lt;element name="MassgebendesTageseinkommen" type="{http://www.zas.admin.ch/RC}BetragFRRP4_Type" minOccurs="0"/>
 *         &lt;element name="ZustaendigeIVStelle" type="{http://www.zas.admin.ch/RC}IVStelle_strongType" minOccurs="0"/>
 *         &lt;element name="Eingliederungsart" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="8"/>
 *               &lt;enumeration value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UVGarantie" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="GekuerztesTaggeld" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Besitzstand4IVRevision" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NrVerfuegung" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ZustaendigeIVStelle" type="{http://www.zas.admin.ch/RC}IVStelle_strongType"/>
 *                   &lt;element name="ElfstelligeNrVerfuegung" type="{http://www.zas.admin.ch/RC}VerfuegungNummer_Type"/>
 *                   &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ErsteTaggeldPeriode" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AbzugVerpflegungUnterkunft" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="AnzahlTage" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
 *                   &lt;element name="Tagesansatz" type="{http://www.zas.admin.ch/RC}BetragFRRP3_Type" minOccurs="0"/>
 *                   &lt;element name="AnzahlTageEingliederungsunterbruchMitTaggeld" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
 *                   &lt;element name="GrundDerUnterbrechung" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="9"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AuszahlungTaggeld" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IVTaggeldTotal" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
 *                   &lt;element name="VorzeichenCode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="PeriodeBeginn" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
 *                   &lt;element name="PeriodeEnde" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
 *                   &lt;element name="AnspruchKindergeld" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="Besitzstand5IVRevision" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TaggeldPeriode" maxOccurs="2" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AbzugVerpflegungUnterkunft" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="AnzahlTage" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
 *                   &lt;element name="Tagesansatz" type="{http://www.zas.admin.ch/RC}BetragFRRP3_Type" minOccurs="0"/>
 *                   &lt;element name="AnzahlTageEingliederungsunterbruchMitTaggeld" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
 *                   &lt;element name="GrundDerUnterbrechung" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="9"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AuszahlungTaggeld" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IVTaggeldTotal" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
 *                   &lt;element name="VorzeichenCode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="PeriodeBeginn" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
 *                   &lt;element name="PeriodeEnde" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
 *                   &lt;element name="AnspruchKindergeld" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="Besitzstand5IVRevision" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="BetragEntschaedigungBetreuungskosten" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
 *                   &lt;element name="BetragEinarbeitungszuschuss" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IVTaggelderMeldung_Type", propOrder = { "kasseZweigstelle", "buchungsmonatJahr", "meldungsInhalt",
        "taggeldart", "versichertennummer", "vNrEhepartner", "zivilstand", "anzahlKinder",
        "massgebendesTageseinkommen", "zustaendigeIVStelle", "eingliederungsart", "uvGarantie", "gekuerztesTaggeld",
        "besitzstand4IVRevision", "nrVerfuegung", "ersteTaggeldPeriode", "taggeldPeriode" })
public class IVTaggelderMeldungType {

    @XmlElement(name = "KasseZweigstelle", required = true)
    protected String kasseZweigstelle;
    @XmlElement(name = "BuchungsmonatJahr")
    protected XMLGregorianCalendar buchungsmonatJahr;
    @XmlElement(name = "MeldungsInhalt")
    protected String meldungsInhalt;
    @XmlElement(name = "Taggeldart")
    protected String taggeldart;
    @XmlElement(name = "Versichertennummer")
    protected String versichertennummer;
    @XmlElement(name = "VNrEhepartner")
    protected String vNrEhepartner;
    @XmlElement(name = "Zivilstand")
    protected Short zivilstand;
    @XmlElement(name = "AnzahlKinder")
    protected Short anzahlKinder;
    @XmlElement(name = "MassgebendesTageseinkommen")
    protected BigDecimal massgebendesTageseinkommen;
    @XmlElement(name = "ZustaendigeIVStelle")
    protected Integer zustaendigeIVStelle;
    @XmlElement(name = "Eingliederungsart")
    protected Short eingliederungsart;
    @XmlElement(name = "UVGarantie")
    protected Boolean uvGarantie;
    @XmlElement(name = "GekuerztesTaggeld")
    protected Boolean gekuerztesTaggeld;
    @XmlElement(name = "Besitzstand4IVRevision")
    protected Boolean besitzstand4IVRevision;
    @XmlElement(name = "NrVerfuegung")
    protected IVTaggelderMeldungType.NrVerfuegung nrVerfuegung;
    @XmlElement(name = "ErsteTaggeldPeriode")
    protected IVTaggelderMeldungType.ErsteTaggeldPeriode ersteTaggeldPeriode;
    @XmlElement(name = "TaggeldPeriode")
    protected List<IVTaggelderMeldungType.TaggeldPeriode> taggeldPeriode;

    /**
     * Gets the value of the kasseZweigstelle property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getKasseZweigstelle() {
        return kasseZweigstelle;
    }

    /**
     * Sets the value of the kasseZweigstelle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKasseZweigstelle(String value) {
        kasseZweigstelle = value;
    }

    /**
     * Gets the value of the buchungsmonatJahr property.
     * 
     * @return
     *         possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getBuchungsmonatJahr() {
        return buchungsmonatJahr;
    }

    /**
     * Sets the value of the buchungsmonatJahr property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setBuchungsmonatJahr(XMLGregorianCalendar value) {
        buchungsmonatJahr = value;
    }

    /**
     * Gets the value of the meldungsInhalt property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getMeldungsInhalt() {
        return meldungsInhalt;
    }

    /**
     * Sets the value of the meldungsInhalt property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMeldungsInhalt(String value) {
        meldungsInhalt = value;
    }

    /**
     * Gets the value of the taggeldart property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getTaggeldart() {
        return taggeldart;
    }

    /**
     * Sets the value of the taggeldart property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaggeldart(String value) {
        taggeldart = value;
    }

    /**
     * Gets the value of the versichertennummer property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getVersichertennummer() {
        return versichertennummer;
    }

    /**
     * Sets the value of the versichertennummer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersichertennummer(String value) {
        versichertennummer = value;
    }

    /**
     * Gets the value of the vNrEhepartner property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getVNrEhepartner() {
        return vNrEhepartner;
    }

    /**
     * Sets the value of the vNrEhepartner property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVNrEhepartner(String value) {
        vNrEhepartner = value;
    }

    /**
     * Gets the value of the zivilstand property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getZivilstand() {
        return zivilstand;
    }

    /**
     * Sets the value of the zivilstand property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setZivilstand(Short value) {
        zivilstand = value;
    }

    /**
     * Gets the value of the anzahlKinder property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getAnzahlKinder() {
        return anzahlKinder;
    }

    /**
     * Sets the value of the anzahlKinder property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setAnzahlKinder(Short value) {
        anzahlKinder = value;
    }

    /**
     * Gets the value of the massgebendesTageseinkommen property.
     * 
     * @return
     *         possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMassgebendesTageseinkommen() {
        return massgebendesTageseinkommen;
    }

    /**
     * Sets the value of the massgebendesTageseinkommen property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMassgebendesTageseinkommen(BigDecimal value) {
        massgebendesTageseinkommen = value;
    }

    /**
     * Gets the value of the zustaendigeIVStelle property.
     * 
     * @return
     *         possible object is {@link Integer }
     * 
     */
    public Integer getZustaendigeIVStelle() {
        return zustaendigeIVStelle;
    }

    /**
     * Sets the value of the zustaendigeIVStelle property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setZustaendigeIVStelle(Integer value) {
        zustaendigeIVStelle = value;
    }

    /**
     * Gets the value of the eingliederungsart property.
     * 
     * @return
     *         possible object is {@link Short }
     * 
     */
    public Short getEingliederungsart() {
        return eingliederungsart;
    }

    /**
     * Sets the value of the eingliederungsart property.
     * 
     * @param value
     *            allowed object is {@link Short }
     * 
     */
    public void setEingliederungsart(Short value) {
        eingliederungsart = value;
    }

    /**
     * Gets the value of the uvGarantie property.
     * 
     * @return
     *         possible object is {@link Boolean }
     * 
     */
    public Boolean isUVGarantie() {
        return uvGarantie;
    }

    /**
     * Sets the value of the uvGarantie property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setUVGarantie(Boolean value) {
        uvGarantie = value;
    }

    /**
     * Gets the value of the gekuerztesTaggeld property.
     * 
     * @return
     *         possible object is {@link Boolean }
     * 
     */
    public Boolean isGekuerztesTaggeld() {
        return gekuerztesTaggeld;
    }

    /**
     * Sets the value of the gekuerztesTaggeld property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setGekuerztesTaggeld(Boolean value) {
        gekuerztesTaggeld = value;
    }

    /**
     * Gets the value of the besitzstand4IVRevision property.
     * 
     * @return
     *         possible object is {@link Boolean }
     * 
     */
    public Boolean isBesitzstand4IVRevision() {
        return besitzstand4IVRevision;
    }

    /**
     * Sets the value of the besitzstand4IVRevision property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setBesitzstand4IVRevision(Boolean value) {
        besitzstand4IVRevision = value;
    }

    /**
     * Gets the value of the nrVerfuegung property.
     * 
     * @return
     *         possible object is {@link IVTaggelderMeldungType.NrVerfuegung }
     * 
     */
    public IVTaggelderMeldungType.NrVerfuegung getNrVerfuegung() {
        return nrVerfuegung;
    }

    /**
     * Sets the value of the nrVerfuegung property.
     * 
     * @param value
     *            allowed object is {@link IVTaggelderMeldungType.NrVerfuegung }
     * 
     */
    public void setNrVerfuegung(IVTaggelderMeldungType.NrVerfuegung value) {
        nrVerfuegung = value;
    }

    /**
     * Gets the value of the ersteTaggeldPeriode property.
     * 
     * @return
     *         possible object is {@link IVTaggelderMeldungType.ErsteTaggeldPeriode }
     * 
     */
    public IVTaggelderMeldungType.ErsteTaggeldPeriode getErsteTaggeldPeriode() {
        return ersteTaggeldPeriode;
    }

    /**
     * Sets the value of the ersteTaggeldPeriode property.
     * 
     * @param value
     *            allowed object is {@link IVTaggelderMeldungType.ErsteTaggeldPeriode }
     * 
     */
    public void setErsteTaggeldPeriode(IVTaggelderMeldungType.ErsteTaggeldPeriode value) {
        ersteTaggeldPeriode = value;
    }

    /**
     * Gets the value of the taggeldPeriode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the taggeldPeriode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTaggeldPeriode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IVTaggelderMeldungType.TaggeldPeriode }
     * 
     * 
     */
    public List<IVTaggelderMeldungType.TaggeldPeriode> getTaggeldPeriode() {
        if (taggeldPeriode == null) {
            taggeldPeriode = new ArrayList<IVTaggelderMeldungType.TaggeldPeriode>();
        }
        return taggeldPeriode;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AbzugVerpflegungUnterkunft" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="AnzahlTage" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
     *         &lt;element name="Tagesansatz" type="{http://www.zas.admin.ch/RC}BetragFRRP3_Type" minOccurs="0"/>
     *         &lt;element name="AnzahlTageEingliederungsunterbruchMitTaggeld" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
     *         &lt;element name="GrundDerUnterbrechung" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="9"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AuszahlungTaggeld" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IVTaggeldTotal" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
     *         &lt;element name="VorzeichenCode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="PeriodeBeginn" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
     *         &lt;element name="PeriodeEnde" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
     *         &lt;element name="AnspruchKindergeld" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="Besitzstand5IVRevision" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "abzugVerpflegungUnterkunft", "anzahlTage", "tagesansatz",
            "anzahlTageEingliederungsunterbruchMitTaggeld", "grundDerUnterbrechung", "auszahlungTaggeld",
            "ivTaggeldTotal", "vorzeichenCode", "periodeBeginn", "periodeEnde", "anspruchKindergeld",
            "besitzstand5IVRevision" })
    public static class ErsteTaggeldPeriode {

        @XmlElement(name = "AbzugVerpflegungUnterkunft")
        protected Boolean abzugVerpflegungUnterkunft;
        @XmlElement(name = "AnzahlTage")
        protected Integer anzahlTage;
        @XmlElement(name = "Tagesansatz")
        protected BigDecimal tagesansatz;
        @XmlElement(name = "AnzahlTageEingliederungsunterbruchMitTaggeld")
        protected Integer anzahlTageEingliederungsunterbruchMitTaggeld;
        @XmlElement(name = "GrundDerUnterbrechung")
        protected Short grundDerUnterbrechung;
        @XmlElement(name = "AuszahlungTaggeld")
        protected Short auszahlungTaggeld;
        @XmlElement(name = "IVTaggeldTotal")
        protected BigDecimal ivTaggeldTotal;
        @XmlElement(name = "VorzeichenCode")
        protected Boolean vorzeichenCode;
        @XmlElement(name = "PeriodeBeginn")
        protected XMLGregorianCalendar periodeBeginn;
        @XmlElement(name = "PeriodeEnde")
        protected XMLGregorianCalendar periodeEnde;
        @XmlElement(name = "AnspruchKindergeld")
        protected Boolean anspruchKindergeld;
        @XmlElement(name = "Besitzstand5IVRevision")
        protected Boolean besitzstand5IVRevision;

        /**
         * Gets the value of the abzugVerpflegungUnterkunft property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isAbzugVerpflegungUnterkunft() {
            return abzugVerpflegungUnterkunft;
        }

        /**
         * Sets the value of the abzugVerpflegungUnterkunft property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setAbzugVerpflegungUnterkunft(Boolean value) {
            abzugVerpflegungUnterkunft = value;
        }

        /**
         * Gets the value of the anzahlTage property.
         * 
         * @return
         *         possible object is {@link Integer }
         * 
         */
        public Integer getAnzahlTage() {
            return anzahlTage;
        }

        /**
         * Sets the value of the anzahlTage property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setAnzahlTage(Integer value) {
            anzahlTage = value;
        }

        /**
         * Gets the value of the tagesansatz property.
         * 
         * @return
         *         possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTagesansatz() {
            return tagesansatz;
        }

        /**
         * Sets the value of the tagesansatz property.
         * 
         * @param value
         *            allowed object is {@link BigDecimal }
         * 
         */
        public void setTagesansatz(BigDecimal value) {
            tagesansatz = value;
        }

        /**
         * Gets the value of the anzahlTageEingliederungsunterbruchMitTaggeld property.
         * 
         * @return
         *         possible object is {@link Integer }
         * 
         */
        public Integer getAnzahlTageEingliederungsunterbruchMitTaggeld() {
            return anzahlTageEingliederungsunterbruchMitTaggeld;
        }

        /**
         * Sets the value of the anzahlTageEingliederungsunterbruchMitTaggeld property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setAnzahlTageEingliederungsunterbruchMitTaggeld(Integer value) {
            anzahlTageEingliederungsunterbruchMitTaggeld = value;
        }

        /**
         * Gets the value of the grundDerUnterbrechung property.
         * 
         * @return
         *         possible object is {@link Short }
         * 
         */
        public Short getGrundDerUnterbrechung() {
            return grundDerUnterbrechung;
        }

        /**
         * Sets the value of the grundDerUnterbrechung property.
         * 
         * @param value
         *            allowed object is {@link Short }
         * 
         */
        public void setGrundDerUnterbrechung(Short value) {
            grundDerUnterbrechung = value;
        }

        /**
         * Gets the value of the auszahlungTaggeld property.
         * 
         * @return
         *         possible object is {@link Short }
         * 
         */
        public Short getAuszahlungTaggeld() {
            return auszahlungTaggeld;
        }

        /**
         * Sets the value of the auszahlungTaggeld property.
         * 
         * @param value
         *            allowed object is {@link Short }
         * 
         */
        public void setAuszahlungTaggeld(Short value) {
            auszahlungTaggeld = value;
        }

        /**
         * Gets the value of the ivTaggeldTotal property.
         * 
         * @return
         *         possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getIVTaggeldTotal() {
            return ivTaggeldTotal;
        }

        /**
         * Sets the value of the ivTaggeldTotal property.
         * 
         * @param value
         *            allowed object is {@link BigDecimal }
         * 
         */
        public void setIVTaggeldTotal(BigDecimal value) {
            ivTaggeldTotal = value;
        }

        /**
         * Gets the value of the vorzeichenCode property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isVorzeichenCode() {
            return vorzeichenCode;
        }

        /**
         * Sets the value of the vorzeichenCode property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setVorzeichenCode(Boolean value) {
            vorzeichenCode = value;
        }

        /**
         * Gets the value of the periodeBeginn property.
         * 
         * @return
         *         possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getPeriodeBeginn() {
            return periodeBeginn;
        }

        /**
         * Sets the value of the periodeBeginn property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setPeriodeBeginn(XMLGregorianCalendar value) {
            periodeBeginn = value;
        }

        /**
         * Gets the value of the periodeEnde property.
         * 
         * @return
         *         possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getPeriodeEnde() {
            return periodeEnde;
        }

        /**
         * Sets the value of the periodeEnde property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setPeriodeEnde(XMLGregorianCalendar value) {
            periodeEnde = value;
        }

        /**
         * Gets the value of the anspruchKindergeld property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isAnspruchKindergeld() {
            return anspruchKindergeld;
        }

        /**
         * Sets the value of the anspruchKindergeld property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setAnspruchKindergeld(Boolean value) {
            anspruchKindergeld = value;
        }

        /**
         * Gets the value of the besitzstand5IVRevision property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isBesitzstand5IVRevision() {
            return besitzstand5IVRevision;
        }

        /**
         * Sets the value of the besitzstand5IVRevision property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setBesitzstand5IVRevision(Boolean value) {
            besitzstand5IVRevision = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ZustaendigeIVStelle" type="{http://www.zas.admin.ch/RC}IVStelle_strongType"/>
     *         &lt;element name="ElfstelligeNrVerfuegung" type="{http://www.zas.admin.ch/RC}VerfuegungNummer_Type"/>
     *         &lt;element name="Versichertennummer" type="{http://www.zas.admin.ch/RC}Versichertennummer11oder13Stellen_Type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "zustaendigeIVStelle", "elfstelligeNrVerfuegung", "versichertennummer" })
    public static class NrVerfuegung {

        @XmlElement(name = "ZustaendigeIVStelle")
        protected int zustaendigeIVStelle;
        @XmlElement(name = "ElfstelligeNrVerfuegung")
        protected long elfstelligeNrVerfuegung;
        @XmlElement(name = "Versichertennummer", required = true)
        protected String versichertennummer;

        /**
         * Gets the value of the zustaendigeIVStelle property.
         * 
         */
        public int getZustaendigeIVStelle() {
            return zustaendigeIVStelle;
        }

        /**
         * Sets the value of the zustaendigeIVStelle property.
         * 
         */
        public void setZustaendigeIVStelle(int value) {
            zustaendigeIVStelle = value;
        }

        /**
         * Gets the value of the elfstelligeNrVerfuegung property.
         * 
         */
        public long getElfstelligeNrVerfuegung() {
            return elfstelligeNrVerfuegung;
        }

        /**
         * Sets the value of the elfstelligeNrVerfuegung property.
         * 
         */
        public void setElfstelligeNrVerfuegung(long value) {
            elfstelligeNrVerfuegung = value;
        }

        /**
         * Gets the value of the versichertennummer property.
         * 
         * @return
         *         possible object is {@link String }
         * 
         */
        public String getVersichertennummer() {
            return versichertennummer;
        }

        /**
         * Sets the value of the versichertennummer property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setVersichertennummer(String value) {
            versichertennummer = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AbzugVerpflegungUnterkunft" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="AnzahlTage" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
     *         &lt;element name="Tagesansatz" type="{http://www.zas.admin.ch/RC}BetragFRRP3_Type" minOccurs="0"/>
     *         &lt;element name="AnzahlTageEingliederungsunterbruchMitTaggeld" type="{http://www.zas.admin.ch/RC}AnzahlTage3Stellig_Type" minOccurs="0"/>
     *         &lt;element name="GrundDerUnterbrechung" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="9"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AuszahlungTaggeld" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IVTaggeldTotal" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
     *         &lt;element name="VorzeichenCode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="PeriodeBeginn" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
     *         &lt;element name="PeriodeEnde" type="{http://www.zas.admin.ch/RC}AHVDatumJMT_Type" minOccurs="0"/>
     *         &lt;element name="AnspruchKindergeld" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="Besitzstand5IVRevision" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="BetragEntschaedigungBetreuungskosten" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
     *         &lt;element name="BetragEinarbeitungszuschuss" type="{http://www.zas.admin.ch/RC}BetragFRRP5_Type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "abzugVerpflegungUnterkunft", "anzahlTage", "tagesansatz",
            "anzahlTageEingliederungsunterbruchMitTaggeld", "grundDerUnterbrechung", "auszahlungTaggeld",
            "ivTaggeldTotal", "vorzeichenCode", "periodeBeginn", "periodeEnde", "anspruchKindergeld",
            "besitzstand5IVRevision", "betragEntschaedigungBetreuungskosten", "betragEinarbeitungszuschuss" })
    public static class TaggeldPeriode {

        @XmlElement(name = "AbzugVerpflegungUnterkunft")
        protected Boolean abzugVerpflegungUnterkunft;
        @XmlElement(name = "AnzahlTage")
        protected Integer anzahlTage;
        @XmlElement(name = "Tagesansatz")
        protected BigDecimal tagesansatz;
        @XmlElement(name = "AnzahlTageEingliederungsunterbruchMitTaggeld")
        protected Integer anzahlTageEingliederungsunterbruchMitTaggeld;
        @XmlElement(name = "GrundDerUnterbrechung")
        protected Short grundDerUnterbrechung;
        @XmlElement(name = "AuszahlungTaggeld")
        protected Short auszahlungTaggeld;
        @XmlElement(name = "IVTaggeldTotal")
        protected BigDecimal ivTaggeldTotal;
        @XmlElement(name = "VorzeichenCode")
        protected Boolean vorzeichenCode;
        @XmlElement(name = "PeriodeBeginn")
        protected XMLGregorianCalendar periodeBeginn;
        @XmlElement(name = "PeriodeEnde")
        protected XMLGregorianCalendar periodeEnde;
        @XmlElement(name = "AnspruchKindergeld")
        protected Boolean anspruchKindergeld;
        @XmlElement(name = "Besitzstand5IVRevision")
        protected Boolean besitzstand5IVRevision;
        @XmlElement(name = "BetragEntschaedigungBetreuungskosten")
        protected BigDecimal betragEntschaedigungBetreuungskosten;
        @XmlElement(name = "BetragEinarbeitungszuschuss")
        protected BigDecimal betragEinarbeitungszuschuss;

        /**
         * Gets the value of the abzugVerpflegungUnterkunft property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isAbzugVerpflegungUnterkunft() {
            return abzugVerpflegungUnterkunft;
        }

        /**
         * Sets the value of the abzugVerpflegungUnterkunft property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setAbzugVerpflegungUnterkunft(Boolean value) {
            abzugVerpflegungUnterkunft = value;
        }

        /**
         * Gets the value of the anzahlTage property.
         * 
         * @return
         *         possible object is {@link Integer }
         * 
         */
        public Integer getAnzahlTage() {
            return anzahlTage;
        }

        /**
         * Sets the value of the anzahlTage property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setAnzahlTage(Integer value) {
            anzahlTage = value;
        }

        /**
         * Gets the value of the tagesansatz property.
         * 
         * @return
         *         possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTagesansatz() {
            return tagesansatz;
        }

        /**
         * Sets the value of the tagesansatz property.
         * 
         * @param value
         *            allowed object is {@link BigDecimal }
         * 
         */
        public void setTagesansatz(BigDecimal value) {
            tagesansatz = value;
        }

        /**
         * Gets the value of the anzahlTageEingliederungsunterbruchMitTaggeld property.
         * 
         * @return
         *         possible object is {@link Integer }
         * 
         */
        public Integer getAnzahlTageEingliederungsunterbruchMitTaggeld() {
            return anzahlTageEingliederungsunterbruchMitTaggeld;
        }

        /**
         * Sets the value of the anzahlTageEingliederungsunterbruchMitTaggeld property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setAnzahlTageEingliederungsunterbruchMitTaggeld(Integer value) {
            anzahlTageEingliederungsunterbruchMitTaggeld = value;
        }

        /**
         * Gets the value of the grundDerUnterbrechung property.
         * 
         * @return
         *         possible object is {@link Short }
         * 
         */
        public Short getGrundDerUnterbrechung() {
            return grundDerUnterbrechung;
        }

        /**
         * Sets the value of the grundDerUnterbrechung property.
         * 
         * @param value
         *            allowed object is {@link Short }
         * 
         */
        public void setGrundDerUnterbrechung(Short value) {
            grundDerUnterbrechung = value;
        }

        /**
         * Gets the value of the auszahlungTaggeld property.
         * 
         * @return
         *         possible object is {@link Short }
         * 
         */
        public Short getAuszahlungTaggeld() {
            return auszahlungTaggeld;
        }

        /**
         * Sets the value of the auszahlungTaggeld property.
         * 
         * @param value
         *            allowed object is {@link Short }
         * 
         */
        public void setAuszahlungTaggeld(Short value) {
            auszahlungTaggeld = value;
        }

        /**
         * Gets the value of the ivTaggeldTotal property.
         * 
         * @return
         *         possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getIVTaggeldTotal() {
            return ivTaggeldTotal;
        }

        /**
         * Sets the value of the ivTaggeldTotal property.
         * 
         * @param value
         *            allowed object is {@link BigDecimal }
         * 
         */
        public void setIVTaggeldTotal(BigDecimal value) {
            ivTaggeldTotal = value;
        }

        /**
         * Gets the value of the vorzeichenCode property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isVorzeichenCode() {
            return vorzeichenCode;
        }

        /**
         * Sets the value of the vorzeichenCode property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setVorzeichenCode(Boolean value) {
            vorzeichenCode = value;
        }

        /**
         * Gets the value of the periodeBeginn property.
         * 
         * @return
         *         possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getPeriodeBeginn() {
            return periodeBeginn;
        }

        /**
         * Sets the value of the periodeBeginn property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setPeriodeBeginn(XMLGregorianCalendar value) {
            periodeBeginn = value;
        }

        /**
         * Gets the value of the periodeEnde property.
         * 
         * @return
         *         possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getPeriodeEnde() {
            return periodeEnde;
        }

        /**
         * Sets the value of the periodeEnde property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setPeriodeEnde(XMLGregorianCalendar value) {
            periodeEnde = value;
        }

        /**
         * Gets the value of the anspruchKindergeld property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isAnspruchKindergeld() {
            return anspruchKindergeld;
        }

        /**
         * Sets the value of the anspruchKindergeld property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setAnspruchKindergeld(Boolean value) {
            anspruchKindergeld = value;
        }

        /**
         * Gets the value of the besitzstand5IVRevision property.
         * 
         * @return
         *         possible object is {@link Boolean }
         * 
         */
        public Boolean isBesitzstand5IVRevision() {
            return besitzstand5IVRevision;
        }

        /**
         * Sets the value of the besitzstand5IVRevision property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setBesitzstand5IVRevision(Boolean value) {
            besitzstand5IVRevision = value;
        }

        /**
         * Gets the value of the betragEntschaedigungBetreuungskosten property.
         * 
         * @return
         *         possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getBetragEntschaedigungBetreuungskosten() {
            return betragEntschaedigungBetreuungskosten;
        }

        /**
         * Sets the value of the betragEntschaedigungBetreuungskosten property.
         * 
         * @param value
         *            allowed object is {@link BigDecimal }
         * 
         */
        public void setBetragEntschaedigungBetreuungskosten(BigDecimal value) {
            betragEntschaedigungBetreuungskosten = value;
        }

        /**
         * Gets the value of the betragEinarbeitungszuschuss property.
         * 
         * @return
         *         possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getBetragEinarbeitungszuschuss() {
            return betragEinarbeitungszuschuss;
        }

        /**
         * Sets the value of the betragEinarbeitungszuschuss property.
         * 
         * @param value
         *            allowed object is {@link BigDecimal }
         * 
         */
        public void setBetragEinarbeitungszuschuss(BigDecimal value) {
            betragEinarbeitungszuschuss = value;
        }

    }

}
