//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Code application 39
 * 
 * <p>
 * Java class for KontrollMeldung_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KontrollMeldung_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListeFolgerecordNr" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FolgerecordNr" type="{http://www.zas.admin.ch/RC}FolgerecordNr_Type" maxOccurs="2"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VorzeichenCode" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
 *         &lt;element name="TotalEinkommen" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="AnzahlIKEintragung" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KontrollMeldung_Type", propOrder = { "listeFolgerecordNr", "vorzeichenCode", "totalEinkommen",
        "anzahlIKEintragung" })
public class KontrollMeldungType {

    @XmlElement(name = "ListeFolgerecordNr")
    protected KontrollMeldungType.ListeFolgerecordNr listeFolgerecordNr;
    @XmlElement(name = "VorzeichenCode")
    protected short vorzeichenCode;
    @XmlElement(name = "TotalEinkommen")
    @XmlSchemaType(name = "unsignedInt")
    protected long totalEinkommen;
    @XmlElement(name = "AnzahlIKEintragung")
    @XmlSchemaType(name = "unsignedShort")
    protected int anzahlIKEintragung;

    /**
     * Gets the value of the listeFolgerecordNr property.
     * 
     * @return
     *         possible object is {@link KontrollMeldungType.ListeFolgerecordNr }
     * 
     */
    public KontrollMeldungType.ListeFolgerecordNr getListeFolgerecordNr() {
        return listeFolgerecordNr;
    }

    /**
     * Sets the value of the listeFolgerecordNr property.
     * 
     * @param value
     *            allowed object is {@link KontrollMeldungType.ListeFolgerecordNr }
     * 
     */
    public void setListeFolgerecordNr(KontrollMeldungType.ListeFolgerecordNr value) {
        listeFolgerecordNr = value;
    }

    /**
     * Gets the value of the vorzeichenCode property.
     * 
     */
    public short getVorzeichenCode() {
        return vorzeichenCode;
    }

    /**
     * Sets the value of the vorzeichenCode property.
     * 
     */
    public void setVorzeichenCode(short value) {
        vorzeichenCode = value;
    }

    /**
     * Gets the value of the totalEinkommen property.
     * 
     */
    public long getTotalEinkommen() {
        return totalEinkommen;
    }

    /**
     * Sets the value of the totalEinkommen property.
     * 
     */
    public void setTotalEinkommen(long value) {
        totalEinkommen = value;
    }

    /**
     * Gets the value of the anzahlIKEintragung property.
     * 
     */
    public int getAnzahlIKEintragung() {
        return anzahlIKEintragung;
    }

    /**
     * Sets the value of the anzahlIKEintragung property.
     * 
     */
    public void setAnzahlIKEintragung(int value) {
        anzahlIKEintragung = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FolgerecordNr" type="{http://www.zas.admin.ch/RC}FolgerecordNr_Type" maxOccurs="2"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "folgerecordNr" })
    public static class ListeFolgerecordNr {

        @XmlElement(name = "FolgerecordNr", required = true, nillable = true)
        protected List<Integer> folgerecordNr;

        /**
         * Gets the value of the folgerecordNr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the folgerecordNr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getFolgerecordNr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Integer }
         * 
         * 
         */
        public List<Integer> getFolgerecordNr() {
            if (folgerecordNr == null) {
                folgerecordNr = new ArrayList<Integer>();
            }
            return folgerecordNr;
        }

    }

}
