//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.25 at 01:29:35 PM CEST
//

package ch.admin.zas.rc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Partie commune du code application 31 et 34
 * 
 * <p>
 * Java class for TStandIKStatistik complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStandIKStatistik">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VorzeichenCode" type="{http://www.zas.admin.ch/RC}SchluesselzahlStornoeintrag_Type"/>
 *         &lt;element name="SummeEinkommen" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStandIKStatistik", propOrder = { "vorzeichenCode", "summeEinkommen" })
@XmlSeeAlso({ ch.admin.zas.rc.IKStatistikMeldungType.StandIKStatistikNacher.class })
public class TStandIKStatistik {

    @XmlElement(name = "VorzeichenCode")
    protected short vorzeichenCode;
    @XmlElement(name = "SummeEinkommen", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger summeEinkommen;

    /**
     * Gets the value of the vorzeichenCode property.
     * 
     */
    public short getVorzeichenCode() {
        return vorzeichenCode;
    }

    /**
     * Sets the value of the vorzeichenCode property.
     * 
     */
    public void setVorzeichenCode(short value) {
        vorzeichenCode = value;
    }

    /**
     * Gets the value of the summeEinkommen property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getSummeEinkommen() {
        return summeEinkommen;
    }

    /**
     * Sets the value of the summeEinkommen property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setSummeEinkommen(BigInteger value) {
        summeEinkommen = value;
    }

}
