/*
 * Generated by JasperReports - 29.03.06 11:29
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class Signature_Model_1 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_P_SIGNATURE_SERVICE = null;
    private JRFillParameter parameter_P_SIGNATURE_IMG = null;
    private JRFillParameter parameter_P_DEFAULT_MODEL_PATH = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_P_SIGNATURE_DATA = null;
    private JRFillParameter parameter_P_SIGNATURE_SIGNATAIRE = null;
    private JRFillParameter parameter_P_SIGNATURE_CAISSE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;


    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_P_SIGNATURE_SERVICE = (JRFillParameter)parsm.get("P_SIGNATURE_SERVICE");
        parameter_P_SIGNATURE_IMG = (JRFillParameter)parsm.get("P_SIGNATURE_IMG");
        parameter_P_DEFAULT_MODEL_PATH = (JRFillParameter)parsm.get("P_DEFAULT_MODEL_PATH");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_P_SIGNATURE_DATA = (JRFillParameter)parsm.get("P_SIGNATURE_DATA");
        parameter_P_SIGNATURE_SIGNATAIRE = (JRFillParameter)parsm.get("P_SIGNATURE_SIGNATAIRE");
        parameter_P_SIGNATURE_CAISSE = (JRFillParameter)parsm.get("P_SIGNATURE_CAISSE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");


        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 46 : // parameterDefaultValue_P_DEFAULT_MODEL_PATH
            {
                value = (java.lang.String)("C:\\Documents and Settings\\Administrator\\My Documents\\consultran\\projet\\globaz\\iText\\Default_workspace\\iText model\\defaultModel");
                break;
            }
            case 55 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_DATA.getValue())!=null));
                break;
            }
            case 53 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_SIGNATAIRE.getValue())!=null));
                break;
            }
            case 43 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 52 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_SERVICE.getValue()));
                break;
            }
            case 41 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 50 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_CAISSE.getValue()));
                break;
            }
            case 48 : // image_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DEFAULT_MODEL_PATH.getValue())+"/"+((java.lang.String)parameter_P_SIGNATURE_IMG.getValue()));
                break;
            }
            case 44 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 39 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 38 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 56 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_DATA.getValue()));
                break;
            }
            case 54 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_SIGNATAIRE.getValue()));
                break;
            }
            case 45 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 47 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_IMG.getValue())!=null));
                break;
            }
            case 40 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 51 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_SERVICE.getValue())!=null));
                break;
            }
            case 49 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_CAISSE.getValue())!=null));
                break;
            }
            case 42 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 46 : // parameterDefaultValue_P_DEFAULT_MODEL_PATH
            {
                value = (java.lang.String)("C:\\Documents and Settings\\Administrator\\My Documents\\consultran\\projet\\globaz\\iText\\Default_workspace\\iText model\\defaultModel");
                break;
            }
            case 55 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_DATA.getValue())!=null));
                break;
            }
            case 53 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_SIGNATAIRE.getValue())!=null));
                break;
            }
            case 43 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 52 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_SERVICE.getValue()));
                break;
            }
            case 41 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 50 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_CAISSE.getValue()));
                break;
            }
            case 48 : // image_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DEFAULT_MODEL_PATH.getValue())+"/"+((java.lang.String)parameter_P_SIGNATURE_IMG.getValue()));
                break;
            }
            case 44 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 39 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 38 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 56 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_DATA.getValue()));
                break;
            }
            case 54 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_SIGNATAIRE.getValue()));
                break;
            }
            case 45 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 47 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_IMG.getValue())!=null));
                break;
            }
            case 40 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 51 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_SERVICE.getValue())!=null));
                break;
            }
            case 49 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_CAISSE.getValue())!=null));
                break;
            }
            case 42 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 46 : // parameterDefaultValue_P_DEFAULT_MODEL_PATH
            {
                value = (java.lang.String)("C:\\Documents and Settings\\Administrator\\My Documents\\consultran\\projet\\globaz\\iText\\Default_workspace\\iText model\\defaultModel");
                break;
            }
            case 55 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_DATA.getValue())!=null));
                break;
            }
            case 53 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_SIGNATAIRE.getValue())!=null));
                break;
            }
            case 43 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 52 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_SERVICE.getValue()));
                break;
            }
            case 41 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 50 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_CAISSE.getValue()));
                break;
            }
            case 48 : // image_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_DEFAULT_MODEL_PATH.getValue())+"/"+((java.lang.String)parameter_P_SIGNATURE_IMG.getValue()));
                break;
            }
            case 44 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 39 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 38 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 56 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_DATA.getValue()));
                break;
            }
            case 54 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)parameter_P_SIGNATURE_SIGNATAIRE.getValue()));
                break;
            }
            case 45 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 47 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_IMG.getValue())!=null));
                break;
            }
            case 40 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 51 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_SERVICE.getValue())!=null));
                break;
            }
            case 49 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)parameter_P_SIGNATURE_CAISSE.getValue())!=null));
                break;
            }
            case 42 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
