//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.23 at 09:38:52 AM CEST
//

package globaz.hercule.process.statOfas.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for nqCanton_Typ.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="nqCanton_Typ">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="AI"/>
 *     &lt;enumeration value="AR"/>
 *     &lt;enumeration value="BE"/>
 *     &lt;enumeration value="BL"/>
 *     &lt;enumeration value="BS"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="GE"/>
 *     &lt;enumeration value="GL"/>
 *     &lt;enumeration value="GR"/>
 *     &lt;enumeration value="JU"/>
 *     &lt;enumeration value="LU"/>
 *     &lt;enumeration value="NE"/>
 *     &lt;enumeration value="NW"/>
 *     &lt;enumeration value="OW"/>
 *     &lt;enumeration value="SG"/>
 *     &lt;enumeration value="SH"/>
 *     &lt;enumeration value="SO"/>
 *     &lt;enumeration value="SZ"/>
 *     &lt;enumeration value="TG"/>
 *     &lt;enumeration value="TI"/>
 *     &lt;enumeration value="UR"/>
 *     &lt;enumeration value="VD"/>
 *     &lt;enumeration value="VS"/>
 *     &lt;enumeration value="ZG"/>
 *     &lt;enumeration value="ZH"/>
 *     &lt;enumeration value="ET"/>
 *     &lt;enumeration value="CH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "nqCanton_Typ")
@XmlEnum
public enum NqCantonTyp {

    AG,
    AI,
    AR,
    BE,
    BL,
    BS,
    FR,
    GE,
    GL,
    GR,
    JU,
    LU,
    NE,
    NW,
    OW,
    SG,
    SH,
    SO,
    SZ,
    TG,
    TI,
    UR,
    VD,
    VS,
    ZG,
    ZH,
    ET,
    CH;

    public String value() {
        return name();
    }

    public static NqCantonTyp fromValue(String v) {
        return valueOf(v);
    }

}
