<wsdl:definitions name="SeodorWebserviceDefinition10"
                  targetNamespace="http://www.zas.admin.ch/seodor/ws/service-periods/1"
                  xmlns="http://www.zas.admin.ch/seodor/ws/service-periods/1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:eavh-iv-2017="http://www.zas.admin.ch/xmlns/seodor-ws/1" >

  <wsdl:types>
    <xs:schema targetNamespace="http://www.zas.admin.ch/seodor/ws/service-periods/1" elementFormDefault="qualified">
      <xs:import namespace="http://www.zas.admin.ch/xmlns/seodor-ws/1" schemaLocation="../xsd/seodor-ws-1-0.xsd"/>
    </xs:schema>
  </wsdl:types>

  <wsdl:message name="getServicePeriodsRequestMessage">
    <wsdl:part name="getServicePeriodsRequest" element="eavh-iv-2017:getServicePeriodsRequest"/>
  </wsdl:message>
  <wsdl:message name="getServicePeriodsResponseMessage">
    <wsdl:part name="getServicePeriodsResponse" element="eavh-iv-2017:getServicePeriodsResponse"/>
  </wsdl:message>

  <wsdl:portType name="ServicePeriodsPort10">
    <wsdl:operation name="getServicePeriods">
      <wsdl:input message="getServicePeriodsRequestMessage"/>
      <wsdl:output message="getServicePeriodsResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="ServicePeriodsBinding10" type="ServicePeriodsPort10">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <wsdl:operation name="getServicePeriods">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="ServicePeriodsService10">
    <wsdl:port name="ServicePeriodsPort10" binding="ServicePeriodsBinding10">
      <soap:address location="https://ws.seodor.zas.admin.ch/services/seodor/ws/service-periods/1"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
