package ch.globaz.amal.business.constantes;

public interface IAMParametres {
    // ONGLETS DE MENU PARAMETRES
    public final static String[][] ONGLETS_PARAMETRES = {
            { "MENU_ONGLET_PARAMETRES_SUBSIDES_ANNEEE", "MENU_ONGLET_PARAMETRES_SUBSIDES_ANNEEE_ABREV",
                    IAMActions.ACTION_PARAMETRES_SUBSIDE_ANNEE },
            { "MENU_ONGLET_PARAMETRES_PRIMES_MOYENNES", "MENU_ONGLET_PARAMETRES_PRIMES_MOYENNES_ABREV",
                    IAMActions.ACTION_PARAMETRES_PRIME_MOYENNE },
            { "MENU_ONGLET_PARAMETRES_PRIMES_AVANTAGEUSE", "MENU_ONGLET_PARAMETRES_PRIMES_AVANTAGEUSE_ABREV",
                    IAMActions.ACTION_PARAMETRES_PRIME_AVANTAGEUSE },
            { "MENU_ONGLET_PARAMETRES_PARAMETRE_ANNUEL", "MENU_ONGLET_PARAMETRES_PARAMETRE_ANNUEL_ABREV",
                    IAMActions.ACTION_PARAMETRES_PARAMETRE_ANNUEL },
            { "MENU_ONGLET_PARAMETRES_DEDUCTIONS_FISCALES_ENFANTS",
                    "MENU_ONGLET_PARAMETRES_DEDUCTIONS_FISCALES_ENFANTS_ABREV",
                    IAMActions.ACTION_PARAMETRES_DEDUCTIONS_FISCALES_ENFANTS },
            { "MENU_ONGLET_PARAMETRES_APPLICATION", "MENU_ONGLET_PARAMETRES_APPLICATION_ABREV",
                    IAMActions.ACTION_PARAMETRES_APPLICATION },
            { "MENU_ONGLET_PARAMETRES_COPY", "MENU_ONGLET_PARAMETRES_COPY_ABREV",
                    IAMActions.ACTION_PARAMETRES_COPY_PARAMETRES } };
}
