package globaz.phenix.listes.itext;

import globaz.framework.printing.itext.fill.FWIImportParametre;

public class CPIListeCommunicationRetourDetailFiscGeParam extends FWIImportParametre {

    public static final String LABEL_ACTIVITE_DECLARE = "L_ACTIVITE_DECLARE";
    public static final String LABEL_AFFILIE = "L_AFFILIE";
    public static final String LABEL_ANNEE = "L_ANNEE";
    public static final String LABEL_ASSUJETI_IBO = "L_ASSUJETI_IBO";
    public static final String LABEL_ASSUJETI_IFD = "L_ASSUJETI_IFD";
    public static final String LABEL_BOURSES = "L_BOURSES";
    public static final String LABEL_CAPITAL = "L_CAPITAL";
    public static final String LABEL_DATE_MAD = "L_DATE_MAD";
    public static final String LABEL_DATE_RECEPTION = "L_DATE_RECEPTION";
    public static final String LABEL_DIVERS = "L_DIVERS";
    public static final String LABEL_EXERCICE = "L_EXERCICE";
    public static final String LABEL_EXPLICATIONS = "L_EXPLICATIONS";
    public static final String LABEL_FORTUNE = "L_FORTUNE";
    public static final String LABEL_GENRE_AFF = "L_GENRE_AFF";
    public static final String LABEL_GENRE_TAX = "L_GENRE_TAX";
    public static final String LABEL_IFD = "L_IFD";
    public static final String LABEL_IMPO_DEPENSE = "L_IMPO_DEPENSE";
    public static final String LABEL_IMPOSITION = "L_IMPOSITION";
    public static final String LABEL_INDEM_JOUR = "L_INDEM_JOUR";
    public static final String LABEL_INFO_GENERAL = "L_INFO_GENERAL";
    public static final String LABEL_INFO_SUPP = "L_INFO_SUPP";
    public static final String LABEL_NOM = "L_NOM";
    public static final String LABEL_NOM_AFC = "L_NOM_AFC";
    public static final String LABEL_NOM_CON = "L_NOM_CON";
    public static final String LABEL_NSS = "L_NSS";
    public static final String LABEL_NUM_CAISSE = "L_NUM_CAISSE";
    public static final String LABEL_NUM_COMM = "L_NUM_COMM";
    public static final String LABEL_NUM_CONTRI = "L_NUM_CONTRI";
    public static final String LABEL_NUM_DEMANDE = "L_NUM_DEMANDE";
    public static final String LABEL_NUMAFF_RECU = "L_NUMAFF_RECU";
    public static final String LABEL_NUMAVS_CON = "L_NUMAVS_CON";
    public static final String LABEL_NUMCONTRI_RECU = "L_NUMCONTRI_RECU";
    public static final String LABEL_OBSERVATIONS = "L_OBSERVATIONS";
    public static final String LABEL_PENSION = "L_PENSION";
    public static final String LABEL_PENSION_ALIM = "L_PENSION_ALIM";
    public static final String LABEL_PERS_NI = "L_PERS_NI";
    public static final String LABEL_PRENOM = "L_PRENOM";
    public static final String LABEL_PRENOM_AFC = "L_PRENOM_AFC";
    public static final String LABEL_PRENOM_CON = "L_PRENOM_CON";
    public static final String LABEL_RENTE_INVALID = "L_RENTE_INVALID";
    public static final String LABEL_RENTE_VIAGERE = "L_RENTE_VIAGERE";
    public static final String LABEL_RENTE_VIEIL = "L_RENTE_VIEIL";
    public static final String LABEL_RETRAITE = "L_RETRAITE";
    public static final String LABEL_REVENU = "L_REVENU";
    public static final String LABEL_TAX_OFFICE = "L_TAX_OFFICE";
    // Communication fiscale retour
    // LABELS TIERS
    public static final String LABEL_TIERS = "L_TIERS";
    public static final String LABEL_TIERS_DESCRIPTION = "L_TIERS_DESCRIPTION";
    public static final String PARAM_ACTIVITE_DECLARE = "P_ACTIVITE_DECLARE";
    public static final String PARAM_AFFILIE = "P_AFFILIE";
    public static final String PARAM_ANNEE = "P_ANNEE";
    public static final String PARAM_ASSUJETI_IBO = "P_ASSUJETI_IBO";
    public static final String PARAM_ASSUJETI_IFD = "P_ASSUJETI_IFD";
    public static final String PARAM_BOURSES = "P_BOURSES";
    public static final String PARAM_CAPITAL = "P_CAPITAL";
    public static final String PARAM_DATE_MAD = "P_DATE_MAD";
    public static final String PARAM_DATE_RECEPTION = "P_DATE_RECEPTION";
    public static final String PARAM_DIVERS = "P_DIVERS";
    public static final String PARAM_EXERCICE = "P_EXERCICE";
    public static final String PARAM_EXPLICATIONS = "P_EXPLICATIONS";
    public static final String PARAM_FORTUNE = "P_FORTUNE";
    public static final String PARAM_GENRE_AFF = "P_GENRE_AFF";
    public static final String PARAM_GENRE_TAX = "P_GENRE_TAX";
    public static final String PARAM_IFD = "P_IFD";
    public static final String PARAM_IMPO_DEPENSE = "P_IMPO_DEPENSE";
    public static final String PARAM_IMPOSITION = "P_IMPOSITION";
    public static final String PARAM_INDEM_JOUR = "P_INDEM_JOUR";
    public static final String PARAM_NOM = "P_NOM";
    public static final String PARAM_NOM_AFC = "P_NOM_AFC";
    public static final String PARAM_NOM_CON = "P_NOM_CON";
    public static final String PARAM_NSS = "P_NSS";
    public static final String PARAM_NUM_CAISSE = "P_NUM_CAISSE";
    public static final String PARAM_NUM_COMM = "P_NUM_COMM";
    public static final String PARAM_NUM_CONTRI = "P_NUM_CONTRI";
    public static final String PARAM_NUM_DEMANDE = "P_NUM_DEMANDE";
    public static final String PARAM_NUMAFF_RECU = "P_NUMAFF_RECU";
    public static final String PARAM_NUMAVS_CON = "P_NUMAVS_CON";
    public static final String PARAM_NUMCONTRI_RECU = "P_NUMCONTRI_RECU";
    public static final String PARAM_OBSERVATIONS = "P_OBSERVATIONS";
    public static final String PARAM_PENSION = "P_PENSION";
    public static final String PARAM_PENSION_ALIM = "P_PENSION_ALIM";
    public static final String PARAM_PERS_NI = "P_PERS_NI";
    public static final String PARAM_PRENOM = "P_PRENOM";
    public static final String PARAM_PRENOM_AFC = "P_PRENOM_AFC";
    public static final String PARAM_PRENOM_CON = "P_PRENOM_CON";
    public static final String PARAM_RENTE_INVALID = "P_RENTE_INVALID";
    public static final String PARAM_RENTE_VIAGERE = "P_RENTE_VIAGERE";
    public static final String PARAM_RENTE_VIEIL = "P_RENTE_VIEIL";
    public static final String PARAM_RETRAITE = "P_RETRAITE";
    public static final String PARAM_REVENU = "P_REVENU";
    public static final String PARAM_TAX_OFFICE = "P_TAX_OFFICE";
    public static final String PARAM_TIERS_ADRESSE = "P_TIERS_ADRESSE";
    public static final String PARAM_TIERS_NOMPRENOM = "P_TIERS_NOMPRENOM";
    // PARAMS TIERS
    public static final String PARAM_TITRE = "P_TITRE";
}
