package ch.globaz.pyxis.domaine.constantes;

/**
 * La liste des pays avec leur code ISO selon la tabelle sur <a
 * href="http://www.iso.org/iso/fr/french_country_names_and_code_elements.htm">le site d'ISO</a>
 */
public enum CodeIsoPays {

    // @formatter:off
	AFGHANISTAN("AF"),
	AFRIQUE_DU_SUD("ZA"),
	ALAND__ILES("AX"),
	ALBANIE("AL"),
	ALGERIE("DZ"),
	ALLEMAGNE("DE"),
	ANDORRE("AD"),
	ANGOLA("AO"),
	ANGUILLA("AI"),
	ANTARCTIQUE("AQ"),
	ANTIGUA_ET_BARBUDA("AG"),
	ARABIE_SAOUDITE("SA"),
	ARGENTINE("AR"),
	ARMENIE("AM"),
	ARUBA("AW"),
	AUSTRALIE("AU"),
	AUTRICHE("AT"),
	AZERBAIDJAN("AZ"),
	BAHAMAS("BS"),
	BAHREIN("BH"),
	BANGLADESH("BD"),
	BARBADE("BB"),
	BELARUS("BY"),
	BELGIQUE("BE"),
	BELIZE("BZ"),
	BENIN("BJ"),
	BERMUDES("BM"),
	BHOUTAN("BT"),
	BOLIVIE__ETAT_PLURINATIONAL_DE("BO"),
	BONAIRE__SAINT_EUSTACHE_ET_SABA("BQ"),
	BOSNIE_HERZEGOVINE("BA"),
	BOTSWANA("BW"),
	BOUVET__ILE("BV"),
	BRESIL("BR"),
	BRUNEI_DARUSSALAM("BN"),
	BULGARIE("BG"),
	BURKINA_FASO("BF"),
	BURUNDI("BI"),
	CAIMANES__ILES("KY"),
	CAMBODGE("KH"),
	CAMEROUN("CM"),
	CANADA("CA"),
	CAP_VERT("CV"),
	CENTRAFRICAINE__REPUBLIQUE("CF"),
	CHILI("CL"),
	CHINE("CN"),
	CHRISTMAS__ILE("CX"),
	CHYPRE("CY"),
	COCOS__ILES("CC"),
	COLOMBIE("CO"),
	COMORES("KM"),
	CONGO("CG"),
	CONGO__LA_REPUBLIQUE_DEMOCRATIQUE_DU("CD"),
	COOK__ILES("CK"),
	COREE__REPUBLIQUE_DE("KR"),
	COREE__REPUBLIQUE_POPULAIRE_DEMOCRATIQUE_DE("KP"),
	COSTA_RICA("CR"),
	COTE_D_IVOIRE("CI"),
	CROATIE("HR"),
	CUBA("CU"),
	CURACAO("CW"),
	DANEMARK("DK"),
	DJIBOUTI("DJ"),
	DOMINICAINE__REPUBLIQUE("DO"),
	DOMINIQUE("DM"),
	EGYPTE("EG"),
	EL_SALVADOR("SV"),
	EMIRATS_ARABES_UNIS("AE"),
	EQUATEUR("EC"),
	ERYTHREE("ER"),
	ESPAGNE("ES"),
	ESTONIE("EE"),
	ETATS_UNIS("US"),
	ETHIOPIE("ET"),
	FALKLAND__ILES("FK"),
	FEROE__ILES("FO"),
	FIDJI("FJ"),
	FINLANDE("FI"),
	FRANCE("FR"),
	GABON("GA"),
	GAMBIE("GM"),
	GEORGIE("GE"),
	GEORGIE_DU_SUD_ET_LES_ILES_SANDWICH_DU_SUD("GS"),
	GHANA("GH"),
	GIBRALTAR("GI"),
	GRECE("GR"),
	GRENADE("GD"),
	GROENLAND("GL"),
	GUADELOUPE("GP"),
	GUAM("GU"),
	GUATEMALA("GT"),
	GUERNESEY("GG"),
	GUINEE("GN"),
	GUINEE_BISSAU("GW"),
	GUINEE_EQUATORIALE("GQ"),
	GUYANA("GY"),
	GUYANE_FRANCAISE("GF"),
	HAITI("HT"),
	HEARD_ET_MCDONALD__ILE("HM"),
	HONDURAS("HN"),
	HONG_KONG("HK"),
	HONGRIE("HU"),
	ILE_DE_MAN("IM"),
	ILES_MINEURES_ELOIGNEES_DES_ETATS_UNIS("UM"),
	ILES_VIERGES_BRITANNIQUES("VG"),
	ILES_VIERGES_DES_ETATS_UNIS("VI"),
	/**
	 * Vu tous les problèmes qu'une gestion stricte des codes ISO a eu en prod, j'ai ajouté ce code ISO afin de palier à d'ancien codes ou codes non-valides utilisés sur nos applic
	 */
	INCONNU(""),
	INDE("IN"),
	INDONESIE("ID"),
	IRAN__REPUBLIQUE_ISLAMIQUE("IR"),
	IRAQ("IQ"),
	IRLANDE("IE"),
	ISLANDE("IS"),
	ISRAEL("IL"),
	ITALIE("IT"),
	JAMAIQUE("JM"),
	JAPON("JP"),
	JERSEY("JE"),
	JORDANIE("JO"),
	KAZAKHSTAN("KZ"),
	KENYA("KE"),
	KIRGHIZISTAN("KG"),
	KIRIBATI("KI"),
	KOWEIT("KW"),
	LAO__REPUBLIQUE_DEMOCRATIQUE_POPULAIRE("LA"),
	LESOTHO("LS"),
	LETTONIE("LV"),
	LIBAN("LB"),
	LIBERIA("LR"),
	LIBYENNE__JAMAHIRIYA_ARABE("LY"),
	LIECHTENSTEIN("LI"),
	LITUANIE("LT"),
	LUXEMBOURG("LU"),
	MACAO("MO"),
	MACEDOINE__EX_REPUBLIQUE_YOUGOSLAVE_DE("MK"),
	MADAGASCAR("MG"),
	MALAISIE("MY"),
	MALAWI("MW"),
	MALDIVES("MV"),
	MALI("ML"),
	MALTE("MT"),
	MARIANNES_DU_NORD__ILES("MP"),
	MAROC("MA"),
	MARSHALL__ILES("MH"),
	MARTINIQUE("MQ"),
	MAURICE("MU"),
	MAURITANIE("MR"),
	MAYOTTE("YT"),
	MEXIQUE("MX"),
	MICRONESIE__ETATS_FEDERES_DE("FM"),
	MOLDOVA__REPUBLIQUE_DE("MD"),
	MONACO("MC"),
	MONGOLIE("MN"),
	MONTENEGRO("ME"),
	MONTSERRAT("MS"),
	MOZAMBIQUE("MZ"),
	MYANMAR("MM"),
	NAMIBIE("NA"),
	NAURU("NR"),
	NEPAL("NP"),
	NICARAGUA("NI"),
	NIGER("NE"),
	NIGERIA("NG"),
	NIUE("NU"),
	NORFOLK__ILE("NF"),
	NORVEGE("NO"),
	NOUVELLE_CALEDONIE("NC"),
	NOUVELLE_ZELANDE("NZ"),
	OCEAN_INDIEN__TERRITOIRE_BRITANNIQUE_DE_L("IO"),
	OMAN("OM"),
	OUGANDA("UG"),
	OUZBEKISTAN("UZ"),
	PAKISTAN("PK"),
	PALAOS("PW"),
	PALESTINIEN_OCCUPE__TERRITOIRE("PS"),
	PANAMA("PA"),
	PAPOUASIE_NOUVELLE_GUINEE("PG"),
	PARAGUAY("PY"),
	PAYS_BAS("NL"),
	PEROU("PE"),
	PHILIPPINES("PH"),
	PITCAIRN("PN"),
	POLOGNE("PL"),
	POLYNESIE_FRANCAISE("PF"),
	PORTO_RICO("PR"),
	PORTUGAL("PT"),
	QATAR("QA"),
	REUNION("RE"),
	ROUMANIE("RO"),
	ROYAUME_UNI("GB"),
	RUSSIE__FEDERATION_DE("RU"),
	RWANDA("RW"),
	SAHARA_OCCIDENTAL("EH"),
	SAINT_BARTHELEMY("BL"),
	SAINT_KITTS_ET_NEVIS("KN"),
	SAINT_MARIN("SM"),
	SAINT_MARTIN__PARTIE_FRANCAISE("MF"),
	SAINT_MARTIN__PARTIE_NEERLANDAISE("SX"),
	SAINT_PIERRE_ET_MIQUELON("PM"),
	SAINT_SIEGE__ETAT_DE_LA_CITE_DU_VATICAN("VA"),
	SAINT_VINCENT_ET_LES_GRENADINES("VC"),
	SAINTE_HELENE__ASCENSION_ET_TRISTAN_DA_CUNHA("SH"),
	SAINTE_LUCIE("LC"),
	SALOMON__ILES("SB"),
	SAMOA("WS"),
	SAMOA_AMERICAINES("AS"),
	SAO_TOME_ET_PRINCIPE("ST"),
	SENEGAL("SN"),
	SERBIE("RS"),
	SEYCHELLES("SC"),
	SIERRA_LEONE("SL"),
	SINGAPOUR("SG"),
	SLOVAQUIE("SK"),
	SLOVENIE("SI"),
	SOMALIE("SO"),
	SOUDAN("SD"),
	SRI_LANKA("LK"),
	SUEDE("SE"),
	SUISSE("CH"),
	SURINAME("SR"),
	SVALBARD_ET_ILE_JAN_MAYEN("SJ"),
	SWAZILAND("SZ"),
	SYRIENNE__REPUBLIQUE_ARABE("SY"),
	TADJIKISTAN("TJ"),
	TAIWAN__PROVINCE_DE_CHINE("TW"),
	TANZANIE__REPUBLIQUE_UNIE_DE("TZ"),
	TCHAD("TD"),
	TCHEQUE__REPUBLIQUE("CZ"),
	TERRES_AUSTRALES_FRANCAISES("TF"),
	THAILANDE("TH"),
	TIMOR_LESTE("TL"),
	TOGO("TG"),
	TOKELAU("TK"),
	TONGA("TO"),
	TRINITE_ET_TOBAGO("TT"),
	TUNISIE("TN"),
	TURKMENISTAN("TM"),
	TURKS_ET_CAIQUES__ILES("TC"),
	TURQUIE("TR"),
	TUVALU("TV"),
	UKRAINE("UA"),
	URUGUAY("UY"),
	VANUATU("VU"),
	VENEZUELA__REPUBLIQUE_BOLIVARIENNE_DU("VE"),
	VIET_NAM("VN"),
	WALLIS_ET_FUTUNA("WF"),
	YEMEN("YE"),
	ZAMBIE("ZM"),
	ZIMBABWE("ZW");
	// @formatter:on

    /**
     * <p>
     * Retourne l'énuméré correspondant au code ISO.
     * </p>
     * <p>
     * Si aucune valeur correspond à ce code ISO, le code {@link #INCONNU} sera retourné
     * </p>
     * 
     * @param codeIso
     *            un code ISO de pays, en majuscule ou minuscule (2 lettres)
     * @return la valeur de l'énuméré correspondant au code ISO passé en paramètre
     */
    public static CodeIsoPays parse(final String codeIso) {
        if ((codeIso == null) || (codeIso.length() != 2)) {
            throw new IllegalArgumentException("An ISO code for coutries must be made of 2 letters! Code used: "
                    + codeIso);
        }

        for (CodeIsoPays unCodeIso : CodeIsoPays.values()) {
            if (unCodeIso.getCodeIso().equals(codeIso.toUpperCase())) {
                return unCodeIso;
            }
        }

        return INCONNU;
    }

    private String codeIso;

    private CodeIsoPays(final String codeIso) {
        this.codeIso = codeIso;
    }

    /**
     * @return le code ISO du pays (deux lettres en majuscules)
     */
    public String getCodeIso() {
        return codeIso;
    }
}
