//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.10.04 at 12:29:02 PM CEST
//

package ch.globaz.perseus.businessimpl.services.statsOFS.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="person" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ue_person_id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;attribute name="ausbildung_id" type="{}shsCode" />
 *                           &lt;attribute name="geschlecht_id" type="{}shsCode" />
 *                           &lt;attribute name="zivilstand_id" type="{}shsCode" />
 *                           &lt;attribute name="verwandtschaftsgrad_id" type="{}shsCode" />
 *                           &lt;attribute name="nationalitaet_land_id" type="{}shsNationalitaet" />
 *                           &lt;attribute name="aufenthaltsstatus_id" type="{}shsCode" />
 *                           &lt;attribute name="beschaeftigungsgrad_id" type="{}shsCode" />
 *                           &lt;attribute name="invaliditaetsgrad_id" type="{}shsCode" />
 *                           &lt;attribute name="hilflosigkeitsgrad_id" type="{}shsCode" />
 *                           &lt;attribute name="geburtsjahr" type="{}shsCode" />
 *                           &lt;attribute name="tagmonat" type="{}shsTagMonat" />
 *                           &lt;attribute name="in_ch_seit_jahr" type="{}shsCode" />
 *                           &lt;attribute name="versichertennummer" use="required" type="{}shsVersichertennummer" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="einkommen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}shsEinkommen">
 *                           &lt;attribute name="ue_person_id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="erwerbsit" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}shsErwerbsit">
 *                           &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="skos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}shsSkos">
 *                           &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="albv_leistung" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}shsAlbvLeistung">
 *                           &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ue")
public class Ue {

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}shsAlbvLeistung">
     *                 &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "row" })
    public static class AlbvLeistung {

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}shsAlbvLeistung">
         *       &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Row extends ShsAlbvLeistung {

            @XmlAttribute(name = "ue_person_id", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger uePersonId;

            /**
             * Gets the value of the uePersonId property.
             * 
             * @return possible object is {@link BigInteger }
             * 
             */
            public BigInteger getUePersonId() {
                return uePersonId;
            }

            /**
             * Sets the value of the uePersonId property.
             * 
             * @param value
             *            allowed object is {@link BigInteger }
             * 
             */
            public void setUePersonId(BigInteger value) {
                uePersonId = value;
            }

        }

        protected List<Ue.AlbvLeistung.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Ue.AlbvLeistung.Row }
         * 
         * 
         */
        public List<Ue.AlbvLeistung.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Ue.AlbvLeistung.Row>();
            }
            return row;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}shsEinkommen">
     *                 &lt;attribute name="ue_person_id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "row" })
    public static class Einkommen {

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}shsEinkommen">
         *       &lt;attribute name="ue_person_id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Row extends ShsEinkommen {

            @XmlAttribute(name = "ue_person_id")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger uePersonId;

            /**
             * Gets the value of the uePersonId property.
             * 
             * @return possible object is {@link BigInteger }
             * 
             */
            public BigInteger getUePersonId() {
                return uePersonId;
            }

            /**
             * Sets the value of the uePersonId property.
             * 
             * @param value
             *            allowed object is {@link BigInteger }
             * 
             */
            public void setUePersonId(BigInteger value) {
                uePersonId = value;
            }

        }

        protected List<Ue.Einkommen.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Ue.Einkommen.Row }
         * 
         * 
         */
        public List<Ue.Einkommen.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Ue.Einkommen.Row>();
            }
            return row;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}shsErwerbsit">
     *                 &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "row" })
    public static class Erwerbsit {

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}shsErwerbsit">
         *       &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Row extends ShsErwerbsit {

            @XmlAttribute(name = "ue_person_id", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger uePersonId;

            /**
             * Gets the value of the uePersonId property.
             * 
             * @return possible object is {@link BigInteger }
             * 
             */
            public BigInteger getUePersonId() {
                return uePersonId;
            }

            /**
             * Sets the value of the uePersonId property.
             * 
             * @param value
             *            allowed object is {@link BigInteger }
             * 
             */
            public void setUePersonId(BigInteger value) {
                uePersonId = value;
            }

        }

        protected List<Ue.Erwerbsit.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Ue.Erwerbsit.Row }
         * 
         * 
         */
        public List<Ue.Erwerbsit.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Ue.Erwerbsit.Row>();
            }
            return row;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ue_person_id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="ausbildung_id" type="{}shsCode" />
     *                 &lt;attribute name="geschlecht_id" type="{}shsCode" />
     *                 &lt;attribute name="zivilstand_id" type="{}shsCode" />
     *                 &lt;attribute name="verwandtschaftsgrad_id" type="{}shsCode" />
     *                 &lt;attribute name="nationalitaet_land_id" type="{}shsNationalitaet" />
     *                 &lt;attribute name="aufenthaltsstatus_id" type="{}shsCode" />
     *                 &lt;attribute name="beschaeftigungsgrad_id" type="{}shsCode" />
     *                 &lt;attribute name="invaliditaetsgrad_id" type="{}shsCode" />
     *                 &lt;attribute name="hilflosigkeitsgrad_id" type="{}shsCode" />
     *                 &lt;attribute name="geburtsjahr" type="{}shsCode" />
     *                 &lt;attribute name="tagmonat" type="{}shsTagMonat" />
     *                 &lt;attribute name="in_ch_seit_jahr" type="{}shsCode" />
     *                 &lt;attribute name="versichertennummer" use="required" type="{}shsVersichertennummer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "row" })
    public static class Person {

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ue_person_id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="ausbildung_id" type="{}shsCode" />
         *       &lt;attribute name="geschlecht_id" type="{}shsCode" />
         *       &lt;attribute name="zivilstand_id" type="{}shsCode" />
         *       &lt;attribute name="verwandtschaftsgrad_id" type="{}shsCode" />
         *       &lt;attribute name="nationalitaet_land_id" type="{}shsNationalitaet" />
         *       &lt;attribute name="aufenthaltsstatus_id" type="{}shsCode" />
         *       &lt;attribute name="beschaeftigungsgrad_id" type="{}shsCode" />
         *       &lt;attribute name="invaliditaetsgrad_id" type="{}shsCode" />
         *       &lt;attribute name="hilflosigkeitsgrad_id" type="{}shsCode" />
         *       &lt;attribute name="geburtsjahr" type="{}shsCode" />
         *       &lt;attribute name="tagmonat" type="{}shsTagMonat" />
         *       &lt;attribute name="in_ch_seit_jahr" type="{}shsCode" />
         *       &lt;attribute name="versichertennummer" use="required" type="{}shsVersichertennummer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Row {

            @XmlAttribute(name = "aufenthaltsstatus_id")
            protected List<String> aufenthaltsstatusId;
            @XmlAttribute(name = "ausbildung_id")
            protected List<String> ausbildungId;
            @XmlAttribute(name = "beschaeftigungsgrad_id")
            protected List<String> beschaeftigungsgradId;
            @XmlAttribute
            protected List<String> geburtsjahr;
            @XmlAttribute(name = "geschlecht_id")
            protected List<String> geschlechtId;
            @XmlAttribute(name = "hilflosigkeitsgrad_id")
            protected List<String> hilflosigkeitsgradId;
            @XmlAttribute(name = "in_ch_seit_jahr")
            protected List<String> inChSeitJahr;
            @XmlAttribute(name = "invaliditaetsgrad_id")
            protected List<String> invaliditaetsgradId;
            @XmlAttribute(name = "nationalitaet_land_id")
            protected String nationalitaetLandId;
            @XmlAttribute
            protected String tagmonat;
            @XmlAttribute(name = "ue_person_id")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger uePersonId;
            @XmlAttribute(required = true)
            protected List<String> versichertennummer;
            @XmlAttribute(name = "verwandtschaftsgrad_id")
            protected List<String> verwandtschaftsgradId;
            @XmlAttribute(name = "zivilstand_id")
            protected List<String> zivilstandId;

            /**
             * Gets the value of the aufenthaltsstatusId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the aufenthaltsstatusId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getAufenthaltsstatusId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getAufenthaltsstatusId() {
                if (aufenthaltsstatusId == null) {
                    aufenthaltsstatusId = new ArrayList<String>();
                }
                return aufenthaltsstatusId;
            }

            /**
             * Gets the value of the ausbildungId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the ausbildungId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getAusbildungId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getAusbildungId() {
                if (ausbildungId == null) {
                    ausbildungId = new ArrayList<String>();
                }
                return ausbildungId;
            }

            /**
             * Gets the value of the beschaeftigungsgradId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the beschaeftigungsgradId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getBeschaeftigungsgradId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getBeschaeftigungsgradId() {
                if (beschaeftigungsgradId == null) {
                    beschaeftigungsgradId = new ArrayList<String>();
                }
                return beschaeftigungsgradId;
            }

            /**
             * Gets the value of the geburtsjahr property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the geburtsjahr property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getGeburtsjahr().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getGeburtsjahr() {
                if (geburtsjahr == null) {
                    geburtsjahr = new ArrayList<String>();
                }
                return geburtsjahr;
            }

            /**
             * Gets the value of the geschlechtId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the geschlechtId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getGeschlechtId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getGeschlechtId() {
                if (geschlechtId == null) {
                    geschlechtId = new ArrayList<String>();
                }
                return geschlechtId;
            }

            /**
             * Gets the value of the hilflosigkeitsgradId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the hilflosigkeitsgradId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getHilflosigkeitsgradId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getHilflosigkeitsgradId() {
                if (hilflosigkeitsgradId == null) {
                    hilflosigkeitsgradId = new ArrayList<String>();
                }
                return hilflosigkeitsgradId;
            }

            /**
             * Gets the value of the inChSeitJahr property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the inChSeitJahr property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getInChSeitJahr().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getInChSeitJahr() {
                if (inChSeitJahr == null) {
                    inChSeitJahr = new ArrayList<String>();
                }
                return inChSeitJahr;
            }

            /**
             * Gets the value of the invaliditaetsgradId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the invaliditaetsgradId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getInvaliditaetsgradId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getInvaliditaetsgradId() {
                if (invaliditaetsgradId == null) {
                    invaliditaetsgradId = new ArrayList<String>();
                }
                return invaliditaetsgradId;
            }

            /**
             * Gets the value of the nationalitaetLandId property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getNationalitaetLandId() {
                return nationalitaetLandId;
            }

            /**
             * Gets the value of the tagmonat property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getTagmonat() {
                return tagmonat;
            }

            /**
             * Gets the value of the uePersonId property.
             * 
             * @return possible object is {@link BigInteger }
             * 
             */
            public BigInteger getUePersonId() {
                return uePersonId;
            }

            /**
             * Gets the value of the versichertennummer property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the versichertennummer property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getVersichertennummer().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getVersichertennummer() {
                if (versichertennummer == null) {
                    versichertennummer = new ArrayList<String>();
                }
                return versichertennummer;
            }

            /**
             * Gets the value of the verwandtschaftsgradId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the verwandtschaftsgradId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getVerwandtschaftsgradId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getVerwandtschaftsgradId() {
                if (verwandtschaftsgradId == null) {
                    verwandtschaftsgradId = new ArrayList<String>();
                }
                return verwandtschaftsgradId;
            }

            /**
             * Gets the value of the zivilstandId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
             * make to the returned list will be present inside the JAXB object. This is why there is not a
             * <CODE>set</CODE> method for the zivilstandId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getZivilstandId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             * 
             * 
             */
            public List<String> getZivilstandId() {
                if (zivilstandId == null) {
                    zivilstandId = new ArrayList<String>();
                }
                return zivilstandId;
            }

            /**
             * Sets the value of the nationalitaetLandId property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setNationalitaetLandId(String value) {
                nationalitaetLandId = value;
            }

            /**
             * Sets the value of the tagmonat property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setTagmonat(String value) {
                tagmonat = value;
            }

            /**
             * Sets the value of the uePersonId property.
             * 
             * @param value
             *            allowed object is {@link BigInteger }
             * 
             */
            public void setUePersonId(BigInteger value) {
                uePersonId = value;
            }

        }

        protected List<Ue.Person.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Ue.Person.Row }
         * 
         * 
         */
        public List<Ue.Person.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Ue.Person.Row>();
            }
            return row;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}shsSkos">
     *                 &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "row" })
    public static class Skos {

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}shsSkos">
         *       &lt;attribute name="ue_person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Row extends ShsSkos {

            @XmlAttribute(name = "ue_person_id", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger uePersonId;

            /**
             * Gets the value of the uePersonId property.
             * 
             * @return possible object is {@link BigInteger }
             * 
             */
            public BigInteger getUePersonId() {
                return uePersonId;
            }

            /**
             * Sets the value of the uePersonId property.
             * 
             * @param value
             *            allowed object is {@link BigInteger }
             * 
             */
            public void setUePersonId(BigInteger value) {
                uePersonId = value;
            }

        }

        protected List<Ue.Skos.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Ue.Skos.Row }
         * 
         * 
         */
        public List<Ue.Skos.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Ue.Skos.Row>();
            }
            return row;
        }

    }

    @XmlElement(name = "albv_leistung")
    protected Ue.AlbvLeistung albvLeistung;

    protected Ue.Einkommen einkommen;

    protected Ue.Erwerbsit erwerbsit;

    protected Ue.Person person;

    protected Ue.Skos skos;

    /**
     * Gets the value of the albvLeistung property.
     * 
     * @return possible object is {@link Ue.AlbvLeistung }
     * 
     */
    public Ue.AlbvLeistung getAlbvLeistung() {
        return albvLeistung;
    }

    /**
     * Gets the value of the einkommen property.
     * 
     * @return possible object is {@link Ue.Einkommen }
     * 
     */
    public Ue.Einkommen getEinkommen() {
        return einkommen;
    }

    /**
     * Gets the value of the erwerbsit property.
     * 
     * @return possible object is {@link Ue.Erwerbsit }
     * 
     */
    public Ue.Erwerbsit getErwerbsit() {
        return erwerbsit;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return possible object is {@link Ue.Person }
     * 
     */
    public Ue.Person getPerson() {
        return person;
    }

    /**
     * Gets the value of the skos property.
     * 
     * @return possible object is {@link Ue.Skos }
     * 
     */
    public Ue.Skos getSkos() {
        return skos;
    }

    /**
     * Sets the value of the albvLeistung property.
     * 
     * @param value
     *            allowed object is {@link Ue.AlbvLeistung }
     * 
     */
    public void setAlbvLeistung(Ue.AlbvLeistung value) {
        albvLeistung = value;
    }

    /**
     * Sets the value of the einkommen property.
     * 
     * @param value
     *            allowed object is {@link Ue.Einkommen }
     * 
     */
    public void setEinkommen(Ue.Einkommen value) {
        einkommen = value;
    }

    /**
     * Sets the value of the erwerbsit property.
     * 
     * @param value
     *            allowed object is {@link Ue.Erwerbsit }
     * 
     */
    public void setErwerbsit(Ue.Erwerbsit value) {
        erwerbsit = value;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *            allowed object is {@link Ue.Person }
     * 
     */
    public void setPerson(Ue.Person value) {
        person = value;
    }

    /**
     * Sets the value of the skos property.
     * 
     * @param value
     *            allowed object is {@link Ue.Skos }
     * 
     */
    public void setSkos(Ue.Skos value) {
        skos = value;
    }

}
