package globaz.cygnus.api.TypesDeSoins;

public interface IRFCodeTypesDeSoins {

    int CODE_TYPE_DE_SOIN_DEVIS_DENTAIRE = 19;
    int CODE_TYPE_DE_SOIN_FRAIS_DENTAIRE = 15;
    int CODE_TYPE_DE_SOIN_FRAIS_REFUSES = 18;
    int CODE_TYPE_DE_SOIN_FRQP = 17;
    int CODE_TYPE_DE_SOIN_MAINTIEN_A_DOMICILE = 13;
    int CODE_TYPE_DE_SOIN_MOYENS_AUXILIAIRES_5 = 5;
    int CODE_TYPE_DE_SOIN_MOYENS_AUXILIAIRES_6 = 6;
    int CODE_TYPE_DE_SOIN_MOYENS_AUXILIAIRES_7 = 7;

    String SOUS_TYPE_12_7_AIDE_AU_MENAGE_PAR_AIDE_PRIVEE = "07";
    String SOUS_TYPE_13_2_AIDE_AU_MENAGE_PAR_AIDE_PRIVEE = "02";
    String SOUS_TYPE_13_5_AIDE_AU_MENAGE_PAR_UN_MEMBRE_DE_LA_FAMILLE_13bOMPC = "05";
    String SOUS_TYPE_16_5_AMBULANCE = "05";

    // CONSTANTES POUR LES CODES UTILISATEURS SOUS TYPES DE SOINS
    String SOUS_TYPE_17_1_FRANCHISE_ET_QUOTEPARTS = "01";
    String SOUS_TYPE_2_1_REGIME_ALIMENTAIRE = "01";
    String SOUS_TYPE_2_2_REGIME_DIABETIQUE = "02";
    String SOUS_TYPE_20_1_FINANCEMENT_DES_SOINS = "01";
    String SOUS_TYPE_25_1_SOIN_A_DOMICILE = "01";
    String SOUS_TYPE_3_CHAISES_PERCEES = "01";
    String SOUS_TYPE_3_CORSET_ORTHOPEDIQUE = "03";
    String SOUS_TYPE_3_FRAIS_D_ENDOPROTHESES = "06";
    String SOUS_TYPE_3_LOMBOSTAT_ORTHOPEDIQUE = "02";
    String SOUS_TYPE_3_LUNETTES_VERRES_DE_CONTACT = "05";
    String SOUS_TYPE_3_MINERVE = "04";
    String SOUS_TYPE_3_PILES_ACOUSTIQUES = "07";

    String SOUS_TYPE_5_APPAREIL_ACOUSTIQUE = "01";
    String SOUS_TYPE_5_APPAREIL_ORTHOPEDIQUE = "06";
    String SOUS_TYPE_5_CHAUSSURES_ORTHOPEDIQUE = "02";
    String SOUS_TYPE_5_EPITHESE = "07";
    String SOUS_TYPE_5_FAUTEUIL_ROULANT = "03";
    String SOUS_TYPE_5_LUNETTES_LOUPE = "05";
    String SOUS_TYPE_5_PERRUQUE = "04";
    String SOUS_TYPE_5_PROTHESE = "08";

    String SOUS_TYPE_6_APPAREIL_ACOUSTIQUE = "01";
    String SOUS_TYPE_6_APPAREIL_ORTHOPEDIQUE = "07";
    String SOUS_TYPE_6_CHAISE_PERSEE = "10";
    String SOUS_TYPE_6_CHAUSSURES_ORTHOPEDIQUES = "03";
    String SOUS_TYPE_6_CORSET_ORTHOPEDIQUE = "12";
    String SOUS_TYPE_6_EPITHESE_OEIL = "08";
    String SOUS_TYPE_6_FAUTEUIL_ROULANT = "04";
    String SOUS_TYPE_6_LIT_ELECTRIQUE = "15";
    String SOUS_TYPE_6_LOMBOSTAT_ORTHOPEDIQUE = "11";
    String SOUS_TYPE_6_LUNETTES_LOUPE = "06";
    String SOUS_TYPE_6_LUNETTES_VERRES_CONTACTS = "14";
    String SOUS_TYPE_6_MINERVE = "13";
    String SOUS_TYPE_6_PERRUQUE = "05";
    String SOUS_TYPE_6_PILES_ACOUSTIQUE = "02";
    String SOUS_TYPE_6_POTENCE = "16";
    String SOUS_TYPE_6_PROTHESE_FACIALE = "09";

    // CONSTANTES POUR LES CODES UTILISATEURS TYPES DE SOINS
    String TYPE_1_COTISATIONS_PARITAIRES = "01";
    String TYPE_10_REPRISE_DE_LIT_ELECTRIQUE = "10";
    String TYPE_11_MOYENS_AUXILIAIRES_REMIS_EN_PRET_SUBSIDIAIREMENT_A_L_AI = "11";
    String TYPE_12_STRUCTURE_ET_SEJOURS = "12";
    String TYPE_13_MAINTIEN_A_DOMICILE = "13";
    String TYPE_14_ENCADREMENT_ET_ACCOMPAGNEMENT_SOCIAL = "14";
    String TYPE_15_FRAIS_DE_TRAITEMENT_DENTAIRE = "15";
    String TYPE_16_FRAIS_DE_TRANSPORT = "16";
    String TYPE_17_FRANCHISE_ET_QUOTEPARTS = "17";

    String TYPE_18_FRAIS_REFUSES = "18";
    String TYPE_19_DEVIS_DENTAIRE = "19";
    String TYPE_2_REGIME_ALIMENTAIRE = "02";
    String TYPE_20_FINANCEMENT_DES_SOINS = "20";
    String TYPE_21_REPRISE = "21";
    String TYPE_3_MOYENS_AUXILIAIRES = "03";
    String TYPE_4_RETOUCHES_COUTEUSES_DE_CHAUSSURES = "04";
    String TYPE_5_MOYENS_AUXILIAIRES = "05";
    String TYPE_6_REPARTITION_DES_MOYENS_AUXILIAIRES = "06";
    String TYPE_7_REPARTITION_DES_MOYENS_AUXILIAIRES_REMIS_EN_PRET_SUBSIDIAIREMENT_A_L_AI = "07";

    String TYPE_8_LOCATION_DE_MOYENS_AUXILIAIRES_SUBSIDIAIREMENT_A_L_AI = "08";

    String TYPE_9_FRAIS_DE_LIVRAISON = "09";
    String TYPE_25_SOIN_A_DOMICILE = "25";

}
