package globaz.corvus.utils.enumere.genre.prestations;

/**
 * @Author SCR
 */
public interface REGenresPrestations {

    String GENRE_10 = "10";
    String GENRE_110 = "110";
    String GENRE_113 = "113";
    String GENRE_12 = "12";
    String GENRE_13 = "13";
    String GENRE_14 = "14";
    String GENRE_15 = "15";
    String GENRE_150 = "150";
    String GENRE_16 = "16";
    // String GENRE_198 = "198"; // @see PRCodePrestationPC._158
    // String GENRE_199 = "199"; // @see PRCodePrestationPC._159
    String GENRE_20 = "20";
    String GENRE_210 = "210";
    String GENRE_213 = "213";
    String GENRE_22 = "22";
    String GENRE_23 = "23";
    String GENRE_24 = "24";
    String GENRE_25 = "25";
    String GENRE_250 = "250";
    String GENRE_26 = "26";
    String GENRE_33 = "33";
    String GENRE_34 = "34";
    String GENRE_35 = "35";
    String GENRE_36 = "36";
    String GENRE_43 = "43";
    String GENRE_44 = "44";
    String GENRE_45 = "45";
    String GENRE_46 = "46";
    String GENRE_50 = "50";
    String GENRE_52 = "52";
    String GENRE_53 = "53";
    String GENRE_54 = "54";
    String GENRE_55 = "55";
    String GENRE_56 = "56";
    String GENRE_70 = "70";
    String GENRE_72 = "72";
    String GENRE_73 = "73";
    String GENRE_74 = "74";
    String GENRE_75 = "75";
    String GENRE_76 = "76";
    String GENRE_81 = "81";
    String GENRE_82 = "82";
    String GENRE_83 = "83";
    String GENRE_84 = "84";
    String GENRE_85 = "85";
    String GENRE_86 = "86";
    String GENRE_87 = "87";
    String GENRE_88 = "88";
    String GENRE_89 = "89";
    String GENRE_91 = "91";
    String GENRE_92 = "92";
    String GENRE_93 = "93";
    String GENRE_94 = "94";
    String GENRE_95 = "95";
    String GENRE_96 = "96";
    String GENRE_97 = "97";

    int PC_AI = 150;
    int PC_ALLOCATION_NOEL_DOMAINE_ALLOCATION_NOEL = 199;
    int PC_ALLOCATION_NOEL_DOMAINE_RENTE = 198;
    int PC_AVS_SURVIVANT = 113;
    int PC_AVS_VIEILLESSE = 110;

    String PC_SOUS_TYPE_AI_COTISATION_AVS = "111";
    String PC_SOUS_TYPE_AI_DOMICILE = "106";
    String PC_SOUS_TYPE_AI_HOME_SASH = "107";
    String PC_SOUS_TYPE_AI_HOME_SASH_HORS_CANTON = "108";
    String PC_SOUS_TYPE_AI_HOME_SPAS = "109";
    String PC_SOUS_TYPE_AI_HOME_SPAS_HORS_CANTON = "110";
    String PC_SOUS_TYPE_AI_HOME = "112";
    String PC_SOUS_TYPE_AI_HOME_EPS = "117";
    String PC_SOUS_TYPE_AI_HOME_EPS_HORS_CANTON = "118";
    // valeur SPEN
    String PC_SOUS_TYPE_AI_HOME_SPEN = "119";
    String PC_SOUS_TYPE_AI_HOME_SPEN_HORS_CANTON = "120";
    // valeur pour DGEJ
    String PC_SOUS_TYPE_AI_HOME_DGEJ_SESAF = "129";
    String PC_SOUS_TYPE_AI_HOME_DGEJ_FOYER = "131";
    String PC_SOUS_TYPE_AI_HOME_DGEJ_FA = "133";
    String PC_SOUS_TYPE_AI_HOME_DGEJ_SESAF_HORS_CANTON = "130";
    String PC_SOUS_TYPE_AI_HOME_DGEJ_FOYER_HORS_CANTON = "132";
    String PC_SOUS_TYPE_AI_HOME_DGEJ_FA_HORS_CANTON = "134";



    String PC_SOUS_TYPE_AVS_COTISATION_AVS = "105";
    String PC_SOUS_TYPE_AVS_DOMICILE = "100";
    String PC_SOUS_TYPE_AVS_HOME_SASH = "101";
    String PC_SOUS_TYPE_AVS_HOME_SASH_HORS_CANTON = "102";
    String PC_SOUS_TYPE_AVS_HOME_SPAS = "103";
    String PC_SOUS_TYPE_AVS_HOME_SPAS_HORS_CANTON = "104";
    String PC_SOUS_TYPE_AVS_HOME = "114";
    String PC_SOUS_TYPE_AVS_HOME_EPS = "115";
    String PC_SOUS_TYPE_AVS_HOME_EPS_HORS_CANTON = "116";
    // valeur SPEN
    String PC_SOUS_TYPE_AVS_HOME_SPEN = "121";
    String PC_SOUS_TYPE_AVS_HOME_SPEN_HORS_CANTON = "122";

    // valeur pour DGEJ
    String PC_SOUS_TYPE_AVS_HOME_DGEJ_SESAF = "123";
    String PC_SOUS_TYPE_AVS_HOME_DGEJ_FOYER = "125";
    String PC_SOUS_TYPE_AVS_HOME_DGEJ_FA = "127";
    String PC_SOUS_TYPE_AVS_HOME_DGEJ_SESAF_HORS_CANTON = "124";
    String PC_SOUS_TYPE_AVS_HOME_DGEJ_FOYER_HORS_CANTON = "126";
    String PC_SOUS_TYPE_AVS_HOME_DGEJ_FA_HORS_CANTON = "128";

    int RENTE_API_DOMICILE_DEGRE_FAIBLE_IMPOTENCE_AI = 81;
    int RENTE_API_DOMICILE_DEGRE_FAIBLE_IMPOTENCE_AVEC_ACCOMPAGNEMENT_AI = 84;
    int RENTE_API_DOMICILE_DEGRE_FAIBLE_IMPOTENCE_AVEC_ACCOMPAGNEMENT_AVS = 89;
    int RENTE_API_DOMICILE_DEGRE_FAIBLE_IMPOTENCE_AVS = 85;
    int RENTE_API_DOMICILE_DEGRE_GRAVE_IMPOTENCE_AI = 83;
    int RENTE_API_DOMICILE_DEGRE_GRAVE_IMPOTENCE_AVS = 87;
    int RENTE_API_DOMICILE_DEGRE_MOYEN_IMPOTENCE_AI = 82;
    int RENTE_API_DOMICILE_DEGRE_MOYEN_IMPOTENCE_AVEC_ACCOMPAGNEMENT_AI = 88;
    int RENTE_API_DOMICILE_DEGRE_MOYEN_IMPOTENCE_AVS = 86;
    int RENTE_API_DOMICILE_OU_HOME_DEGRES_FAIBLE_IMPOTENCE_AI = 91;
    int RENTE_API_DOMICILE_OU_HOME_DEGRES_FAIBLE_IMPOTENCE_AVS = 95;
    int RENTE_API_DOMICILE_OU_HOME_DEGRES_GRAVE_IMPOTENCE_AI = 93;
    int RENTE_API_DOMICILE_OU_HOME_DEGRES_GRAVE_IMPOTENCE_AVS = 97;
    int RENTE_API_DOMICILE_OU_HOME_DEGRES_MOYEN_IMPOTENCE_AI = 92;
    int RENTE_API_DOMICILE_OU_HOME_DEGRES_MOYEN_IMPOTENCE_AVS = 96;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_CONJOINT_EXTRAORDINAIRE = 73;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_CONJOINT_ORDINAIRE = 53;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_ENFANT_LIEE_RENTE_MERE_EXTRAORDINAIRE = 75;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_ENFANT_LIEE_RENTE_MERE_ORDINAIRE = 55;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_ENFANT_LIEE_RENTE_PERE_EXTRAORDINAIRE = 74;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_ENFANT_LIEE_RENTE_PERE_ORDINAIRE = 54;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_ENFANT_RENTE_DOUBLE_EXTRAORDINAIRE = 76;
    int RENTE_COMPLEMENTAIRE_INVALIDITE_POUR_ENFANT_RENTE_DOUBLE_ORDINAIRE = 56;
    int RENTE_COMPLEMENTAIRE_SURVIVANT_RENTE_ORPHELIN_DE_MERE_EXTRAORDINAIRE = 25;
    int RENTE_COMPLEMENTAIRE_SURVIVANT_RENTE_ORPHELIN_DE_MERE_ORDINAIRE = 15;
    int RENTE_COMPLEMENTAIRE_SURVIVANT_RENTE_ORPHELIN_DE_PERE_EXTRAORDINAIRE = 24;
    int RENTE_COMPLEMENTAIRE_SURVIVANT_RENTE_ORPHELIN_DE_PERE_ORDINAIRE = 14;
    int RENTE_COMPLEMENTAIRE_SURVIVANT_RENTE_ORPHELIN_DOUBLE_EXTRAORDINAIRE = 26;
    int RENTE_COMPLEMENTAIRE_SURVIVANT_RENTE_ORPHELIN_DOUBLE_ORDINAIRE = 16;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_CONJOINT_EXTRAORDINAIRE = 43;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_CONJOINT_ORDINAIRE = 33;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_ENFANT_LIEE_RENTE_MERE_EXTRAORDINAIRE = 45;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_ENFANT_LIEE_RENTE_MERE_ORDINAIRE = 35;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_ENFANT_LIEE_RENTE_PERE_EXTRAORDINAIRE = 44;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_ENFANT_LIEE_RENTE_PERE_ORDINAIRE = 34;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_ENFANT_RENTE_DOUBLE_EXTRAORDINAIRE = 46;
    int RENTE_COMPLEMENTAIRE_VIEILLESSE_POUR_ENFANT_RENTE_DOUBLE_ORDINAIRE = 36;
    int RENTE_PRINCIPALE_INVALIDITE_EXTRAORDINAIRE = 70;
    int RENTE_PRINCIPALE_INVALIDITE_MOITIE_RENTE_EXTRAORDINAIRE = 72;
    int RENTE_PRINCIPALE_INVALIDITE_MOITIE_RENTE_ORDINAIRE = 52;
    int RENTE_PRINCIPALE_INVALIDITE_ORDINAIRE = 50;
    int RENTE_PRINCIPALE_SURVIVANT_EXTRAORDINAIRE = 23;
    int RENTE_PRINCIPALE_SURVIVANT_ORDINAIRE = 13;
    int RENTE_PRINCIPALE_VIEILLESSE_EXTRAORDINAIRE = 20;
    int RENTE_PRINCIPALE_VIEILLESSE_MOITIE_RENTE_EXTRAORDINAIRE = 22;
    int RENTE_PRINCIPALE_VIEILLESSE_MOITIE_RENTE_ORDINAIRE = 12;
    int RENTE_PRINCIPALE_VIEILLESSE_ORDINAIRE = 10;

    String[] GENRE_PRESTATIONS_AI = {GENRE_50, GENRE_52,GENRE_53,GENRE_54, GENRE_55, GENRE_56, GENRE_70, GENRE_72,GENRE_73,GENRE_74,GENRE_75, GENRE_76};

}
