//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.01.28 at 11:33:44 AM CET
//

package ch.globaz.amal.xmlns.am_0001._1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Taxation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Taxation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rub" type="{http://www.globaz.ch/amal/xmlns/am-0001/1}rubrique" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="periode" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="dateDec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ecTax" type="{http://www.globaz.ch/amal/xmlns/am-0001/1}EtatCivil" />
 *       &lt;attribute name="nbJours" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="rdu" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="genre" type="{http://www.globaz.ch/amal/xmlns/am-0001/1}GenreTaxation" />
 *       &lt;attribute name="codeProfession" type="{http://www.globaz.ch/amal/xmlns/am-0001/1}CodeProfession" />
 *       &lt;attribute name="departCommuneDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Taxation", propOrder = { "rub" })
public class Taxation {

    protected List<Rubrique> rub;
    @XmlAttribute
    protected BigInteger periode;
    @XmlAttribute
    protected String dateDec;
    @XmlAttribute
    protected BigInteger ecTax;
    @XmlAttribute
    protected BigInteger nbJours;
    @XmlAttribute
    protected BigInteger rdu;
    @XmlAttribute
    protected BigInteger genre;
    @XmlAttribute
    protected String codeProfession;
    @XmlAttribute
    protected String departCommuneDate;

    /**
     * Gets the value of the rub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the rub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Rubrique }
     * 
     * 
     */
    public List<Rubrique> getRub() {
        if (rub == null) {
            rub = new ArrayList<Rubrique>();
        }
        return rub;
    }

    /**
     * Gets the value of the periode property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setPeriode(BigInteger value) {
        periode = value;
    }

    /**
     * Gets the value of the dateDec property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getDateDec() {
        return dateDec;
    }

    /**
     * Sets the value of the dateDec property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDateDec(String value) {
        dateDec = value;
    }

    /**
     * Gets the value of the ecTax property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getEcTax() {
        return ecTax;
    }

    /**
     * Sets the value of the ecTax property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setEcTax(BigInteger value) {
        ecTax = value;
    }

    /**
     * Gets the value of the nbJours property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNbJours() {
        return nbJours;
    }

    /**
     * Sets the value of the nbJours property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setNbJours(BigInteger value) {
        nbJours = value;
    }

    /**
     * Gets the value of the rdu property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getRdu() {
        return rdu;
    }

    /**
     * Sets the value of the rdu property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setRdu(BigInteger value) {
        rdu = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setGenre(BigInteger value) {
        genre = value;
    }

    /**
     * Gets the value of the codeProfession property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getCodeProfession() {
        return codeProfession;
    }

    /**
     * Sets the value of the codeProfession property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodeProfession(String value) {
        codeProfession = value;
    }

    /**
     * Gets the value of the departCommuneDate property.
     * 
     * @return
     *         possible object is {@link String }
     * 
     */
    public String getDepartCommuneDate() {
        return departCommuneDate;
    }

    /**
     * Sets the value of the departCommuneDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDepartCommuneDate(String value) {
        departCommuneDate = value;
    }

}
